# Generated by Django 4.2.7 on 2026-03-27 13:01

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lipaidox", "0001_initial"),
        (
            "lipaidox_auth",
            "0002_remove_user_tenant_id_emailverification_tenant_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecuritySettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("two_fa_enabled", models.BooleanField(default=False)),
                (
                    "two_fa_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sms", "SMS"),
                            ("email", "Email"),
                            ("authenticator_app", "Authenticator App"),
                            ("backup_code", "Backup Code"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "two_fa_phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "two_fa_email",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                ("two_fa_secret", models.TextField(blank=True, null=True)),
                ("two_fa_enabled_at", models.DateTimeField(blank=True, null=True)),
                ("two_fa_last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "backup_codes_hash",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), default=list, size=None
                    ),
                ),
                (
                    "backup_codes_generated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("backup_codes_remaining", models.IntegerField(default=0)),
                (
                    "account_risk_score",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
                ),
                ("risk_score_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "risk_flags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), default=list, size=None
                    ),
                ),
                ("login_notification_email", models.BooleanField(default=True)),
                ("login_notification_sms", models.BooleanField(default=False)),
                (
                    "trusted_ips",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=45),
                        default=list,
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "security_settings",
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login_success", "Login Success"),
                            ("login_failed", "Login Failed"),
                            ("password_changed", "Password Changed"),
                            ("email_changed", "Email Changed"),
                            ("phone_changed", "Phone Changed"),
                            ("two_fa_enabled", "2FA Enabled"),
                            ("two_fa_disabled", "2FA Disabled"),
                            ("two_fa_failed", "2FA Failed"),
                            ("device_added", "Device Added"),
                            ("device_removed", "Device Removed"),
                            ("device_trusted", "Device Trusted"),
                            ("suspicious_login", "Suspicious Login"),
                            ("account_locked", "Account Locked"),
                            ("account_unlocked", "Account Unlocked"),
                            ("session_revoked", "Session Revoked"),
                            ("password_reset_requested", "Password Reset Requested"),
                            ("password_reset_completed", "Password Reset Completed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=45, null=True)),
                (
                    "device_fingerprint",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "risk_score_before",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "risk_score_after",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "security_events",
            },
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed_password", "Failed Password"),
                            ("failed_2fa", "Failed 2FA"),
                            ("failed_locked", "Failed Locked"),
                            ("failed_suspended", "Failed Suspended"),
                            ("failed_unverified", "Failed Unverified"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.CharField(blank=True, max_length=45, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                            ("desktop", "Desktop"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("browser", models.CharField(blank=True, max_length=100, null=True)),
                ("os", models.CharField(blank=True, max_length=100, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("session_id", models.UUIDField(blank=True, null=True)),
                ("two_fa_used", models.BooleanField(default=False)),
                (
                    "two_fa_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sms", "SMS"),
                            ("email", "Email"),
                            ("authenticator_app", "Authenticator App"),
                            ("backup_code", "Backup Code"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True, null=True)),
                ("is_suspicious", models.BooleanField(default=False)),
                ("suspicious_reason", models.TextField(blank=True, null=True)),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "login_history",
            },
        ),
        migrations.CreateModel(
            name="DeviceSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("device_fingerprint", models.CharField(max_length=255)),
                (
                    "device_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                            ("desktop", "Desktop"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("browser", models.CharField(blank=True, max_length=100, null=True)),
                ("os", models.CharField(blank=True, max_length=100, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=45, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("is_trusted", models.BooleanField(default=False)),
                ("trusted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                            ("logged_out", "Logged Out"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("last_active_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "refresh_token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_session",
                        to="lipaidox_auth.refreshtoken",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "device_sessions",
            },
        ),
        migrations.CreateModel(
            name="TwoFAAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("sms", "SMS"),
                            ("email", "Email"),
                            ("authenticator_app", "Authenticator App"),
                            ("backup_code", "Backup Code"),
                        ],
                        max_length=20,
                    ),
                ),
                ("code_hash", models.CharField(max_length=255)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                            ("already_used", "Already Used"),
                        ],
                        default="failed",
                        max_length=15,
                    ),
                ),
                ("ip_address", models.CharField(blank=True, max_length=45, null=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_fa_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "two_fa_attempts",
                "indexes": [
                    models.Index(fields=["user"], name="idx_two_fa_attempts_user"),
                    models.Index(fields=["result"], name="idx_two_fa_attempts_result"),
                    models.Index(
                        fields=["created_at"], name="idx_two_fa_attempts_created"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="twofaattempt",
            constraint=models.UniqueConstraint(
                fields=("code_hash",), name="two_fa_attempts_code_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="securitysettings",
            index=models.Index(fields=["user"], name="idx_security_settings_user"),
        ),
        migrations.AddIndex(
            model_name="securitysettings",
            index=models.Index(
                fields=["two_fa_enabled"], name="idx_security_settings_2fa"
            ),
        ),
        migrations.AddIndex(
            model_name="securitysettings",
            index=models.Index(
                fields=["-account_risk_score"], name="idx_security_settings_risk"
            ),
        ),
        migrations.AddConstraint(
            model_name="securitysettings",
            constraint=models.UniqueConstraint(
                fields=("user",), name="security_settings_user_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="securitysettings",
            constraint=models.CheckConstraint(
                check=models.Q(("account_risk_score__range", (0, 1))),
                name="risk_score_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="securitysettings",
            constraint=models.CheckConstraint(
                check=models.Q(("backup_codes_remaining__gte", 0)),
                name="backup_codes_check",
            ),
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(fields=["user"], name="idx_security_events_user"),
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(fields=["event_type"], name="idx_security_events_type"),
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(
                fields=["created_at"], name="idx_security_events_created"
            ),
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(fields=["user"], name="idx_login_history_user"),
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(fields=["result"], name="idx_login_history_result"),
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(fields=["ip_address"], name="idx_login_history_ip"),
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(
                fields=["is_suspicious"], name="idx_login_history_suspicious"
            ),
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(fields=["logged_at"], name="idx_login_history_logged"),
        ),
        migrations.AddIndex(
            model_name="devicesession",
            index=models.Index(fields=["user"], name="idx_device_sessions_user"),
        ),
        migrations.AddIndex(
            model_name="devicesession",
            index=models.Index(
                fields=["device_fingerprint"], name="idx_device_sessions_fp"
            ),
        ),
        migrations.AddIndex(
            model_name="devicesession",
            index=models.Index(fields=["status"], name="idx_device_sessions_status"),
        ),
        migrations.AddIndex(
            model_name="devicesession",
            index=models.Index(
                fields=["is_trusted"], name="idx_device_sessions_trusted"
            ),
        ),
        migrations.AddIndex(
            model_name="devicesession",
            index=models.Index(
                fields=["last_active_at"], name="idx_device_sessions_last"
            ),
        ),
        migrations.AddConstraint(
            model_name="devicesession",
            constraint=models.UniqueConstraint(
                fields=("user", "device_fingerprint"),
                name="device_sessions_fingerprint_user_unique",
            ),
        ),
    ]
