# Generated by Django 4.2.7 on 2026-09-19 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('message', models.TextField(blank=True, default='')),
                ('app_version', models.CharField(blank=True, default='', max_length=30)),
                ('platform', models.CharField(blank=True, default='', max_length=40)),
                ('app_id', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rating'], name='idx_app_feedback_rating'), models.Index(fields=['user', '-created_at'], name='idx_app_feedback_user')],
            },
        ),
        migrations.AddConstraint(
            model_name='appfeedback',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='app_feedback_rating_1_5'),
        ),
    ]
