# Generated by Django 4.2.7 on 2026-03-27 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lipaidox", "0001_initial"),
        ("lipaidox_security", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new_subscriber", "New Subscriber"),
                            ("subscriber_cancelled", "Subscriber Cancelled"),
                            ("new_tip_received", "New Tip Received"),
                            ("new_ppv_purchase", "New PPV Purchase"),
                            ("new_follower", "New Follower"),
                            ("new_comment", "New Comment"),
                            ("new_like", "New Like"),
                            ("payout_completed", "Payout Completed"),
                            ("payout_failed", "Payout Failed"),
                            ("kyc_approved", "KYC Approved"),
                            ("kyc_rejected", "KYC Rejected"),
                            (
                                "kyc_resubmission_requested",
                                "KYC Resubmission Requested",
                            ),
                            ("credit_gifted", "Credit Gifted"),
                            ("plan_renewed", "Plan Renewed"),
                            ("plan_cancelled", "Plan Cancelled"),
                            ("plan_expired", "Plan Expired"),
                            ("creator_went_live", "Creator Went Live"),
                            ("new_content_posted", "New Content Posted"),
                            ("content_unlocked", "Content Unlocked"),
                            ("subscription_renewed", "Subscription Renewed"),
                            ("subscription_expiring", "Subscription Expiring"),
                            ("tip_sent_confirmed", "Tip Sent Confirmed"),
                            ("credits_purchased", "Credits Purchased"),
                            ("announcement", "Announcement"),
                            ("security_alert", "Security Alert"),
                            ("account_suspended", "Account Suspended"),
                            ("account_reactivated", "Account Reactivated"),
                            ("password_changed", "Password Changed"),
                            ("new_login_detected", "New Login Detected"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("image_url", models.URLField(blank=True, null=True)),
                ("action_url", models.URLField(blank=True, null=True)),
                (
                    "action_label",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("failed", "Failed"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("group_key", models.CharField(blank=True, max_length=100, null=True)),
                ("group_count", models.IntegerField(default=1)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("email_enabled", models.BooleanField(default=True)),
                ("sms_enabled", models.BooleanField(default=False)),
                ("push_enabled", models.BooleanField(default=True)),
                ("notify_new_subscriber", models.BooleanField(default=True)),
                ("notify_new_tip", models.BooleanField(default=True)),
                ("notify_new_ppv_purchase", models.BooleanField(default=True)),
                ("notify_new_follower", models.BooleanField(default=True)),
                ("notify_new_comment", models.BooleanField(default=True)),
                ("notify_new_like", models.BooleanField(default=False)),
                ("notify_payout_completed", models.BooleanField(default=True)),
                ("notify_payout_failed", models.BooleanField(default=True)),
                ("notify_kyc_updates", models.BooleanField(default=True)),
                ("notify_creator_went_live", models.BooleanField(default=True)),
                ("notify_new_content_posted", models.BooleanField(default=True)),
                ("notify_subscription_expiring", models.BooleanField(default=True)),
                ("notify_security_alerts", models.BooleanField(default=True)),
                ("notify_announcements", models.BooleanField(default=True)),
                ("notify_plan_updates", models.BooleanField(default=True)),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                (
                    "quiet_hours_timezone",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("email_digest_enabled", models.BooleanField(default=False)),
                (
                    "email_digest_frequency",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly")],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="NotificationDeliveryLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "In-App"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("failed", "Failed"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "provider_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("provider_response", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("attempt_number", models.IntegerField(default=1)),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_logs",
                        to="lipaidox_notifications.notification",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_delivery_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_delivery_logs",
            },
        ),
        migrations.CreateModel(
            name="PushToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("fcm", "Firebase Cloud Messaging"),
                            ("apns", "Apple Push Notification Service"),
                            ("web_push", "Web Push"),
                        ],
                        max_length=10,
                    ),
                ),
                ("token", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="push_tokens",
                        to="lipaidox_security.devicesession",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "push_tokens",
                "indexes": [
                    models.Index(fields=["user"], name="idx_push_tokens_user_id"),
                    models.Index(fields=["platform"], name="idx_push_tokens_platform"),
                    models.Index(
                        fields=["is_active"], name="idx_push_tokens_is_active"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="pushtoken",
            constraint=models.UniqueConstraint(
                fields=("token",), name="push_tokens_token_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationpreference",
            index=models.Index(fields=["user"], name="idx_notification_prefs_user_id"),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.UniqueConstraint(
                fields=("user",), name="notification_preferences_user_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdeliverylog",
            index=models.Index(
                fields=["notification"], name="idx_delivery_logs_notification"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdeliverylog",
            index=models.Index(fields=["user"], name="idx_delivery_logs_user"),
        ),
        migrations.AddIndex(
            model_name="notificationdeliverylog",
            index=models.Index(fields=["channel"], name="idx_delivery_logs_channel"),
        ),
        migrations.AddIndex(
            model_name="notificationdeliverylog",
            index=models.Index(fields=["status"], name="idx_delivery_logs_status"),
        ),
        migrations.AddIndex(
            model_name="notificationdeliverylog",
            index=models.Index(
                fields=["attempted_at"], name="idx_delivery_logs_attempted"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationdeliverylog",
            constraint=models.CheckConstraint(
                check=models.Q(("attempt_number__gte", 1)), name="attempt_number_check"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["user"], name="idx_notifications_user_id"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type"], name="idx_notifications_type"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["status"], name="idx_notifications_status"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["is_read"], name="idx_notifications_is_read"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["priority"], name="idx_notifications_priority"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["created_at"], name="idx_notifications_created_at"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "group_key"], name="idx_notifications_group_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                check=models.Q(("group_count__gte", 1)), name="group_count_check"
            ),
        ),
    ]
