# Generated by Django 4.2.7 on 2026-08-11 06:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lipaidox', '0001_initial'),
        ('lipaidox_notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], max_length=20)),
                ('recipient_address', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('template_name', models.CharField(blank=True, max_length=100, null=True)),
                ('template_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('dismissed', 'Dismissed')], default='pending', max_length=15)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='lipaidox_notifications.notification')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_instances', to='lipaidox.tenant')),
            ],
            options={
                'db_table': 'notification_queue',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('notification_type', models.CharField(max_length=20)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], max_length=20)),
                ('subject_template', models.CharField(blank=True, max_length=255, null=True)),
                ('body_template', models.TextField()),
                ('variables_schema', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_instances', to='lipaidox.tenant')),
            ],
            options={
                'db_table': 'notification_templates',
                'indexes': [models.Index(fields=['notification_type', 'channel'], name='idx_notif_tmpl_type_channel'), models.Index(fields=['is_active'], name='idx_notif_tmpl_active')],
            },
        ),
        migrations.AddConstraint(
            model_name='notificationtemplate',
            constraint=models.UniqueConstraint(fields=('notification_type', 'channel'), name='notification_templates_unique'),
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['status'], name='idx_notification_queue_status'),
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['channel'], name='idx_notification_queue_channel'),
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['scheduled_at'], name='idx_notif_queue_scheduled'),
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['priority', 'status'], name='idx_notif_queue_prio_status'),
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['created_at'], name='idx_notification_queue_created'),
        ),
    ]
