# Generated by Django 4.2.7 on 2026-08-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipaidox_notifications', '0002_notificationqueue_notificationtemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushtoken',
            name='platform',
            field=models.CharField(choices=[('fcm', 'Firebase Cloud Messaging'), ('apns', 'Apple Push Notification Service'), ('web_push', 'Web Push'), ('expo', 'Expo Push Service')], max_length=10),
        ),
    ]
