# Generated by Django 4.2.7 on 2026-10-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipaidox_notifications', '0004_notification_action_text_notification_entity_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_subscriber', 'New Subscriber'), ('subscriber_cancelled', 'Subscriber Cancelled'), ('new_tip_received', 'New Tip Received'), ('new_ppv_purchase', 'New PPV Purchase'), ('new_follower', 'New Follower'), ('new_follow_request', 'New Follow Request'), ('follow_request_accepted', 'Follow Request Accepted'), ('new_comment', 'New Comment'), ('new_like', 'New Like'), ('payout_completed', 'Payout Completed'), ('payout_failed', 'Payout Failed'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('kyc_resubmission_requested', 'KYC Resubmission Requested'), ('credit_gifted', 'Credit Gifted'), ('plan_renewed', 'Plan Renewed'), ('plan_cancelled', 'Plan Cancelled'), ('plan_expired', 'Plan Expired'), ('creator_went_live', 'Creator Went Live'), ('new_content_posted', 'New Content Posted'), ('content_unlocked', 'Content Unlocked'), ('subscription_renewed', 'Subscription Renewed'), ('subscription_expiring', 'Subscription Expiring'), ('tip_sent_confirmed', 'Tip Sent Confirmed'), ('credits_purchased', 'Credits Purchased'), ('announcement', 'Announcement'), ('security_alert', 'Security Alert'), ('account_suspended', 'Account Suspended'), ('account_reactivated', 'Account Reactivated'), ('password_changed', 'Password Changed'), ('new_login_detected', 'New Login Detected')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notify_new_like',
            field=models.BooleanField(default=True),
        ),
    ]
