# Generated by Django 4.2.7 on 2026-03-23 17:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lipaidox", "0001_initial"),
        ("lipaidox_creator_profile", "0002_remove_creatorprofile_display_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, max_length=2200, null=True),
                ),
                (
                    "content_format",
                    models.CharField(
                        choices=[
                            ("single_image", "Single Image"),
                            ("single_video", "Single Video"),
                            ("slideshow", "Slideshow"),
                            ("audio", "Audio"),
                            ("blog", "Blog"),
                            ("live_stream", "Live Stream"),
                        ],
                        default="single_image",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                            ("flagged", "Flagged"),
                            ("under_review", "Under Review"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "primary_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("one_time", "One-Time Payment"),
                            ("timed", "Timed Payment"),
                            ("subscription", "Subscription Required"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "one_time_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "timed_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("timed_duration_value", models.IntegerField(blank=True, null=True)),
                (
                    "timed_duration_unit",
                    models.CharField(
                        blank=True,
                        choices=[("hours", "Hours"), ("days", "Days")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("allow_download", models.BooleanField(default=False)),
                (
                    "platform_fee_percent",
                    models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
                ),
                ("is_continuous", models.BooleanField(default=False)),
                ("episode_number", models.IntegerField(blank=True, null=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.IntegerField(default=0)),
                ("like_count", models.IntegerField(default=0)),
                ("comment_count", models.IntegerField(default=0)),
                ("purchase_count", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=14),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "content",
            },
        ),
        migrations.CreateModel(
            name="ContentSeries",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                ("episode_count", models.IntegerField(default=0)),
                ("is_complete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "content_series",
            },
        ),
        migrations.CreateModel(
            name="ContentMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("thumbnail", "Thumbnail"),
                            ("pdf", "PDF Document"),
                            ("zip", "ZIP Archive"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_url", models.URLField(max_length=2000)),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("resolution", models.CharField(blank=True, max_length=20, null=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "slide_topic",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("slide_hint", models.TextField(blank=True, null=True)),
                ("is_preview_slide", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="lipaidox_content.content",
                    ),
                ),
            ],
            options={
                "db_table": "content_media",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("zip", "ZIP"),
                            ("rar", "RAR"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_url", models.URLField(max_length=2000)),
                ("file_name", models.CharField(max_length=255)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("download_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="lipaidox_content.content",
                    ),
                ),
            ],
            options={
                "db_table": "content_attachments",
            },
        ),
        migrations.CreateModel(
            name="ContentAccessRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("geo_restrictions", models.JSONField(blank=True, default=list)),
                ("subscriber_only_preview", models.BooleanField(default=False)),
                (
                    "preview_duration_seconds",
                    models.IntegerField(blank=True, null=True),
                ),
                ("preview_slide_count", models.IntegerField(blank=True, null=True)),
                ("allow_download", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_rules",
                        to="lipaidox_content.content",
                    ),
                ),
            ],
            options={
                "db_table": "content_access_rules",
            },
        ),
        migrations.AddField(
            model_name="content",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="episodes",
                to="lipaidox_content.contentseries",
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_instances",
                to="lipaidox.tenant",
            ),
        ),
        migrations.CreateModel(
            name="ContentTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tag", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags_list",
                        to="lipaidox_content.content",
                    ),
                ),
            ],
            options={
                "db_table": "content_tags",
                "unique_together": {("content", "tag")},
            },
        ),
        migrations.AddIndex(
            model_name="contentseries",
            index=models.Index(
                fields=["creator"], name="content_ser_creator_ac96d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentmedia",
            index=models.Index(
                fields=["media_type"], name="content_med_media_t_5931cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentmedia",
            index=models.Index(
                fields=["content", "sort_order"], name="content_med_content_cc5da7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(fields=["status"], name="content_status_1dd890_idx"),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["access_type"], name="content_access__b5f24e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["published_at"], name="content_publish_13b85e_idx"
            ),
        ),
    ]
