# Generated by Django 4.2.7 on 2026-03-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lipaidox_content", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="contentmedia",
            name="content_med_media_t_5931cd_idx",
        ),
        migrations.AddField(
            model_name="contentmedia",
            name="media_role",
            field=models.CharField(
                choices=[
                    ("main", "Main Content File"),
                    ("thumbnail", "Post Thumbnail"),
                    ("slideshow_image", "Additional Slideshow Image"),
                ],
                default="main",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="content_format",
            field=models.CharField(
                choices=[
                    ("single_image", "Single Image"),
                    ("single_video", "Single Video"),
                    ("audio", "Audio"),
                    ("blog", "Blog"),
                    ("live_stream", "Live Stream"),
                ],
                default="single_image",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="contentmedia",
            index=models.Index(
                fields=["media_role"], name="content_med_media_r_877f9c_idx"
            ),
        ),
    ]
