# Generated by Django 4.2.7 on 2026-03-26 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lipaidox", "0001_initial"),
        (
            "lipaidox_content",
            "0002_remove_contentmedia_content_med_media_t_5931cd_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("inappropriate_content", "Inappropriate Content"),
                            ("harassment", "Harassment or Bullying"),
                            ("hate_speech", "Hate Speech"),
                            ("violence", "Violence or Graphic Content"),
                            ("spam", "Spam or Misleading"),
                            ("copyright", "Copyright Infringement"),
                            ("privacy", "Privacy Violation"),
                            ("false_information", "False Information"),
                            ("impersonation", "Impersonation"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed explanation of the report", max_length=2000
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("under_review", "Under Review"),
                            ("resolved", "Resolved"),
                            ("rejected", "Rejected"),
                            ("escalated", "Escalated"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolution_notes",
                    models.TextField(blank=True, max_length=2000, null=True),
                ),
                (
                    "action_taken",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="lipaidox_content.content",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "content_reports",
            },
        ),
        migrations.CreateModel(
            name="ContentModerationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("reason", models.TextField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_logs",
                        to="lipaidox_content.content",
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_action",
                        to="lipaidox_content.contentreport",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "content_moderation_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="contentreport",
            index=models.Index(
                fields=["content", "status"], name="content_rep_content_fd83a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentreport",
            index=models.Index(
                fields=["reporter", "created_at"], name="content_rep_reporte_723ad7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentreport",
            index=models.Index(
                fields=["status", "created_at"], name="content_rep_status_c435df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentreport",
            index=models.Index(fields=["reason"], name="content_rep_reason_27ba7c_idx"),
        ),
        migrations.AddConstraint(
            model_name="contentreport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "under_review"])),
                fields=("reporter", "content"),
                name="unique_pending_report_per_user_content",
            ),
        ),
    ]
