# Generated by Django 4.2.7 on 2026-03-27 00:07

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lipaidox_creator_profile", "0004_usernamehistory_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lipaidox_admin_panel", "0001_initial"),
        ("lipaidox_content", "0003_contentreport_contentmoderationlog_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contentreport",
            name="unique_pending_report_per_user_content",
        ),
        migrations.RemoveIndex(
            model_name="contentreport",
            name="content_rep_content_fd83a1_idx",
        ),
        migrations.RemoveIndex(
            model_name="contentreport",
            name="content_rep_reporte_723ad7_idx",
        ),
        migrations.RemoveIndex(
            model_name="contentreport",
            name="content_rep_status_c435df_idx",
        ),
        migrations.RemoveField(
            model_name="contentreport",
            name="action_taken",
        ),
        migrations.RemoveField(
            model_name="contentreport",
            name="reporter",
        ),
        migrations.RemoveField(
            model_name="contentreport",
            name="resolution_notes",
        ),
        migrations.AddField(
            model_name="contentreport",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_reports_received",
                to="lipaidox_creator_profile.creatorprofile",
            ),
        ),
        migrations.AddField(
            model_name="contentreport",
            name="escalated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentreport",
            name="escalated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports_escalated",
                to="lipaidox_admin_panel.adminaccount",
            ),
        ),
        migrations.AddField(
            model_name="contentreport",
            name="escalation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentreport",
            name="evidence_urls",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(max_length=2000),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="contentreport",
            name="reported_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contentreport",
            name="resolution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("content_removed", "Content Removed"),
                    ("content_approved", "Content Approved"),
                    ("creator_warned", "Creator Warned"),
                    ("creator_suspended", "Creator Suspended"),
                    ("creator_banned", "Creator Banned"),
                    ("no_action", "No Action"),
                    ("escalated_to_legal", "Escalated to Legal"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contentreport",
            name="resolution_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contentattachment",
            name="attachment_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("zip", "ZIP"),
                    ("rar", "RAR"),
                    ("video", "Video"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contentmoderationlog",
            name="moderator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moderation_actions",
                to="lipaidox_admin_panel.adminaccount",
            ),
        ),
        migrations.AlterField(
            model_name="contentmoderationlog",
            name="reason",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="contentreport",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contentreport",
            name="reason",
            field=models.CharField(
                choices=[
                    ("spam", "Spam"),
                    ("misinformation", "Misinformation"),
                    ("harassment", "Harassment"),
                    ("hate_speech", "Hate Speech"),
                    ("explicit_content", "Explicit Content"),
                    ("copyright_violation", "Copyright Violation"),
                    ("scam", "Scam"),
                    ("impersonation", "Impersonation"),
                    ("self_harm", "Self Harm"),
                    ("violence", "Violence"),
                    ("illegal_content", "Illegal Content"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="contentreport",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports_reviewed",
                to="lipaidox_admin_panel.adminaccount",
            ),
        ),
        migrations.AlterField(
            model_name="contentreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("under_review", "Under Review"),
                    ("resolved", "Resolved"),
                    ("dismissed", "Dismissed"),
                    ("escalated", "Escalated"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="contentreport",
            index=models.Index(
                fields=["content"], name="content_rep_content_7b7f9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentreport",
            index=models.Index(
                fields=["reported_by"], name="content_rep_reporte_2ddb78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentreport",
            index=models.Index(
                fields=["creator"], name="content_rep_creator_979cd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentreport",
            index=models.Index(fields=["status"], name="content_rep_status_9fcf4e_idx"),
        ),
        migrations.AddIndex(
            model_name="contentreport",
            index=models.Index(
                fields=["created_at"], name="content_rep_created_23a0b8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentreport",
            constraint=models.UniqueConstraint(
                fields=("content", "reported_by"), name="content_reports_unique"
            ),
        ),
    ]
