# Generated by Django 4.2.7 on 2026-03-30 09:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("lipaidox_creator_profile", "0005_creatorprofile_content_blocks_count"),
        ("lipaidox_admin_panel", "0001_initial"),
        ("lipaidox", "0001_initial"),
        ("lipaidox_content", "0005_contentlicense"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentAppeal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Creator's bargaining/claim reason"),
                ),
                ("evidence_urls", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("in_review", "In Review"),
                            ("approved", "Approved (Restored)"),
                            ("denied", "Denied (Permanently Blocked)"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes during case management",
                        null=True,
                    ),
                ),
                (
                    "resolution_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason given to creator upon resolution",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appeals",
                        to="lipaidox_content.content",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_appeals",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "original_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appeals",
                        to="lipaidox_content.contentreport",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_appeals",
                        to="lipaidox_admin_panel.adminaccount",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "content_appeals",
                "ordering": ["-created_at"],
            },
        ),
    ]
