# Generated by Django 4.2.7 on 2026-04-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipaidox_content', '0007_contentseries_parent_sort_order_series_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentseries',
            options={'ordering': ['sort_order', 'created_at']},
        ),
        migrations.AlterField(
            model_name='content',
            name='content_format',
            field=models.CharField(choices=[('single_image', 'Single Image'), ('single_video', 'Single Video'), ('audio', 'Audio'), ('blog', 'Blog'), ('live_stream', 'Live Stream'), ('gallery', 'Gallery / Slideshow')], default='single_image', max_length=20),
        ),
        migrations.AlterField(
            model_name='contentmedia',
            name='media_role',
            field=models.CharField(choices=[('main', 'Main Content File'), ('thumbnail', 'Post Thumbnail'), ('preview', 'Video Preview (15s)'), ('slideshow_image', 'Additional Slideshow Image')], default='main', max_length=20),
        ),
        migrations.AddIndex(
            model_name='contentseries',
            index=models.Index(fields=['parent'], name='content_ser_parent__7f9768_idx'),
        ),
    ]
