# Generated by Django 4.2.7 on 2026-05-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lipaidox_content", "0008_alter_contentseries_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentattachment",
            name="thumbnail_url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
