# Generated by Django 4.2.7 on 2026-05-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lipaidox_content", "0009_add_thumbnail_url_to_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentattachment",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentattachment",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contentmedia",
            name="thumbnail_url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
