# Generated by Django 4.2.7 on 2026-07-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipaidox_content', '0012_content_reviews'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contentreview',
            new_name='content_rev_content_2a8d90_idx',
            old_name='creview_content_idx',
        ),
        migrations.RenameIndex(
            model_name='contentreview',
            new_name='content_rev_author__549849_idx',
            old_name='creview_author_idx',
        ),
        migrations.RenameIndex(
            model_name='contentreview',
            new_name='content_rev_status_e41323_idx',
            old_name='creview_status_idx',
        ),
        migrations.RenameIndex(
            model_name='contentreview',
            new_name='content_rev_rating_cc096b_idx',
            old_name='creview_rating_idx',
        ),
        migrations.RenameIndex(
            model_name='contentreview',
            new_name='content_rev_created_f142e9_idx',
            old_name='creview_created_idx',
        ),
        migrations.RenameIndex(
            model_name='contentreview',
            new_name='content_rev_content_c96268_idx',
            old_name='creview_content_status_cr_idx',
        ),
        migrations.RenameIndex(
            model_name='contentreviewhelpful',
            new_name='content_rev_review__70204f_idx',
            old_name='creview_help_review_idx',
        ),
        migrations.RenameIndex(
            model_name='contentreviewhelpful',
            new_name='content_rev_user_id_f9cb89_idx',
            old_name='creview_help_user_idx',
        ),
        migrations.AddField(
            model_name='content',
            name='style',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
