# Generated by Django 4.2.7 on 2026-07-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipaidox_content', '0013_rename_creview_content_idx_content_rev_content_2a8d90_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentreview',
            name='owner_replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentreview',
            name='owner_reply',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contentreview',
            name='owner_reply_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
