# Generated by Django 4.2.7 on 2026-07-14 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lipaidox', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lipaidox_content', '0014_contentreview_owner_replied_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('published', 'Published'), ('hidden', 'Hidden'), ('flagged', 'Flagged')], default='published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_comments', to=settings.AUTH_USER_MODEL)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lipaidox_content.content')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_instances', to='lipaidox.tenant')),
            ],
            options={
                'db_table': 'content_comments',
                'indexes': [models.Index(fields=['content'], name='content_com_content_df559c_idx'), models.Index(fields=['author'], name='content_com_author__2394cb_idx'), models.Index(fields=['status'], name='content_com_status_eb9b8b_idx'), models.Index(fields=['content', 'status', 'created_at'], name='content_com_content_a319e5_idx')],
            },
        ),
    ]
