# Generated by Django 4.2.7 on 2026-08-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipaidox_content', '0015_contentcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='followers_notified',
            field=models.BooleanField(default=False),
        ),
    ]
