# Generated by Django 4.2.7 on 2026-08-16 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lipaidox_content', '0016_content_followers_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='lipaidox_content.contentcomment'),
        ),
        migrations.AddIndex(
            model_name='contentcomment',
            index=models.Index(fields=['parent', 'status', 'created_at'], name='content_com_parent__11931d_idx'),
        ),
    ]
