# Generated by Django 4.2.7 on 2026-08-17 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lipaidox', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lipaidox_content', '0017_contentcomment_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='lipaidox_content.content')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_instances', to='lipaidox.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_bookmarks',
            },
        ),
        migrations.CreateModel(
            name='ContentLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='lipaidox_content.content')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_instances', to='lipaidox.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_likes',
                'indexes': [models.Index(fields=['content'], name='content_lik_content_88ec7b_idx'), models.Index(fields=['user'], name='content_lik_user_id_b300bf_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='contentlike',
            constraint=models.UniqueConstraint(fields=('user', 'content'), name='unique_like_per_user_content'),
        ),
        migrations.AddIndex(
            model_name='contentbookmark',
            index=models.Index(fields=['content'], name='content_boo_content_8fd8ca_idx'),
        ),
        migrations.AddIndex(
            model_name='contentbookmark',
            index=models.Index(fields=['user'], name='content_boo_user_id_c821a0_idx'),
        ),
        migrations.AddIndex(
            model_name='contentbookmark',
            index=models.Index(fields=['user', 'created_at'], name='content_boo_user_id_2dc2a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentbookmark',
            constraint=models.UniqueConstraint(fields=('user', 'content'), name='unique_bookmark_per_user_content'),
        ),
    ]
