# Generated by Django 4.2.7 on 2026-08-18 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lipaidox', '0001_initial'),
        ('lipaidox_content', '0018_contentbookmark_contentlike_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='lipaidox_content.content')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_instances', to='lipaidox.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_views',
                'indexes': [models.Index(fields=['content'], name='content_vie_content_08d152_idx'), models.Index(fields=['user'], name='content_vie_user_id_81b863_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='contentview',
            constraint=models.UniqueConstraint(fields=('user', 'content'), name='unique_view_per_user_content'),
        ),
    ]
