# Generated by Django 4.2.7 on 2026-09-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipaidox_content', '0020_content_location_hide_engagement_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='share_count',
            field=models.IntegerField(default=0),
        ),
    ]
