# Generated by Django 4.2.7 on 2026-03-31 13:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LostFoundItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title of the item", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Detailed description"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("electronics", "Electronics"),
                            ("documents", "Documents"),
                            ("clothing", "Clothing"),
                            ("jewelry", "Jewelry"),
                            ("accessories", "Accessories"),
                            ("bags", "Bags & Luggage"),
                            ("keys", "Keys"),
                            ("wallets", "Wallets & Cards"),
                            ("books", "Books & Media"),
                            ("sports", "Sports Equipment"),
                            ("tools", "Tools"),
                            ("medical", "Medical Items"),
                            ("pets", "Pets"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lost", "Lost"),
                            ("found", "Found"),
                            ("claimed", "Claimed"),
                            ("resolved", "Resolved"),
                            ("archived", "Archived"),
                        ],
                        default="lost",
                        max_length=20,
                    ),
                ),
                (
                    "location_lat",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "location_lng",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("location_address", models.TextField(blank=True)),
                (
                    "location_description",
                    models.TextField(
                        blank=True, help_text="Additional location details"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reported_date",
                    models.DateTimeField(
                        blank=True, help_text="When item was lost/found", null=True
                    ),
                ),
                ("claimed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "visual_search_result",
                    models.JSONField(
                        blank=True, default=dict, help_text="YOLOv8 + CLIP results"
                    ),
                ),
                (
                    "ai_detection_result",
                    models.JSONField(
                        blank=True, default=dict, help_text="Nonescape AI detection"
                    ),
                ),
                (
                    "qr_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="QR code data"
                    ),
                ),
                (
                    "price_comparison",
                    models.JSONField(
                        blank=True, default=dict, help_text="Scraped price data"
                    ),
                ),
                (
                    "deepfake_result",
                    models.JSONField(
                        blank=True, default=dict, help_text="DeepSafe analysis"
                    ),
                ),
                (
                    "community_consensus",
                    models.JSONField(
                        blank=True, default=dict, help_text="Voting statistics"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="Searchable tags"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=1,
                        help_text="1=Low, 5=High priority",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("view_count", models.PositiveIntegerField(default=0)),
                (
                    "claimer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claimed_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lost_found_items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_name", models.CharField(db_index=True, max_length=255)),
                ("normalized_name", models.CharField(db_index=True, max_length=255)),
                (
                    "prices",
                    models.JSONField(
                        default=dict, help_text="Prices from different sources"
                    ),
                ),
                (
                    "lowest_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "highest_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "average_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("source_count", models.PositiveIntegerField(default=0)),
                ("last_scraped", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "product_cache",
                "indexes": [
                    models.Index(
                        fields=["product_name"], name="product_cac_product_8308bc_idx"
                    ),
                    models.Index(
                        fields=["normalized_name"],
                        name="product_cac_normali_a337e0_idx",
                    ),
                    models.Index(
                        fields=["last_scraped"], name="product_cac_last_sc_0640ca_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="product_cac_is_acti_5a01d1_idx"
                    ),
                ],
                "unique_together": {("product_name", "normalized_name")},
            },
        ),
        migrations.CreateModel(
            name="ItemImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.PositiveIntegerField()),
                ("content_type", models.CharField(max_length=100)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("ai_class", models.CharField(blank=True, max_length=100)),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "embedding",
                    models.JSONField(
                        blank=True, help_text="CLIP embedding vector", null=True
                    ),
                ),
                ("is_processed", models.BooleanField(default=False)),
                ("processing_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="lost_found.lostfounditem",
                    ),
                ),
            ],
            options={
                "db_table": "item_images",
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "vote_type",
                    models.CharField(
                        choices=[
                            ("real", "Real/Authentic"),
                            ("fake", "Fake/Suspicious"),
                            ("helpful", "Helpful Information"),
                            ("inaccurate", "Inaccurate Information"),
                            ("spam", "Spam"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="lost_found.lostfounditem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "item_votes",
                "indexes": [
                    models.Index(fields=["item"], name="item_votes_item_id_1dafef_idx"),
                    models.Index(fields=["user"], name="item_votes_user_id_5457bd_idx"),
                    models.Index(
                        fields=["vote_type"], name="item_votes_vote_ty_6743b3_idx"
                    ),
                ],
                "unique_together": {("item", "user")},
            },
        ),
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query", models.CharField(max_length=500)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("results_count", models.PositiveIntegerField()),
                ("processing_time_ms", models.PositiveIntegerField()),
                ("ai_features_used", models.JSONField(blank=True, default=list)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "search_logs",
                "indexes": [
                    models.Index(
                        fields=["user"], name="search_logs_user_id_57f35c_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="search_logs_created_1842c5_idx"
                    ),
                    models.Index(fields=["query"], name="search_logs_query_5b6409_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("inappropriate", "Inappropriate Content"),
                            ("false_info", "False Information"),
                            ("duplicate", "Duplicate Item"),
                            ("resolved", "Already Resolved"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                ("is_reviewed", models.BooleanField(default=False)),
                ("moderator_note", models.TextField(blank=True)),
                ("action_taken", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="lost_found.lostfounditem",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "item_reports",
                "indexes": [
                    models.Index(
                        fields=["item"], name="item_report_item_id_6465ca_idx"
                    ),
                    models.Index(
                        fields=["reporter"], name="item_report_reporte_f7da46_idx"
                    ),
                    models.Index(
                        fields=["report_type"], name="item_report_report__d5f91e_idx"
                    ),
                    models.Index(
                        fields=["is_reviewed"], name="item_report_is_revi_9c89af_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("visual", "Visual Similarity"),
                            ("location", "Location Proximity"),
                            ("category", "Category Match"),
                            ("description", "Description Similarity"),
                            ("temporal", "Time-based Match"),
                            ("combined", "Combined Score"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "similarity_score",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "visual_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "location_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "category_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "temporal_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "ai_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(default=False, help_text="Confirmed by users"),
                ),
                (
                    "is_rejected",
                    models.BooleanField(
                        default=False, help_text="Rejected as false positive"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_a",
                        to="lost_found.lostfounditem",
                    ),
                ),
                (
                    "item_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_b",
                        to="lost_found.lostfounditem",
                    ),
                ),
            ],
            options={
                "db_table": "item_matches",
                "indexes": [
                    models.Index(
                        fields=["item_a"], name="item_matche_item_a__7fc470_idx"
                    ),
                    models.Index(
                        fields=["item_b"], name="item_matche_item_b__0166c0_idx"
                    ),
                    models.Index(
                        fields=["match_type"], name="item_matche_match_t_f44a0f_idx"
                    ),
                    models.Index(
                        fields=["similarity_score"],
                        name="item_matche_similar_2734c9_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="item_matche_created_516636_idx"
                    ),
                ],
                "unique_together": {("item_a", "item_b", "match_type")},
            },
        ),
        migrations.AddIndex(
            model_name="lostfounditem",
            index=models.Index(
                fields=["category"], name="lost_found__categor_585f7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lostfounditem",
            index=models.Index(fields=["status"], name="lost_found__status_0f5f01_idx"),
        ),
        migrations.AddIndex(
            model_name="lostfounditem",
            index=models.Index(
                fields=["created_at"], name="lost_found__created_185e88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lostfounditem",
            index=models.Index(
                fields=["location_lat", "location_lng"],
                name="lost_found__locatio_9c2e83_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lostfounditem",
            index=models.Index(
                fields=["priority"], name="lost_found__priorit_54baa5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lostfounditem",
            index=models.Index(
                fields=["is_featured"], name="lost_found__is_feat_9698d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itemimage",
            index=models.Index(fields=["item"], name="item_images_item_id_b431dd_idx"),
        ),
        migrations.AddIndex(
            model_name="itemimage",
            index=models.Index(
                fields=["ai_class"], name="item_images_ai_clas_4fda39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itemimage",
            index=models.Index(
                fields=["is_processed"], name="item_images_is_proc_86cd24_idx"
            ),
        ),
    ]
