# Generated by Django 4.2.7 on 2026-06-18 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lost_found", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField()),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="community_answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "community_answers",
                "ordering": ["-like_count", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunityPoll",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("options", models.JSONField(default=list)),
                ("duration_days", models.PositiveIntegerField(default=7)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("total_votes", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="community_polls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "community_polls",
                "ordering": ["-total_votes", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunityQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("body", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("all", "All"),
                            ("business", "Business"),
                            ("hotel", "Hotel"),
                            ("jobs", "Jobs"),
                            ("tech", "Tech"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("image_url", models.CharField(blank=True, max_length=500)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("answer_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="community_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "community_questions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunityPollVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("option_index", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="lost_found.communitypoll",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "community_poll_votes",
            },
        ),
        migrations.CreateModel(
            name="CommunityAnswerLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="lost_found.communityanswer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "community_answer_likes",
            },
        ),
        migrations.AddField(
            model_name="communityanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="lost_found.communityquestion",
            ),
        ),
        migrations.AddIndex(
            model_name="communityquestion",
            index=models.Index(
                fields=["category", "-created_at"],
                name="community_q_categor_ce3723_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="communityquestion",
            index=models.Index(
                fields=["-answer_count", "-view_count"],
                name="community_q_answer__9b4771_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="communitypollvote",
            unique_together={("poll", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="communityanswerlike",
            unique_together={("answer", "user")},
        ),
    ]
