# Generated by Django 4.2.7 on 2026-06-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lost_found", "0002_community_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitypoll",
            name="allow_comments",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="communitypoll",
            name="allow_write_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="communitypoll",
            name="hide_results_until_close",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="communitypoll",
            name="max_selections",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="communitypoll",
            name="poll_type",
            field=models.CharField(
                choices=[("single", "Single choice"), ("multiple", "Multiple choice")],
                default="single",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="communitypoll",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="communitypoll",
            name="verified_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="communitypoll",
            name="question",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="communityquestion",
            name="category",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("business", "Business"),
                    ("hotel", "Hotel"),
                    ("jobs", "Jobs"),
                    ("tech", "Tech"),
                    ("finance", "Finance"),
                    ("health", "Health"),
                    ("travel", "Travel"),
                    ("sports", "Sports"),
                    ("education", "Education"),
                    ("general", "General"),
                ],
                default="general",
                max_length=20,
            ),
        ),
    ]
