# Generated by Django 4.2.7 on 2026-06-22 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lost_found", "0006_vote_change"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "community_question_views",
            },
        ),
        migrations.RenameIndex(
            model_name="communityquestion",
            new_name="community_q_score_c0363b_idx",
            old_name="cq_score_created_idx",
        ),
        migrations.AlterField(
            model_name="communitypollvote",
            name="option",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="lost_found.polloption",
            ),
        ),
        migrations.AddField(
            model_name="questionview",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_views",
                to="lost_found.communityquestion",
            ),
        ),
        migrations.AddField(
            model_name="questionview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_views",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="questionview",
            index=models.Index(
                fields=["question", "user"], name="community_q_questio_b56c77_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="questionview",
            unique_together={("question", "user")},
        ),
    ]
