# Generated by Django 4.2.7 on 2026-06-22 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lost_found", "0007_add_question_view_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityanswer",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="lost_found.communityanswer",
            ),
        ),
        migrations.AddIndex(
            model_name="communityanswer",
            index=models.Index(
                fields=["question", "parent", "-created_at"],
                name="community_a_questio_0ed85f_idx",
            ),
        ),
    ]
