# Generated by Django 4.2.7 on 2026-07-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0010_questionview_source'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='questionview',
            new_name='community_q_questio_1439c2_idx',
            old_name='comm_qview_q_source_idx',
        ),
        migrations.RenameIndex(
            model_name='questionview',
            new_name='community_q_questio_afd425_idx',
            old_name='comm_qview_q_viewed_idx',
        ),
        migrations.AddField(
            model_name='communitypoll',
            name='share_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communitypoll',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
