# Generated by Django 4.2.7 on 2026-07-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0011_rename_comm_qview_q_source_idx_community_q_questio_1439c2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityquestion',
            name='share_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
