# Generated by Django 4.2.7 on 2026-03-30 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lipaidox", "0001_initial"),
        ("lipaidox_creator_profile", "0005_creatorprofile_content_blocks_count"),
        ("lms_identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstructorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("headline", models.CharField(blank=True, max_length=255, null=True)),
                ("specializations", models.JSONField(blank=True, default=list)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("total_reviews", models.IntegerField(default=0)),
                ("total_students", models.IntegerField(default=0)),
                ("total_courses", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending Review"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending_review",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lms_instructor",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lms_instructor_profiles",
            },
        ),
    ]
