# Generated by Django 4.2.7 on 2026-03-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms_identity", "0002_instructorprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="github",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="linkedin",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="portfolio",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="remote_preference",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="website",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="willing_to_relocate",
            field=models.BooleanField(default=False),
        ),
    ]
