# Generated by Django 4.2.7 on 2026-03-31 10:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        (
            "lms_identity",
            "0004_studentprofile_learning_preferences_workexperience_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AppearanceSetting",
            fields=[
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="lms_identity.studentprofile",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                ("language", models.CharField(default="en", max_length=10)),
                ("timezone", models.CharField(default="UTC", max_length=100)),
                ("date_format", models.CharField(default="YYYY-MM-DD", max_length=30)),
                (
                    "time_format",
                    models.CharField(
                        choices=[("12h", "12h"), ("24h", "24h")],
                        default="12h",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "db_table": "lms_appearance_settings",
            },
        ),
        migrations.CreateModel(
            name="DataSetting",
            fields=[
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="lms_identity.studentprofile",
                    ),
                ),
                ("low_data_mode", models.BooleanField(default=False)),
                ("auto_download", models.BooleanField(default=False)),
                ("download_wifi_only", models.BooleanField(default=True)),
                (
                    "video_quality",
                    models.CharField(
                        choices=[
                            ("auto", "Auto"),
                            ("480p", "480p"),
                            ("720p", "720p"),
                            ("1080p", "Full HD"),
                        ],
                        default="auto",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "lms_data_settings",
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="lms_identity.studentprofile",
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("push_enabled", models.BooleanField(default=True)),
                ("sms_enabled", models.BooleanField(default=False)),
                ("course_updates", models.BooleanField(default=True)),
                ("new_lessons", models.BooleanField(default=True)),
                ("quiz_reminders", models.BooleanField(default=True)),
                ("assignment_due", models.BooleanField(default=True)),
                ("cohort_sessions", models.BooleanField(default=True)),
                ("streak_reminders", models.BooleanField(default=True)),
                ("certificate_earned", models.BooleanField(default=True)),
                ("badge_earned", models.BooleanField(default=True)),
                ("job_matches", models.BooleanField(default=True)),
                ("marketing_emails", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "lms_notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="PrivacySetting",
            fields=[
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="lms_identity.studentprofile",
                    ),
                ),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("connections", "Connections"),
                            ("private", "Private"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("show_progress", models.BooleanField(default=True)),
                ("show_badges", models.BooleanField(default=True)),
                ("show_certificates", models.BooleanField(default=True)),
                ("show_activity", models.BooleanField(default=True)),
                ("allow_messaging", models.BooleanField(default=True)),
                ("show_in_talent_pool", models.BooleanField(default=True)),
                ("allow_employer_contact", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "lms_privacy_settings",
            },
        ),
        migrations.RemoveField(
            model_name="preferredcategory",
            name="student",
        ),
        migrations.RemoveField(
            model_name="preferredcategory",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="studentproject",
            name="student",
        ),
        migrations.RemoveField(
            model_name="studentproject",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="studentskill",
            name="student",
        ),
        migrations.RemoveField(
            model_name="studentskill",
            name="tenant",
        ),
        migrations.AlterModelOptions(
            name="educationrecord",
            options={"ordering": ["-start_date"]},
        ),
        migrations.AlterModelOptions(
            name="workexperience",
            options={"ordering": ["-start_date"]},
        ),
        migrations.RemoveField(
            model_name="educationrecord",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="externalcertification",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="workexperience",
            name="tenant",
        ),
        migrations.AlterField(
            model_name="educationrecord",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="education",
                to="lms_identity.studentprofile",
            ),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("remote", "Remote"),
                    ("hybrid", "Hybrid"),
                    ("onsite", "On-Site"),
                ],
                default="onsite",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experiences",
                to="lms_identity.studentprofile",
            ),
        ),
        migrations.DeleteModel(
            name="LearningGoal",
        ),
        migrations.DeleteModel(
            name="PreferredCategory",
        ),
        migrations.DeleteModel(
            name="StudentProject",
        ),
        migrations.DeleteModel(
            name="StudentSkill",
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("url", models.URLField(blank=True, max_length=500, null=True)),
                ("github_url", models.URLField(blank=True, max_length=500, null=True)),
                ("technologies", models.JSONField(blank=True, default=list)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="lms_identity.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "lms_student_projects",
            },
        ),
    ]
