# Generated by Django 4.2.7 on 2026-03-31 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("lipaidox", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lms_content", "0006_labsubmission"),
        ("lms_identity", "0005_learning_core_features"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("instructor", "Instructor"),
                            ("teaching_assistant", "Teaching Assistant"),
                        ],
                        default="instructor",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("can_create_courses", models.BooleanField(default=False)),
                ("can_manage_students", models.BooleanField(default=True)),
                ("can_view_analytics", models.BooleanField(default=True)),
                ("can_manage_payouts", models.BooleanField(default=False)),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="lms_identity.instructorprofile",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institution_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lms_institution_users",
            },
        ),
        migrations.CreateModel(
            name="CourseReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("review_note", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="lms_content.course",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_course_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_reviews",
                        to="lms_identity.studentprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "lms_course_reviews",
            },
        ),
        migrations.CreateModel(
            name="CourseAssignmentTeam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("instructor", "Instructor"),
                            ("teaching_assistant", "Teaching Assistant"),
                        ],
                        default="instructor",
                        max_length=20,
                    ),
                ),
                ("can_edit_content", models.BooleanField(default=True)),
                ("can_manage_students", models.BooleanField(default=True)),
                ("can_view_analytics", models.BooleanField(default=True)),
                ("can_grade_assignments", models.BooleanField(default=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_assignments",
                        to="lms_content.course",
                    ),
                ),
                (
                    "institution_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_assignments",
                        to="lms_identity.institutionuser",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "lms_course_assignment_teams",
            },
        ),
        migrations.CreateModel(
            name="InstructorPayout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_payout_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_transfer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("payout_date", models.DateTimeField(blank=True, null=True)),
                (
                    "course_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "platform_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="lms_identity.instructorprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "lms_instructor_payouts",
                "indexes": [
                    models.Index(fields=["instructor"], name="idx_inst_payout_inst"),
                    models.Index(fields=["status"], name="idx_inst_payout_status"),
                    models.Index(
                        fields=["-created_at"], name="idx_inst_payout_created"
                    ),
                    models.Index(
                        fields=["period_start"], name="idx_inst_payout_period"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="institutionuser",
            index=models.Index(fields=["institution"], name="idx_inst_user_inst"),
        ),
        migrations.AddIndex(
            model_name="institutionuser",
            index=models.Index(fields=["user"], name="idx_inst_user_user"),
        ),
        migrations.AddIndex(
            model_name="institutionuser",
            index=models.Index(fields=["role"], name="idx_inst_user_role"),
        ),
        migrations.AddIndex(
            model_name="institutionuser",
            index=models.Index(fields=["status"], name="idx_inst_user_status"),
        ),
        migrations.AlterUniqueTogether(
            name="institutionuser",
            unique_together={("institution", "user")},
        ),
        migrations.AddIndex(
            model_name="coursereview",
            index=models.Index(fields=["course"], name="idx_course_rev_course"),
        ),
        migrations.AddIndex(
            model_name="coursereview",
            index=models.Index(fields=["student"], name="idx_course_rev_student"),
        ),
        migrations.AddIndex(
            model_name="coursereview",
            index=models.Index(fields=["status"], name="idx_course_rev_status"),
        ),
        migrations.AddIndex(
            model_name="coursereview",
            index=models.Index(fields=["rating"], name="idx_course_rev_rating"),
        ),
        migrations.AddIndex(
            model_name="coursereview",
            index=models.Index(fields=["-created_at"], name="idx_course_rev_created"),
        ),
        migrations.AlterUniqueTogether(
            name="coursereview",
            unique_together={("course", "student")},
        ),
        migrations.AddIndex(
            model_name="courseassignmentteam",
            index=models.Index(fields=["course"], name="idx_course_team_course"),
        ),
        migrations.AddIndex(
            model_name="courseassignmentteam",
            index=models.Index(
                fields=["institution_user"], name="idx_course_team_user"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="courseassignmentteam",
            unique_together={("course", "institution_user")},
        ),
    ]
