# Generated by Django 4.2.7 on 2026-03-27 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lipaidox", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoDMRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("new_follower", "New Follower"),
                            ("new_subscriber", "New Subscriber"),
                            ("new_ppv_purchase", "New PPV Purchase"),
                            ("new_tip", "New Tip"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("message_template", models.TextField()),
                ("include_creator_name", models.BooleanField(default=True)),
                ("include_fan_name", models.BooleanField(default=True)),
                ("delay_minutes", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_dm_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "auto_dm_rules",
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conversation_type",
                    models.CharField(
                        choices=[
                            ("fan_to_creator", "Fan to Creator"),
                            ("creator_to_fan", "Creator to Fan"),
                            ("platform_to_user", "Platform to User"),
                        ],
                        default="fan_to_creator",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("blocked", "Blocked"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("last_message_id", models.UUIDField(blank=True, null=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_message_preview",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fan_unread_count", models.IntegerField(default=0)),
                ("creator_unread_count", models.IntegerField(default=0)),
                ("blocked_at", models.DateTimeField(blank=True, null=True)),
                ("block_reason", models.TextField(blank=True, null=True)),
                ("archived_by_fan", models.BooleanField(default=False)),
                ("archived_by_creator", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blocked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blocked_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fan_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "conversations",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("file", "File"),
                            ("tip", "Tip"),
                            ("automated", "Automated"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("body", models.TextField(blank=True, null=True)),
                ("is_automated", models.BooleanField(default=False)),
                (
                    "tip_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("failed", "Failed"),
                            ("deleted", "Deleted"),
                        ],
                        default="sent",
                        max_length=15,
                    ),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted_by_sender", models.BooleanField(default=False)),
                ("is_deleted_by_receiver", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "auto_dm_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_messages",
                        to="lipaidox_messaging.autodmrule",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="lipaidox_messaging.conversation",
                    ),
                ),
                (
                    "reply_to_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="lipaidox_messaging.message",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "messages",
            },
        ),
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("document", "Document"),
                            ("archive", "Archive"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file_url", models.TextField()),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("thumbnail_url", models.TextField(blank=True, null=True)),
                ("is_expired", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="lipaidox_messaging.conversation",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="lipaidox_messaging.message",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "message_attachments",
                "indexes": [
                    models.Index(
                        fields=["message"], name="idx_msg_attachments_message"
                    ),
                    models.Index(
                        fields=["conversation"], name="idx_msg_attachments_conv"
                    ),
                    models.Index(
                        fields=["media_type"], name="idx_msg_attachments_media"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="messageattachment",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("file_size_bytes__isnull", True),
                    ("file_size_bytes__gt", 0),
                    _connector="OR",
                ),
                name="file_size_check",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation"], name="idx_messages_conversation_id"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["sender"], name="idx_messages_sender_id"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["status"], name="idx_messages_status"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["-sent_at"], name="idx_messages_sent_at"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["is_automated"], name="idx_messages_is_automated"
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("body__isnull", False),
                    models.Q(("message_type", "text"), _negated=True),
                    _connector="OR",
                ),
                name="body_or_attachment",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["fan"], name="idx_conversations_fan_id"),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["creator"], name="idx_conversations_creator_id"),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["status"], name="idx_conversations_status"),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["-last_message_at"], name="idx_conversations_last_msg_at"
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                fields=("fan", "creator"), name="conversations_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("fan_unread_count__gte", 0), ("creator_unread_count__gte", 0)
                ),
                name="unread_counts_check",
            ),
        ),
        migrations.AddIndex(
            model_name="autodmrule",
            index=models.Index(fields=["creator"], name="idx_auto_dm_rules_creator_id"),
        ),
        migrations.AddIndex(
            model_name="autodmrule",
            index=models.Index(fields=["trigger"], name="idx_auto_dm_rules_trigger"),
        ),
        migrations.AddIndex(
            model_name="autodmrule",
            index=models.Index(
                fields=["is_active"], name="idx_auto_dm_rules_is_active"
            ),
        ),
        migrations.AddConstraint(
            model_name="autodmrule",
            constraint=models.UniqueConstraint(
                fields=("creator", "trigger"), name="auto_dm_rules_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="autodmrule",
            constraint=models.CheckConstraint(
                check=models.Q(("delay_minutes__gte", 0)), name="delay_check"
            ),
        ),
    ]
