# Generated by Django 4.2.7 on 2026-09-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipaidox_messaging', '0004_message_sticker_starredmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('tip', 'Tip'), ('automated', 'Automated'), ('sticker', 'Sticker')], default='text', max_length=10),
        ),
    ]
