# Generated by Django 4.2.7 on 2026-09-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipaidox_messaging', '0005_alter_message_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='request_pending_for_creator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='request_pending_for_fan',
            field=models.BooleanField(default=False),
        ),
    ]
