# Generated by Django 4.2.7 on 2026-03-31 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lms_identity", "0005_learning_core_features"),
        ("lipaidox", "0001_initial"),
        ("lms_content", "0005_course_pool_additions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("max_students", models.PositiveIntegerField(default=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("upcoming", "Upcoming"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("requires_approval", models.BooleanField(default=False)),
                (
                    "default_meeting_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("meeting_schedule", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohorts",
                        to="lms_content.course",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructed_cohorts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "lms_cohorts",
            },
        ),
        migrations.CreateModel(
            name="CohortSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("scheduled_at", models.DateTimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                ("meet_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "recording_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("is_cancelled", models.BooleanField(default=False)),
                ("cancellation_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attended_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="attended_sessions",
                        to="lms_identity.studentprofile",
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="lms_cohorts.cohort",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conducted_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "lms_cohort_sessions",
                "ordering": ["scheduled_at"],
                "indexes": [
                    models.Index(fields=["cohort"], name="idx_session_cohort"),
                    models.Index(fields=["instructor"], name="idx_session_instructor"),
                    models.Index(fields=["scheduled_at"], name="idx_session_scheduled"),
                    models.Index(fields=["is_cancelled"], name="idx_session_cancelled"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CohortMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                            ("dropped", "Dropped"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "completion_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_cohort_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="lms_cohorts.cohort",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohort_memberships",
                        to="lms_identity.studentprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "lms_cohort_members",
                "indexes": [
                    models.Index(fields=["cohort"], name="idx_member_cohort"),
                    models.Index(fields=["student"], name="idx_member_student"),
                    models.Index(fields=["status"], name="idx_member_status"),
                    models.Index(fields=["-joined_at"], name="idx_member_joined"),
                ],
                "unique_together": {("cohort", "student")},
            },
        ),
        migrations.AddIndex(
            model_name="cohort",
            index=models.Index(fields=["course"], name="idx_cohort_course"),
        ),
        migrations.AddIndex(
            model_name="cohort",
            index=models.Index(fields=["instructor"], name="idx_cohort_instructor"),
        ),
        migrations.AddIndex(
            model_name="cohort",
            index=models.Index(fields=["status"], name="idx_cohort_status"),
        ),
        migrations.AddIndex(
            model_name="cohort",
            index=models.Index(fields=["start_date"], name="idx_cohort_start"),
        ),
        migrations.AddIndex(
            model_name="cohort",
            index=models.Index(fields=["-created_at"], name="idx_cohort_created"),
        ),
    ]
