# Generated by Django 4.2.7 on 2026-03-31 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lipaidox", "0001_initial"),
        ("lms_content", "0005_course_pool_additions"),
        ("lms_identity", "0005_learning_core_features"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="lms_content.course",
                    ),
                ),
                (
                    "ended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ended_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="lms_identity.studentprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lms_conversation_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "lms_conversations",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[("text", "Text"), ("file", "File")],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="lms_messages.conversation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lms_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lms_message_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "lms_messages",
                "ordering": ["sent_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_url", models.URLField(max_length=500)),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=100)),
                ("file_size", models.BigIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="lms_messages.message",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lms_messageattachment_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "lms_message_attachments",
                "indexes": [
                    models.Index(fields=["message"], name="idx_attachment_message"),
                    models.Index(
                        fields=["-uploaded_at"], name="idx_attachment_uploaded"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["conversation"], name="idx_msg_conversation"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["sender"], name="idx_msg_sender"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["-sent_at"], name="idx_msg_sent_at"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["read_at"], name="idx_msg_read_at"),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["course"], name="idx_conv_course"),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["student"], name="idx_conv_student"),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["instructor"], name="idx_conv_instructor"),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["-last_message_at"], name="idx_conv_last_msg"),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["is_active"], name="idx_conv_active"),
        ),
        migrations.AlterUniqueTogether(
            name="conversation",
            unique_together={("course", "student", "instructor")},
        ),
    ]
