# Generated by Django 4.2.7 on 2026-03-30 22:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lms_identity", "0002_instructorprofile"),
        ("lipaidox", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subcategories",
                        to="lms_skills.skillcategory",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "lms_skill_categories",
            },
        ),
        migrations.CreateModel(
            name="StudentSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("skill_name", models.CharField(max_length=255)),
                ("proficiency_level", models.IntegerField(default=1)),
                ("is_verified", models.BooleanField(default=False)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="lms_skills.skillcategory",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="lms_identity.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "lms_student_skills",
                "unique_together": {("student", "skill_name")},
            },
        ),
        migrations.CreateModel(
            name="SkillAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("max_score", models.IntegerField(default=100)),
                ("passed", models.BooleanField(default=False)),
                ("taken_at", models.DateTimeField(auto_now_add=True)),
                ("assessment_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lms_identity.studentprofile",
                    ),
                ),
                (
                    "student_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="lms_skills.studentskill",
                    ),
                ),
            ],
            options={
                "db_table": "lms_skill_assessments",
                "ordering": ["-taken_at"],
            },
        ),
    ]
