# Generated by Django 4.2.7 on 2026-03-31 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lipaidox", "0001_initial"),
        (
            "lms_identity",
            "0006_institutionuser_coursereview_courseassignmentteam_and_more",
        ),
        ("lms_careers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("technology", "Technology"),
                            ("healthcare", "Healthcare"),
                            ("finance", "Finance"),
                            ("education", "Education"),
                            ("retail", "Retail"),
                            ("manufacturing", "Manufacturing"),
                            ("consulting", "Consulting"),
                            ("media", "Media"),
                            ("nonprofit", "Non-Profit"),
                            ("government", "Government"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "company_size",
                    models.CharField(
                        choices=[
                            ("startup", "Startup (1-10)"),
                            ("small", "Small (11-50)"),
                            ("medium", "Medium (51-200)"),
                            ("large", "Large (201-1000)"),
                            ("enterprise", "Enterprise (1000+)"),
                        ],
                        default="small",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("mission", models.TextField(blank=True, null=True)),
                ("values", models.JSONField(blank=True, default=list)),
                ("logo_url", models.URLField(blank=True, max_length=500, null=True)),
                ("website", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "headquarters",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("locations", models.JSONField(blank=True, default=list)),
                (
                    "linkedin_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("twitter_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "hr_contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("recruitment_team_size", models.IntegerField(default=1)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("total_job_postings", models.IntegerField(default=0)),
                ("active_job_postings", models.IntegerField(default=0)),
                ("total_applications", models.IntegerField(default=0)),
                ("plan_type", models.CharField(default="free", max_length=50)),
                ("plan_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lms_employer_profiles",
            },
        ),
        migrations.CreateModel(
            name="EmployerDashboardStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_views", models.IntegerField(default=0)),
                ("total_applications", models.IntegerField(default=0)),
                ("pending_applications", models.IntegerField(default=0)),
                ("hired_count", models.IntegerField(default=0)),
                ("profile_views", models.IntegerField(default=0)),
                ("contacts_sent", models.IntegerField(default=0)),
                ("contacts_accepted", models.IntegerField(default=0)),
                ("avg_response_time_hours", models.FloatField(default=0)),
                ("conversion_rate", models.FloatField(default=0)),
                ("stats_period_start", models.DateTimeField()),
                ("stats_period_end", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_stats",
                        to="lms_employer.employerprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "lms_employer_dashboard_stats",
            },
        ),
        migrations.CreateModel(
            name="TalentPoolSearch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filters_json", models.JSONField(default=dict)),
                (
                    "search_query",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("results_count", models.IntegerField(default=0)),
                ("saved_profiles", models.JSONField(blank=True, default=list)),
                ("searched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talent_searches",
                        to="lms_employer.employerprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "lms_talent_pool_searches",
                "indexes": [
                    models.Index(fields=["employer"], name="idx_search_employer"),
                    models.Index(fields=["-searched_at"], name="idx_search_date"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployerStudentContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("responded", "Responded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("student_response", models.TextField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("source", models.CharField(default="talent_search", max_length=50)),
                ("priority", models.CharField(default="normal", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_contacts",
                        to="lms_employer.employerprofile",
                    ),
                ),
                (
                    "job_listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_contacts",
                        to="lms_careers.joblisting",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employer_contacts",
                        to="lms_identity.studentprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "lms_employer_student_contacts",
                "indexes": [
                    models.Index(fields=["employer"], name="idx_contact_employer"),
                    models.Index(fields=["student"], name="idx_contact_student"),
                    models.Index(fields=["status"], name="idx_contact_status"),
                    models.Index(fields=["-created_at"], name="idx_contact_created"),
                ],
                "unique_together": {("employer", "student")},
            },
        ),
        migrations.AddIndex(
            model_name="employerprofile",
            index=models.Index(fields=["company_name"], name="idx_emp_company_name"),
        ),
        migrations.AddIndex(
            model_name="employerprofile",
            index=models.Index(fields=["industry"], name="idx_emp_industry"),
        ),
        migrations.AddIndex(
            model_name="employerprofile",
            index=models.Index(fields=["company_size"], name="idx_emp_size"),
        ),
        migrations.AddIndex(
            model_name="employerprofile",
            index=models.Index(fields=["is_verified"], name="idx_emp_verified"),
        ),
        migrations.AddIndex(
            model_name="employerprofile",
            index=models.Index(fields=["-created_at"], name="idx_emp_created"),
        ),
        migrations.AddIndex(
            model_name="employerdashboardstats",
            index=models.Index(fields=["employer"], name="idx_stats_employer"),
        ),
        migrations.AddIndex(
            model_name="employerdashboardstats",
            index=models.Index(fields=["stats_period_start"], name="idx_stats_period"),
        ),
    ]
