# Generated by Django 4.2.7 on 2026-03-23 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lipaidox", "0001_initial"),
        ("lipaidox_creator_profile", "0002_remove_creatorprofile_display_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kyc_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("business", "Business"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("passport", "Passport"),
                            ("national_id", "National ID"),
                            ("driver_license", "Driver License"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "document_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("document_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "document_file_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                (
                    "document_file_size_bytes",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "document_mime_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("selfie_url", models.URLField(blank=True, max_length=1000, null=True)),
                (
                    "selfie_file_size_bytes",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("tin_number", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "tin_certificate_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                ("tin_file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                (
                    "tin_mime_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "business_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "business_registration_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "business_registration_doc_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                (
                    "business_registration_doc_size",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "business_registration_mime_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ai_face_match_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("ai_fraud_flag", models.BooleanField(default=False)),
                ("ai_fraud_reason", models.TextField(blank=True, null=True)),
                ("ai_document_valid", models.BooleanField(blank=True, null=True)),
                ("ai_document_reason", models.TextField(blank=True, null=True)),
                ("ai_processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ai_processing", "AI Processing"),
                            ("ai_passed", "AI Passed"),
                            ("ai_failed", "AI Failed"),
                            ("admin_review", "Admin Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("resubmission_requested", "Resubmission Requested"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_documents",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "verification_documents",
            },
        ),
        migrations.CreateModel(
            name="KYCStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kyc_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("business", "Business"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                (
                    "overall_status",
                    models.CharField(
                        choices=[
                            ("not_submitted", "Not Submitted"),
                            ("pending", "Pending"),
                            ("ai_processing", "AI Processing"),
                            ("admin_review", "Admin Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("resubmission_requested", "Resubmission Requested"),
                            ("permanently_rejected", "Permanently Rejected"),
                        ],
                        default="not_submitted",
                        max_length=50,
                    ),
                ),
                ("resubmission_count", models.IntegerField(default=0)),
                ("max_resubmissions", models.IntegerField(default=3)),
                ("last_resubmission_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("document_expired", "Document Expired"),
                            ("document_blurry", "Document Blurry"),
                            ("document_tampered", "Document Tampered"),
                            ("face_mismatch", "Face Mismatch"),
                            ("duplicate_identity", "Duplicate Identity"),
                            ("invalid_document_type", "Invalid Document Type"),
                            ("incomplete_submission", "Incomplete Submission"),
                            ("suspicious_activity", "Suspicious Activity"),
                            ("business_not_registered", "Business Not Registered"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("rejection_note", models.TextField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "permanently_rejected_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("permanent_rejection_note", models.TextField(blank=True, null=True)),
                ("first_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_status",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "current_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_for_status",
                        to="lipaidox_kyc.verificationdocument",
                    ),
                ),
                (
                    "permanently_rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permanent_rejections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kyc_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "kyc_status",
            },
        ),
        migrations.AddIndex(
            model_name="verificationdocument",
            index=models.Index(fields=["status"], name="verificatio_status_a43286_idx"),
        ),
        migrations.AddIndex(
            model_name="verificationdocument",
            index=models.Index(
                fields=["kyc_type"], name="verificatio_kyc_typ_d9d0a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="verificationdocument",
            index=models.Index(
                fields=["submitted_at"], name="verificatio_submitt_10c923_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kycstatus",
            index=models.Index(
                fields=["overall_status"], name="kyc_status_overall_b04fd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kycstatus",
            index=models.Index(
                fields=["reviewed_by"], name="kyc_status_reviewe_47b5d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kycstatus",
            index=models.Index(
                fields=["approved_at"], name="kyc_status_approve_92e6b4_idx"
            ),
        ),
    ]
