# Generated by Django 4.2.7 on 2026-03-23 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("lipaidox_creator_profile", "0002_remove_creatorprofile_display_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lipaidox", "0001_initial"),
        ("lipaidox_kyc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("business_name", models.CharField(max_length=255)),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("sole_proprietorship", "Sole Proprietorship"),
                            ("partnership", "Partnership"),
                            ("limited_liability_company", "Limited Liability Company"),
                            ("corporation", "Corporation"),
                            ("non_profit", "Non Profit"),
                            ("agency", "Agency"),
                            ("enterprise", "Enterprise"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("business_registration_number", models.CharField(max_length=100)),
                (
                    "registered_business_address",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "business_website",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "business_email",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                (
                    "business_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "country_of_incorporation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_of_incorporation", models.DateField(blank=True, null=True)),
                ("tin_number", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "tin_certificate_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                (
                    "tin_certificate_size_bytes",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "tin_certificate_mime_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("business_registration_doc_url", models.URLField(max_length=1000)),
                (
                    "business_registration_doc_size",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "business_registration_doc_mime_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "business_registration_expiry_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "business_license_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "business_license_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                (
                    "business_license_size_bytes",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "business_license_mime_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "business_license_expiry_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "incorporation_certificate_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                (
                    "incorporation_certificate_size_bytes",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "incorporation_certificate_mime_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("representative_first_name", models.CharField(max_length=100)),
                ("representative_last_name", models.CharField(max_length=100)),
                (
                    "representative_role",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "representative_id_document_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                (
                    "representative_id_document_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("passport", "Passport"),
                            ("national_id", "National ID"),
                            ("driver_license", "Driver License"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "representative_id_document_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "representative_id_expiry_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "representative_selfie_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                (
                    "ai_registry_check_passed",
                    models.BooleanField(blank=True, null=True),
                ),
                ("ai_registry_check_reason", models.TextField(blank=True, null=True)),
                ("ai_document_valid", models.BooleanField(blank=True, null=True)),
                ("ai_document_reason", models.TextField(blank=True, null=True)),
                ("ai_fraud_flag", models.BooleanField(default=False)),
                ("ai_fraud_reason", models.TextField(blank=True, null=True)),
                ("ai_processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("not_submitted", "Not Submitted"),
                            ("pending", "Pending"),
                            ("ai_processing", "AI Processing"),
                            ("admin_review", "Admin Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("resubmission_requested", "Resubmission Requested"),
                            ("permanently_rejected", "Permanently Rejected"),
                        ],
                        default="not_submitted",
                        max_length=50,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "invalid_registration_number",
                                "Invalid Registration Number",
                            ),
                            (
                                "business_not_found_in_registry",
                                "Business Not Found in Registry",
                            ),
                            ("expired_registration", "Expired Registration"),
                            ("name_mismatch", "Name Mismatch"),
                            ("invalid_license", "Invalid License"),
                            ("expired_license", "Expired License"),
                            ("invalid_tin", "Invalid TIN"),
                            ("incomplete_submission", "Incomplete Submission"),
                            ("document_tampered", "Document Tampered"),
                            ("suspicious_activity", "Suspicious Activity"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("rejection_note", models.TextField(blank=True, null=True)),
                ("resubmission_count", models.IntegerField(default=0)),
                ("max_resubmissions", models.IntegerField(default=3)),
                ("last_resubmission_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "permanently_rejected_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("permanent_rejection_note", models.TextField(blank=True, null=True)),
                ("first_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_verification",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "permanently_rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permanent_business_rejections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="business_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "business_verifications",
                "indexes": [
                    models.Index(
                        fields=["verification_status"],
                        name="business_ve_verific_91b64c_idx",
                    ),
                    models.Index(
                        fields=["business_name"], name="business_ve_busines_ac825c_idx"
                    ),
                    models.Index(
                        fields=["business_registration_number"],
                        name="business_ve_busines_95675b_idx",
                    ),
                ],
            },
        ),
    ]
