# Generated by Django 4.2.7 on 2026-04-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipaidox_kyc', '0003_verificationdocument_document_name_other_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessverification',
            name='representative_id_document_type',
            field=models.CharField(blank=True, choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('driver_license', 'Driver License'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
