# Generated by Django 4.2.7 on 2026-03-31 08:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("lms_identity", "0003_studentprofile_github_studentprofile_linkedin_and_more"),
        ("lms_performance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningStreak",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("current_streak", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                ("last_activity_date", models.DateField(blank=True, null=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_streak",
                        to="lms_identity.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "lms_learning_streaks",
            },
        ),
    ]
