# Generated by Django 4.2.7 on 2026-03-30 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lms_content", "0001_initial"),
        ("lipaidox", "0001_initial"),
        ("lms_identity", "0002_instructorprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="lms_identity.instructorprofile",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_instances",
                to="lipaidox.tenant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together={("course", "slug")},
        ),
    ]
