# Generated by Django 4.2.7 on 2026-03-30 21:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("lms_content", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF Document"),
                            ("link", "External Link"),
                            ("code", "Source Code"),
                            ("zip", "Archive"),
                        ],
                        default="pdf",
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("file_size_kb", models.IntegerField(default=0)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="lms_content.lesson",
                    ),
                ),
            ],
            options={
                "db_table": "lms_resources",
            },
        ),
        migrations.CreateModel(
            name="Lab",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "lab_type",
                    models.CharField(
                        choices=[
                            ("code", "Interactive Code"),
                            ("sandbox", "Sandbox Environment"),
                            ("quiz", "Advanced Quiz"),
                        ],
                        default="code",
                        max_length=20,
                    ),
                ),
                ("instructions", models.TextField()),
                ("starter_code", models.TextField(blank=True, null=True)),
                ("solution_code", models.TextField(blank=True, null=True)),
                ("language", models.CharField(default="python", max_length=50)),
                ("time_limit_mins", models.IntegerField(default=30)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labs",
                        to="lms_content.lesson",
                    ),
                ),
            ],
            options={
                "db_table": "lms_labs",
            },
        ),
    ]
