# Generated by Django 4.2.7 on 2026-03-31 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("lms_identity", "0005_learning_core_features"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lipaidox", "0001_initial"),
        ("lms_content", "0005_course_pool_additions"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.TextField()),
                ("language", models.CharField(default="python", max_length=50)),
                ("output", models.TextField(blank=True, null=True)),
                ("error_output", models.TextField(blank=True, null=True)),
                ("is_passing", models.BooleanField(default=False)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("grading", "Grading"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("resubmitted", "Resubmitted"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("instructor_feedback", models.TextField(blank=True, null=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("execution_time_ms", models.IntegerField(blank=True, null=True)),
                ("memory_usage_mb", models.FloatField(blank=True, null=True)),
                ("test_results", models.JSONField(blank=True, default=dict)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_lab_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="lms_content.lab",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_submissions",
                        to="lms_identity.studentprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "lms_lab_submissions",
                "indexes": [
                    models.Index(fields=["lab"], name="idx_lab_submission_lab"),
                    models.Index(fields=["student"], name="idx_lab_submission_student"),
                    models.Index(fields=["status"], name="idx_lab_submission_status"),
                    models.Index(
                        fields=["-submitted_at"], name="idx_lab_submission_submitted"
                    ),
                ],
                "unique_together": {("lab", "student")},
            },
        ),
    ]
