# Generated by Django 4.2.7 on 2026-03-23 12:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lipaidox_creator_profile", "0002_remove_creatorprofile_display_name"),
        ("lipaidox", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Bank Transfer"),
                            ("mobile_money", "Mobile Money"),
                            ("card", "Card"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                            ("disabled", "Disabled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "bank_account_holder_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "bank_account_number_encrypted",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "bank_account_number_last4",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "bank_swift_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("bank_iban", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "bank_routing_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "bank_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "bank_branch_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "bank_branch_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "mobile_money_provider",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mobile_money_phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "mobile_money_phone_country_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "mobile_money_account_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "card_holder_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("card_last4", models.CharField(blank=True, max_length=4, null=True)),
                ("card_brand", models.CharField(blank=True, max_length=50, null=True)),
                ("card_expiry_month", models.SmallIntegerField(blank=True, null=True)),
                ("card_expiry_year", models.SmallIntegerField(blank=True, null=True)),
                (
                    "card_billing_address_line1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "card_billing_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "card_billing_postal_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "card_billing_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("card_gateway_token", models.TextField(blank=True, null=True)),
                ("card_fingerprint", models.TextField(blank=True, null=True)),
                (
                    "payout_currency",
                    models.CharField(
                        choices=[
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                            ("TZS", "TZS"),
                            ("KES", "KES"),
                            ("NGN", "NGN"),
                            ("GHS", "GHS"),
                            ("ZAR", "ZAR"),
                            ("UGX", "UGX"),
                        ],
                        default="USD",
                        max_length=10,
                    ),
                ),
                (
                    "payout_frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("bi_weekly", "Bi-Weekly"),
                            ("monthly", "Monthly"),
                            ("manual", "Manual"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "minimum_payout_threshold",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
                ),
                (
                    "tax_withholding_rate",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("ten_percent", "10%"),
                            ("fifteen_percent", "15%"),
                            ("twenty_percent", "20%"),
                            ("thirty_percent", "30%"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "payment_methods",
            },
        ),
        migrations.CreateModel(
            name="MobileMoneyProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider_name", models.CharField(max_length=100)),
                ("country_name", models.CharField(max_length=100)),
                ("country_code", models.CharField(max_length=10)),
                ("dial_code", models.CharField(max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "mobile_money_providers",
                "unique_together": {("provider_name", "country_code")},
            },
        ),
        migrations.AddConstraint(
            model_name="paymentmethod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("creator",),
                name="idx_payment_methods_one_primary",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentmethod",
            constraint=models.CheckConstraint(
                check=models.Q(("minimum_payout_threshold__gte", 10.0)),
                name="minimum_threshold_check",
            ),
        ),
    ]
