# Generated by Django 4.2.7 on 2026-07-14 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lipaidox', '0001_initial'),
        ('lipaidox_payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(default='simulated', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('purpose', models.CharField(choices=[('wallet_topup', 'Wallet Top-up'), ('ppv', 'PPV Purchase'), ('credits', 'Credit Purchase'), ('live_entry', 'Live Entry'), ('subscription', 'Subscription')], default='wallet_topup', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('provider_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_instances', to='lipaidox.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'charges',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='idx_charge_user'), models.Index(fields=['status'], name='idx_charge_status'), models.Index(fields=['purpose'], name='idx_charge_purpose')],
            },
        ),
    ]
