# Generated by Django 4.2.7 on 2026-09-29 05:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lipaidox', '0001_initial'),
        ('lipaidox_creator_profile', '0015_creatorprofile_show_gender_on_profile_and_more'),
        ('lipaidox_payment', '0002_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=2)),
                ('country_name', models.CharField(max_length=100)),
                ('tax_authority', models.CharField(max_length=255)),
                ('taxpayer_name', models.CharField(max_length=255)),
                ('tin_number', models.CharField(max_length=100)),
                ('tin_certificate_url', models.URLField(max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_profile', to='lipaidox_creator_profile.creatorprofile')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_instances', to='lipaidox.tenant')),
            ],
            options={
                'db_table': 'tax_profiles',
                'indexes': [models.Index(fields=['status'], name='tax_profile_status_ce415c_idx')],
            },
        ),
    ]
