# Generated by Django 4.2.7 on 2026-03-27 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lipaidox", "0001_initial"),
        ("lipaidox_creator_profile", "0004_usernamehistory_and_more"),
        ("lipaidox_admin_panel", "0001_initial"),
        ("lipaidox_payment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreatorWallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "pending_balance",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "available_balance",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "on_hold_balance",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "lifetime_earnings",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "lifetime_payouts",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "lifetime_refunds",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "lifetime_platform_fees",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "earnings_from_ppv",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "earnings_from_subscriptions",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "earnings_from_tips",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "earnings_from_credits",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "earnings_from_live_streams",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("last_payout_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_payout_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallets",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "creator_wallets",
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("ppv_earning", "PPV Earning"),
                            ("subscription_earning", "Subscription Earning"),
                            ("tip_earning", "Tip Earning"),
                            ("credit_gift_earning", "Credit Gift Earning"),
                            ("live_stream_earning", "Live Stream Earning"),
                            ("payout", "Payout"),
                            ("payout_reversal", "Payout Reversal"),
                            ("refund_deduction", "Refund Deduction"),
                            ("platform_fee", "Platform Fee"),
                            ("tax_withholding", "Tax Withholding"),
                            ("adjustment", "Adjustment"),
                            ("bonus", "Bonus"),
                        ],
                        default="ppv_earning",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("cleared", "Cleared"),
                            ("paid_out", "Paid Out"),
                            ("reversed", "Reversed"),
                            ("held", "Held"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=14)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "balance_before",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                ("balance_after", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "balance_type",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("available", "Available"),
                            ("on_hold", "On Hold"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ppv_purchase_id", models.UUIDField(blank=True, null=True)),
                ("subscription_payment_id", models.UUIDField(blank=True, null=True)),
                ("tip_id", models.UUIDField(blank=True, null=True)),
                ("live_stream_id", models.UUIDField(blank=True, null=True)),
                ("credit_transaction_id", models.UUIDField(blank=True, null=True)),
                ("payout_id", models.UUIDField(blank=True, null=True)),
                ("clears_at", models.DateTimeField(blank=True, null=True)),
                ("cleared_at", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_transactions",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="lipaidox_wallet.creatorwallet",
                    ),
                ),
            ],
            options={
                "db_table": "wallet_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WalletClearingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=14)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("scheduled_clear_at", models.DateTimeField()),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_clearing_jobs",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clearing_jobs",
                        to="lipaidox_wallet.creatorwallet",
                    ),
                ),
                (
                    "wallet_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clearing_jobs",
                        to="lipaidox_wallet.wallettransaction",
                    ),
                ),
            ],
            options={
                "db_table": "wallet_clearing_jobs",
                "ordering": ["scheduled_clear_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("ppv_purchase", "PPV Purchase"),
                            ("subscription", "Subscription"),
                            ("tip", "Tip"),
                            ("credit_purchase", "Credit Purchase"),
                            ("live_entry", "Live Entry"),
                            ("payout", "Payout"),
                            ("refund", "Refund"),
                            ("tax_withholding", "Tax Withholding"),
                            ("platform_fee", "Platform Fee"),
                            ("adjustment", "Adjustment"),
                        ],
                        default="ppv_purchase",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                            ("disputed", "Disputed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "platform_fee_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "platform_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("ppv_purchase_id", models.UUIDField(blank=True, null=True)),
                ("subscription_payment_id", models.UUIDField(blank=True, null=True)),
                ("tip_id", models.UUIDField(blank=True, null=True)),
                ("credit_purchase_id", models.UUIDField(blank=True, null=True)),
                ("payout_id", models.UUIDField(blank=True, null=True)),
                (
                    "gateway_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("gateway_response", models.JSONField(blank=True, default=dict)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("refund_reason", models.TextField(blank=True, null=True)),
                ("disputed_at", models.DateTimeField(blank=True, null=True)),
                ("dispute_reason", models.TextField(blank=True, null=True)),
                ("dispute_resolved_at", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_transactions",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "fan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="lipaidox_payment.paymentmethod",
                    ),
                ),
                (
                    "refunded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunded_transactions",
                        to="lipaidox_admin_panel.adminaccount",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PayoutTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "tax_withholding_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_withheld_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "net_payout_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("reversed", "Reversed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "gateway_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("gateway_response", models.JSONField(blank=True, default=dict)),
                (
                    "gateway_fee",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("invalid_account", "Invalid Account"),
                            ("insufficient_funds", "Insufficient Funds"),
                            ("bank_rejected", "Bank Rejected"),
                            ("gateway_error", "Gateway Error"),
                            ("compliance_hold", "Compliance Hold"),
                            ("account_suspended", "Account Suspended"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("failure_note", models.TextField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("last_retry_at", models.DateTimeField(blank=True, null=True)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("reversal_reason", models.TextField(blank=True, null=True)),
                ("requires_admin_approval", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("processing_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payouts",
                        to="lipaidox_admin_panel.adminaccount",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_transactions",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payout_transactions",
                        to="lipaidox_payment.paymentmethod",
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversed_payouts",
                        to="lipaidox_admin_panel.adminaccount",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_transactions",
                        to="lipaidox_wallet.creatorwallet",
                    ),
                ),
            ],
            options={
                "db_table": "payout_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(fields=["wallet"], name="idx_wallet_txn_wallet"),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(fields=["creator"], name="idx_wallet_txn_creator"),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(fields=["transaction_type"], name="idx_wallet_txn_type"),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(fields=["status"], name="idx_wallet_txn_status"),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(fields=["clears_at"], name="idx_wallet_txn_clears_at"),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(fields=["created_at"], name="idx_wallet_txn_created"),
        ),
        migrations.AddConstraint(
            model_name="wallettransaction",
            constraint=models.CheckConstraint(
                check=models.Q(("amount", 0), _negated=True),
                name="wallet_txn_amount_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="wallettransaction",
            constraint=models.CheckConstraint(
                check=models.Q(("balance_after__gte", 0)),
                name="wallet_txn_balance_after_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="wallettransaction",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "balance_after",
                        django.db.models.expressions.CombinedExpression(
                            models.F("balance_before"), "+", models.F("amount")
                        ),
                    )
                ),
                name="wallet_txn_balance_consistency",
            ),
        ),
        migrations.AddIndex(
            model_name="walletclearingjob",
            index=models.Index(fields=["wallet"], name="idx_clearing_wallet"),
        ),
        migrations.AddIndex(
            model_name="walletclearingjob",
            index=models.Index(fields=["creator"], name="idx_clearing_creator"),
        ),
        migrations.AddIndex(
            model_name="walletclearingjob",
            index=models.Index(fields=["status"], name="idx_clearing_status"),
        ),
        migrations.AddIndex(
            model_name="walletclearingjob",
            index=models.Index(
                fields=["scheduled_clear_at"], name="idx_clearing_scheduled"
            ),
        ),
        migrations.AddConstraint(
            model_name="walletclearingjob",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gt", 0)), name="clearing_amount_check"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["fan"], name="idx_txn_fan"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["creator"], name="idx_txn_creator"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["transaction_type"], name="idx_txn_type"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["status"], name="idx_txn_status"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["gateway_reference"], name="idx_txn_gateway_ref"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["created_at"], name="idx_txn_created"),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                check=models.Q(("gross_amount__gt", 0)), name="txn_gross_amount_check"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                check=models.Q(("platform_fee__gte", 0)), name="txn_platform_fee_check"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                check=models.Q(("net_amount__gte", 0)), name="txn_net_amount_check"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "net_amount",
                        django.db.models.expressions.CombinedExpression(
                            models.F("gross_amount"), "-", models.F("platform_fee")
                        ),
                    )
                ),
                name="txn_net_calculation",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("refund_amount__isnull", True),
                    models.Q(
                        ("refund_amount__gt", 0),
                        ("refund_amount__lte", models.F("gross_amount")),
                    ),
                    _connector="OR",
                ),
                name="txn_refund_amount_check",
            ),
        ),
        migrations.AddIndex(
            model_name="payouttransaction",
            index=models.Index(fields=["creator"], name="idx_payout_creator"),
        ),
        migrations.AddIndex(
            model_name="payouttransaction",
            index=models.Index(fields=["wallet"], name="idx_payout_wallet"),
        ),
        migrations.AddIndex(
            model_name="payouttransaction",
            index=models.Index(fields=["status"], name="idx_payout_status"),
        ),
        migrations.AddIndex(
            model_name="payouttransaction",
            index=models.Index(fields=["initiated_at"], name="idx_payout_initiated"),
        ),
        migrations.AddIndex(
            model_name="payouttransaction",
            index=models.Index(fields=["completed_at"], name="idx_payout_completed"),
        ),
        migrations.AddIndex(
            model_name="payouttransaction",
            index=models.Index(
                fields=["payment_method"], name="idx_payout_payment_method"
            ),
        ),
        migrations.AddConstraint(
            model_name="payouttransaction",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gt", 0)), name="payout_amount_check"
            ),
        ),
        migrations.AddConstraint(
            model_name="payouttransaction",
            constraint=models.CheckConstraint(
                check=models.Q(("net_payout_amount__gt", 0)),
                name="payout_net_amount_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="payouttransaction",
            constraint=models.CheckConstraint(
                check=models.Q(("tax_withheld_amount__gte", 0)), name="payout_tax_check"
            ),
        ),
        migrations.AddConstraint(
            model_name="payouttransaction",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "net_payout_amount",
                        django.db.models.expressions.CombinedExpression(
                            models.F("amount"), "-", models.F("tax_withheld_amount")
                        ),
                    )
                ),
                name="payout_net_calculation",
            ),
        ),
        migrations.AddConstraint(
            model_name="payouttransaction",
            constraint=models.CheckConstraint(
                check=models.Q(("retry_count__gte", 0)), name="payout_retry_check"
            ),
        ),
        migrations.AddConstraint(
            model_name="payouttransaction",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("tax_withholding_percent__gte", 0),
                    ("tax_withholding_percent__lte", 100),
                ),
                name="payout_tax_percent_check",
            ),
        ),
        migrations.AddIndex(
            model_name="creatorwallet",
            index=models.Index(fields=["creator"], name="idx_wallet_creator"),
        ),
        migrations.AddIndex(
            model_name="creatorwallet",
            index=models.Index(fields=["currency"], name="idx_wallet_currency"),
        ),
        migrations.AddConstraint(
            model_name="creatorwallet",
            constraint=models.UniqueConstraint(
                fields=("creator", "currency"), name="creator_wallets_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="creatorwallet",
            constraint=models.CheckConstraint(
                check=models.Q(("pending_balance__gte", 0)),
                name="wallet_pending_balance_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="creatorwallet",
            constraint=models.CheckConstraint(
                check=models.Q(("available_balance__gte", 0)),
                name="wallet_available_balance_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="creatorwallet",
            constraint=models.CheckConstraint(
                check=models.Q(("on_hold_balance__gte", 0)),
                name="wallet_on_hold_balance_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="creatorwallet",
            constraint=models.CheckConstraint(
                check=models.Q(("lifetime_earnings__gte", 0)),
                name="wallet_lifetime_earnings_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="creatorwallet",
            constraint=models.CheckConstraint(
                check=models.Q(("lifetime_payouts__gte", 0)),
                name="wallet_lifetime_payouts_check",
            ),
        ),
    ]
