# Generated by Django 4.2.7 on 2026-07-14 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lipaidox', '0001_initial'),
        ('lipaidox_wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('balance', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('lifetime_topup', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('lifetime_spent', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_instances', to='lipaidox.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan_wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fan_wallets',
                'indexes': [models.Index(fields=['user'], name='idx_fan_wallet_user')],
            },
        ),
        migrations.AddConstraint(
            model_name='fanwallet',
            constraint=models.UniqueConstraint(fields=('user', 'currency'), name='fan_wallets_unique'),
        ),
        migrations.AddConstraint(
            model_name='fanwallet',
            constraint=models.CheckConstraint(check=models.Q(('balance__gte', 0)), name='fan_wallet_balance_check'),
        ),
    ]
