# Generated by Django 4.2.7 on 2026-03-31 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lipaidox", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LmsNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("course_enrolled", "Course Enrolled"),
                            ("course_completed", "Course Completed"),
                            ("lesson_completed", "Lesson Completed"),
                            ("assignment_due", "Assignment Due"),
                            ("assignment_submitted", "Assignment Submitted"),
                            ("assignment_graded", "Assignment Graded"),
                            ("quiz_completed", "Quiz Completed"),
                            ("quiz_passed", "Quiz Passed"),
                            ("quiz_failed", "Quiz Failed"),
                            ("study_room_invited", "Study Room Invited"),
                            ("study_room_message", "Study Room Message"),
                            ("accountability_check_in", "Accountability Check-In"),
                            ("certification_earned", "Certification Earned"),
                            ("skill_badge_earned", "Skill Badge Earned"),
                            ("streak_achieved", "Streak Achieved"),
                            ("weekly_progress", "Weekly Progress"),
                            ("job_application_viewed", "Job Application Viewed"),
                            (
                                "job_application_shortlisted",
                                "Job Application Shortlisted",
                            ),
                            ("system_announcement", "System Announcement"),
                            ("payment_confirmed", "Payment Confirmed"),
                            ("subscription_renewal", "Subscription Renewal"),
                        ],
                        default="system_announcement",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("action_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "action_text",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lms_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lms_notifications",
                "indexes": [
                    models.Index(fields=["user"], name="idx_notif_user"),
                    models.Index(fields=["-created_at"], name="idx_notif_created"),
                    models.Index(fields=["is_read"], name="idx_notif_read"),
                    models.Index(fields=["notification_type"], name="idx_notif_type"),
                ],
            },
        ),
    ]
