# Generated by Django 4.2.7 on 2026-03-23 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lipaidox.auth.models.password_reset_token
import lipaidox.auth.models.refresh_token
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("lipaidox", "0001_initial"),
        ("lipaidox_auth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="tenant_id",
        ),
        migrations.AddField(
            model_name="emailverification",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_verifications",
                to="lipaidox.tenant",
            ),
        ),
        migrations.AddField(
            model_name="phoneverification",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phone_verifications",
                to="lipaidox.tenant",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="lipaidox.tenant",
            ),
        ),
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_hash", models.TextField(unique=True)),
                ("status", models.CharField(default="active", max_length=20)),
                (
                    "device_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=lipaidox.auth.models.refresh_token.get_refresh_expiry
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "refresh_tokens",
            },
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_hash", models.TextField(unique=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=lipaidox.auth.models.password_reset_token.get_reset_expiry
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_resets",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "password_reset_tokens",
            },
        ),
    ]
