# Generated by Django 4.2.7 on 2026-03-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "lipaidox_auth",
            "0002_remove_user_tenant_id_emailverification_tenant_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="phoneverification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="phoneverification",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="phoneverification",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp from WhatsApp webhook confirming delivery",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="phoneverification",
            name="delivery_channel",
            field=models.CharField(
                choices=[("whatsapp", "WhatsApp"), ("sms", "SMS")],
                default="whatsapp",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="phoneverification",
            name="fallback_to_sms",
            field=models.BooleanField(
                default=False,
                help_text="True if WhatsApp failed and OTP was resent via SMS",
            ),
        ),
        migrations.AddField(
            model_name="phoneverification",
            name="fallback_triggered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="phoneverification",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="phoneverification",
            name="max_attempts",
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="phoneverification",
            name="sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when WhatsApp message was dispatched",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="phoneverification",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="phoneverification",
            name="whatsapp_error_code",
            field=models.CharField(
                blank=True,
                help_text="Error code from WhatsApp API if sending failed",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="phoneverification",
            name="whatsapp_error_message",
            field=models.TextField(
                blank=True,
                help_text="Error detail from WhatsApp API if sending failed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="phoneverification",
            name="whatsapp_message_id",
            field=models.CharField(
                blank=True,
                help_text="Message ID returned by WhatsApp API after sending",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="phoneverification",
            name="whatsapp_status",
            field=models.CharField(
                blank=True,
                help_text="Delivery status from WhatsApp webhook: sent, delivered, read, failed",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="phoneverification",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("expired", "Expired"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="phoneverification",
            index=models.Index(
                fields=["phone_number", "status"], name="phone_verif_phone_n_ed9303_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phoneverification",
            index=models.Index(
                fields=["user", "status"], name="phone_verif_user_id_064c47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phoneverification",
            index=models.Index(
                fields=["whatsapp_message_id"], name="phone_verif_whatsap_e8e9ef_idx"
            ),
        ),
    ]
