# Generated by Django 4.2.7 on 2026-03-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lipaidox_auth", "0003_alter_phoneverification_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phoneverification",
            name="fallback_to_sms",
        ),
        migrations.AddField(
            model_name="phoneverification",
            name="fallback_to_email",
            field=models.BooleanField(
                default=False,
                help_text="True if WhatsApp failed and OTP was sent via Email",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="apple_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(default="local", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="google_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="phoneverification",
            name="delivery_channel",
            field=models.CharField(
                choices=[("whatsapp", "WhatsApp"), ("email", "Email")],
                default="whatsapp",
                max_length=20,
            ),
        ),
    ]
