# Generated by Django 4.2.7 on 2026-04-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lipaidox_auth", "0004_remove_phoneverification_fallback_to_sms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="apple_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="google_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("phone_number__isnull", False)),
                fields=("phone_number", "tenant"),
                name="unique_phone_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("google_id__isnull", False)),
                fields=("google_id", "tenant"),
                name="unique_google_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("apple_id__isnull", False)),
                fields=("apple_id", "tenant"),
                name="unique_apple_per_tenant",
            ),
        ),
    ]
