# Generated by Django 4.2.7 on 2026-04-24 21:18

from django.db import migrations, models
import lipaidox.auth.models.password_reset_otp


class Migration(migrations.Migration):

    dependencies = [
        ('lipaidox_auth', '0006_password_reset_otp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresetotp',
            new_name='password_re_user_id_50c583_idx',
            old_name='pwreset_otp_user_status_idx',
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='expires_at',
            field=models.DateTimeField(default=lipaidox.auth.models.password_reset_otp._otp_default_expiry),
        ),
    ]
