# Generated by Django 4.2.7 on 2026-06-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "lipaidox_auth",
            "0007_rename_pwreset_otp_user_status_idx_password_re_user_id_50c583_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_first_login",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="module",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="staff_capabilities",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
