# Generated by Django 4.2.7 on 2026-10-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipaidox_auth', '0009_twofactorloginchallenge_twofactorauth_backupcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('firebase_uid__isnull', False)), fields=('firebase_uid', 'tenant'), name='unique_firebase_uid_per_tenant'),
        ),
    ]
