# Generated by Django 4.2.7 on 2026-10-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipaidox_auth', '0010_user_firebase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requires_follow_approval',
            field=models.BooleanField(default=False),
        ),
    ]
