# Generated by Django 4.2.7 on 2026-03-23 12:43

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lipaidox_creator_profile", "0002_remove_creatorprofile_display_name"),
        ("lipaidox", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonetizationSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subscription_enabled", models.BooleanField(default=False)),
                (
                    "subscription_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "subscription_billing_cycle",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("subscription_trial_days", models.IntegerField(default=0)),
                ("subscription_description", models.TextField(blank=True, null=True)),
                ("ppv_enabled", models.BooleanField(default=False)),
                (
                    "ppv_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "ppv_price_min",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
                ),
                (
                    "ppv_price_max",
                    models.DecimalField(
                        decimal_places=2, default=999.99, max_digits=10
                    ),
                ),
                ("live_stream_enabled", models.BooleanField(default=False)),
                (
                    "live_stream_credit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "live_stream_credit_description",
                    models.TextField(blank=True, null=True),
                ),
                ("custom_content_enabled", models.BooleanField(default=False)),
                (
                    "custom_content_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("custom_content_delivery_days", models.IntegerField(default=7)),
                ("custom_content_description", models.TextField(blank=True, null=True)),
                ("tips_enabled", models.BooleanField(default=False)),
                (
                    "tip_min_amount",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
                ),
                (
                    "tip_max_amount",
                    models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
                ),
                (
                    "tip_suggested_amounts",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.DecimalField(decimal_places=2, max_digits=10),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("promotions_enabled", models.BooleanField(default=False)),
                ("discount_config", models.JSONField(blank=True, null=True)),
                (
                    "display_currency",
                    models.CharField(
                        choices=[
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                            ("TZS", "TZS"),
                            ("KES", "KES"),
                            ("NGN", "NGN"),
                            ("GHS", "GHS"),
                            ("ZAR", "ZAR"),
                            ("UGX", "UGX"),
                        ],
                        default="USD",
                        max_length=10,
                    ),
                ),
                (
                    "platform_fee_percent",
                    models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monetization_settings",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "monetization_settings",
            },
        ),
        migrations.CreateModel(
            name="MonetizationPriceHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "price_field",
                    models.CharField(
                        choices=[
                            ("subscription_price", "Subscription Price"),
                            ("ppv_price", "PPV Price"),
                            ("live_stream_credit_price", "Live Stream Credit Price"),
                            ("custom_content_price", "Custom Content Price"),
                            ("tip_min_amount", "Tip Min Amount"),
                            ("tip_max_amount", "Tip Max Amount"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "new_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("effective_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "monetization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="lipaidox_monetization.monetizationsettings",
                    ),
                ),
            ],
            options={
                "db_table": "monetization_price_history",
                "ordering": ["-effective_at"],
            },
        ),
        migrations.AddIndex(
            model_name="monetizationsettings",
            index=models.Index(
                fields=["subscription_enabled"], name="monetizatio_subscri_2fd1c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monetizationsettings",
            index=models.Index(
                fields=["tips_enabled"], name="monetizatio_tips_en_b749d7_idx"
            ),
        ),
    ]
