# Generated by Django 4.2.7 on 2026-09-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipaidox_monetization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monetizationsettings',
            name='subscription_benefits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='monetizationsettings',
            name='subscription_description',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
