# Generated by Django 4.2.7 on 2026-03-31 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lipaidox", "0001_initial"),
        ("lms_financial", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentPaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("card", "Credit/Debit Card"),
                            ("bank_account", "Bank Account"),
                            ("mobile_money", "Mobile Money"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("expired", "Expired"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "stripe_payment_method_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("card_brand", models.CharField(blank=True, max_length=50, null=True)),
                ("card_last4", models.CharField(blank=True, max_length=4, null=True)),
                ("card_exp_month", models.IntegerField(blank=True, null=True)),
                ("card_exp_year", models.IntegerField(blank=True, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "bank_account_last4",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "mobile_money_provider",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mobile_money_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_payment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lms_student_payment_methods",
                "indexes": [
                    models.Index(fields=["user"], name="idx_student_pm_user"),
                    models.Index(fields=["status"], name="idx_student_pm_status"),
                    models.Index(fields=["is_default"], name="idx_student_pm_default"),
                ],
            },
        ),
    ]
