# Generated by Django 4.2.7 on 2026-03-27 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lipaidox", "0001_initial"),
        ("lipaidox_creator_profile", "0004_usernamehistory_and_more"),
        ("lipaidox_credits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveStream",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("thumbnail_url", models.TextField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("tags", models.TextField(blank=True, null=True)),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("subscription", "Subscription"),
                            ("paid_entry", "Paid Entry"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "entry_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("live", "Live"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("credits_used", models.IntegerField(default=0)),
                ("credit_deduction_interval", models.IntegerField(default=15)),
                ("stream_key", models.CharField(blank=True, max_length=255, null=True)),
                ("stream_url", models.TextField(blank=True, null=True)),
                ("playback_url", models.TextField(blank=True, null=True)),
                ("recording_url", models.TextField(blank=True, null=True)),
                ("is_recorded", models.BooleanField(default=False)),
                ("peak_viewer_count", models.IntegerField(default=0)),
                ("total_viewer_count", models.IntegerField(default=0)),
                ("current_viewer_count", models.IntegerField(default=0)),
                (
                    "total_tips_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("total_credits_received", models.IntegerField(default=0)),
                (
                    "total_credits_value",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("chat_enabled", models.BooleanField(default=True)),
                ("chat_followers_only", models.BooleanField(default=False)),
                ("chat_subscribers_only", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_streams",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "live_streams",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LiveStreamCreditTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("credits_received", models.IntegerField()),
                (
                    "monetary_value",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                ("platform_fee", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "creator_earnings",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "animation_type",
                    models.CharField(
                        choices=[
                            ("heart", "Heart"),
                            ("rose", "Rose"),
                            ("diamond", "Diamond"),
                        ],
                        default="heart",
                        max_length=50,
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_stream_credit_transactions",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "fan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_stream_credit_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_stream_transactions",
                        to="lipaidox_credits.fancreditgiftsent",
                    ),
                ),
                (
                    "live_stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_transactions",
                        to="lipaidox_live_streaming.livestream",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "live_stream_credit_transactions",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="LiveStreamChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("visible", "Visible"),
                            ("deleted", "Deleted"),
                            ("flagged", "Flagged"),
                            ("auto_moderated", "Auto Moderated"),
                        ],
                        default="visible",
                        max_length=20,
                    ),
                ),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_creator_message", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_stream_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "live_stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="lipaidox_live_streaming.livestream",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "live_stream_chat_messages",
                "ordering": ["sent_at"],
            },
        ),
        migrations.CreateModel(
            name="LiveStreamViewer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("watching", "Watching"),
                            ("left", "Left"),
                            ("kicked", "Kicked"),
                            ("banned", "Banned"),
                        ],
                        default="watching",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("watch_duration_s", models.IntegerField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("device_type", models.CharField(blank=True, max_length=50, null=True)),
                ("is_subscriber", models.BooleanField(default=False)),
                ("credits_sent", models.IntegerField(default=0)),
                (
                    "tips_sent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_stream_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "live_stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viewers",
                        to="lipaidox_live_streaming.livestream",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "live_stream_viewers",
                "ordering": ["-joined_at"],
                "indexes": [
                    models.Index(fields=["live_stream"], name="idx_viewer_stream"),
                    models.Index(fields=["fan"], name="idx_viewer_fan"),
                    models.Index(fields=["status"], name="idx_viewer_status"),
                    models.Index(fields=["joined_at"], name="idx_viewer_joined"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="livestreamviewer",
            constraint=models.UniqueConstraint(
                fields=("live_stream", "fan"), name="livestream_viewers_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="livestreamviewer",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("watch_duration_s__isnull", True),
                    ("watch_duration_s__gte", 0),
                    _connector="OR",
                ),
                name="viewer_watch_duration_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="livestreamviewer",
            constraint=models.CheckConstraint(
                check=models.Q(("credits_sent__gte", 0)),
                name="viewer_credits_sent_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="livestreamviewer",
            constraint=models.CheckConstraint(
                check=models.Q(("tips_sent__gte", 0)), name="viewer_tips_sent_check"
            ),
        ),
        migrations.AddIndex(
            model_name="livestreamcredittransaction",
            index=models.Index(fields=["live_stream"], name="idx_stream_credit_stream"),
        ),
        migrations.AddIndex(
            model_name="livestreamcredittransaction",
            index=models.Index(fields=["fan"], name="idx_stream_credit_fan"),
        ),
        migrations.AddIndex(
            model_name="livestreamcredittransaction",
            index=models.Index(fields=["creator"], name="idx_stream_credit_creator"),
        ),
        migrations.AddIndex(
            model_name="livestreamcredittransaction",
            index=models.Index(
                fields=["received_at"], name="idx_stream_credit_received"
            ),
        ),
        migrations.AddConstraint(
            model_name="livestreamcredittransaction",
            constraint=models.CheckConstraint(
                check=models.Q(("credits_received__gt", 0)),
                name="stream_credits_received_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="livestreamcredittransaction",
            constraint=models.CheckConstraint(
                check=models.Q(("creator_earnings__gte", 0)),
                name="stream_creator_earnings_check",
            ),
        ),
        migrations.AddIndex(
            model_name="livestreamchatmessage",
            index=models.Index(fields=["live_stream"], name="idx_chat_stream"),
        ),
        migrations.AddIndex(
            model_name="livestreamchatmessage",
            index=models.Index(fields=["fan"], name="idx_chat_fan"),
        ),
        migrations.AddIndex(
            model_name="livestreamchatmessage",
            index=models.Index(fields=["status"], name="idx_chat_status"),
        ),
        migrations.AddIndex(
            model_name="livestreamchatmessage",
            index=models.Index(fields=["sent_at"], name="idx_chat_sent"),
        ),
        migrations.AddIndex(
            model_name="livestream",
            index=models.Index(fields=["creator"], name="idx_livestream_creator"),
        ),
        migrations.AddIndex(
            model_name="livestream",
            index=models.Index(fields=["status"], name="idx_livestream_status"),
        ),
        migrations.AddIndex(
            model_name="livestream",
            index=models.Index(fields=["access_type"], name="idx_livestream_access"),
        ),
        migrations.AddIndex(
            model_name="livestream",
            index=models.Index(
                fields=["scheduled_at"], name="idx_livestream_scheduled"
            ),
        ),
        migrations.AddIndex(
            model_name="livestream",
            index=models.Index(fields=["started_at"], name="idx_livestream_started"),
        ),
        migrations.AddConstraint(
            model_name="livestream",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("access_type", "paid_entry"), _negated=True),
                    ("entry_price__isnull", False),
                    _connector="OR",
                ),
                name="livestream_entry_price_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="livestream",
            constraint=models.CheckConstraint(
                check=models.Q(("credits_used__gte", 0)),
                name="livestream_credits_used_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="livestream",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("peak_viewer_count__gte", 0),
                    ("total_viewer_count__gte", 0),
                    ("current_viewer_count__gte", 0),
                ),
                name="livestream_viewer_count_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="livestream",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("total_tips_amount__gte", 0),
                    ("total_credits_received__gte", 0),
                    ("total_revenue__gte", 0),
                ),
                name="livestream_revenue_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="livestream",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("duration_seconds__isnull", True),
                    ("duration_seconds__gte", 0),
                    _connector="OR",
                ),
                name="livestream_duration_check",
            ),
        ),
    ]
