# Generated by Django 4.2.7 on 2026-03-27 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "lipaidox_live_streaming",
            "0002_remove_livestreamchatmessage_chat_message_length_check",
        ),
    ]

    operations = []
