# Generated by Django 4.2.7 on 2026-07-14 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lipaidox', '0001_initial'),
        ('lipaidox_live_streaming', '0004_livestreammedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStreamEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_stream_entries', to=settings.AUTH_USER_MODEL)),
                ('live_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='lipaidox_live_streaming.livestream')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_instances', to='lipaidox.tenant')),
            ],
            options={
                'db_table': 'live_stream_entries',
                'indexes': [models.Index(fields=['fan'], name='idx_lse_fan'), models.Index(fields=['live_stream'], name='idx_lse_stream')],
            },
        ),
        migrations.AddConstraint(
            model_name='livestreamentry',
            constraint=models.UniqueConstraint(fields=('live_stream', 'fan'), name='live_stream_entry_unique'),
        ),
    ]
