# Generated by Django 4.2.7 on 2026-09-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipaidox_live_streaming', '0005_livestreamentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='end_reason',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='livestream',
            name='credits_used',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
