# Generated by Django 4.2.7 on 2026-03-23 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lipaidox", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreatorOnboardingStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "overall_status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("suspended", "Suspended"),
                            ("rejected", "Rejected"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("account_created", "Account Created"),
                            ("email_verified", "Email Verified"),
                            ("phone_verified", "Phone Verified"),
                            ("profile_setup", "Profile Setup"),
                            ("content_classification", "Content Classification"),
                            ("identity_verification", "Identity Verification"),
                            ("payment_setup", "Payment Setup"),
                            ("monetization_setup", "Monetization Setup"),
                        ],
                        default="account_created",
                        max_length=50,
                    ),
                ),
                (
                    "completion_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "account_created_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("account_created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "email_verified_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "phone_verified_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("phone_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile_setup_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("profile_setup_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_classification_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "content_classification_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "identity_verification_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "identity_verification_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "payment_setup_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("payment_setup_at", models.DateTimeField(blank=True, null=True)),
                (
                    "monetization_setup_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("monetization_setup_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_status",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "creator_onboarding_status",
            },
        ),
        migrations.CreateModel(
            name="OnboardingStepLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("account_created", "Account Created"),
                            ("email_verified", "Email Verified"),
                            ("phone_verified", "Phone Verified"),
                            ("profile_setup", "Profile Setup"),
                            ("content_classification", "Content Classification"),
                            ("identity_verification", "Identity Verification"),
                            ("payment_setup", "Payment Setup"),
                            ("monetization_setup", "Monetization Setup"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("step_started", "Step Started"),
                            ("step_completed", "Step Completed"),
                            ("step_failed", "Step Failed"),
                            ("step_retried", "Step Retried"),
                            ("step_skipped", "Step Skipped"),
                            ("document_uploaded", "Document Uploaded"),
                            ("document_rejected", "Document Rejected"),
                            ("document_resubmitted", "Document Resubmitted"),
                            ("admin_approved", "Admin Approved"),
                            ("admin_rejected", "Admin Rejected"),
                            (
                                "admin_requested_resubmission",
                                "Admin Requested Resubmission",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status_before",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "status_after",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[
                            ("creator", "Creator"),
                            ("admin", "Admin"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "onboarding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="lipaidox_onboarding.creatoronboardingstatus",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "onboarding_step_logs",
            },
        ),
    ]
