# Generated by Django 4.2.7 on 2026-03-27 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lipaidox_payment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lipaidox_creator_profile", "0004_usernamehistory_and_more"),
        (
            "lipaidox_content",
            "0004_remove_contentreport_unique_pending_report_per_user_content_and_more",
        ),
        ("lipaidox", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PPVPurchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[("one_time", "One Time"), ("timed", "Timed")],
                        default="one_time",
                        max_length=20,
                    ),
                ),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "platform_fee_percent",
                    models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
                ),
                ("platform_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("access_granted_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_expired", models.BooleanField(default=False)),
                ("allow_download", models.BooleanField(default=False)),
                ("download_count", models.IntegerField(default=0)),
                (
                    "gateway_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                ("refund_reason", models.TextField(blank=True, null=True)),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ppv_purchases",
                        to="lipaidox_content.content",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ppv_sales",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "fan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ppv_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lipaidox_payment.paymentmethod",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "ppv_purchases",
            },
        ),
        migrations.CreateModel(
            name="PPVAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("device_type", models.CharField(blank=True, max_length=50, null=True)),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ppv_access_logs",
                        to="lipaidox_content.content",
                    ),
                ),
                (
                    "fan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ppv_access_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="lipaidox_ppv.ppvpurchase",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "ppv_access_logs",
                "ordering": ["-accessed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="ppvpurchase",
            index=models.Index(fields=["fan"], name="idx_ppv_fan"),
        ),
        migrations.AddIndex(
            model_name="ppvpurchase",
            index=models.Index(fields=["creator"], name="idx_ppv_creator"),
        ),
        migrations.AddIndex(
            model_name="ppvpurchase",
            index=models.Index(fields=["content"], name="idx_ppv_content"),
        ),
        migrations.AddIndex(
            model_name="ppvpurchase",
            index=models.Index(fields=["status"], name="idx_ppv_status"),
        ),
        migrations.AddIndex(
            model_name="ppvpurchase",
            index=models.Index(fields=["expires_at"], name="idx_ppv_expires"),
        ),
        migrations.AddIndex(
            model_name="ppvpurchase",
            index=models.Index(fields=["purchased_at"], name="idx_ppv_purchased"),
        ),
        migrations.AddConstraint(
            model_name="ppvpurchase",
            constraint=models.UniqueConstraint(
                fields=("fan", "content"), name="ppv_purchases_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="ppvpurchase",
            constraint=models.CheckConstraint(
                check=models.Q(("amount_paid__gt", 0)), name="ppv_amount_paid_check"
            ),
        ),
        migrations.AddConstraint(
            model_name="ppvpurchase",
            constraint=models.CheckConstraint(
                check=models.Q(("platform_fee__gte", 0)), name="ppv_platform_fee_check"
            ),
        ),
        migrations.AddConstraint(
            model_name="ppvpurchase",
            constraint=models.CheckConstraint(
                check=models.Q(("net_amount__gte", 0)), name="ppv_net_amount_check"
            ),
        ),
        migrations.AddConstraint(
            model_name="ppvpurchase",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "net_amount",
                        django.db.models.expressions.CombinedExpression(
                            models.F("amount_paid"), "-", models.F("platform_fee")
                        ),
                    )
                ),
                name="ppv_net_amount_calc",
            ),
        ),
        migrations.AddConstraint(
            model_name="ppvpurchase",
            constraint=models.CheckConstraint(
                check=models.Q(("download_count__gte", 0)),
                name="ppv_download_count_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="ppvpurchase",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("refund_amount__isnull", True),
                    models.Q(
                        ("refund_amount__gt", 0),
                        ("refund_amount__lte", models.F("amount_paid")),
                    ),
                    _connector="OR",
                ),
                name="ppv_refund_amount_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="ppvpurchase",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("access_type", "timed"), _negated=True),
                    ("expires_at__isnull", False),
                    _connector="OR",
                ),
                name="ppv_timed_expiry_check",
            ),
        ),
        migrations.AddIndex(
            model_name="ppvaccesslog",
            index=models.Index(fields=["purchase"], name="idx_ppv_log_purchase"),
        ),
        migrations.AddIndex(
            model_name="ppvaccesslog",
            index=models.Index(fields=["fan"], name="idx_ppv_log_fan"),
        ),
        migrations.AddIndex(
            model_name="ppvaccesslog",
            index=models.Index(fields=["accessed_at"], name="idx_ppv_log_accessed"),
        ),
    ]
