# Generated by Django 4.2.7 on 2026-03-27 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lipaidox", "0001_initial"),
        ("lipaidox_content", "0003_contentreport_contentmoderationlog_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "admin_role",
                    models.CharField(
                        choices=[
                            ("superadmin", "Super Admin"),
                            ("admin", "Admin"),
                            ("moderator", "Moderator"),
                            ("support", "Support"),
                            ("finance", "Finance"),
                        ],
                        default="moderator",
                        max_length=20,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("can_manage_kyc", models.BooleanField(default=False)),
                ("can_manage_financials", models.BooleanField(default=False)),
                ("can_manage_content", models.BooleanField(default=False)),
                ("can_manage_users", models.BooleanField(default=False)),
                ("can_post_announcements", models.BooleanField(default=False)),
                ("can_gift_credits", models.BooleanField(default=False)),
                ("last_active_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "admin_accounts",
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "announcement_type",
                    models.CharField(
                        choices=[
                            ("platform_update", "Platform Update"),
                            ("feature_release", "Feature Release"),
                            ("maintenance", "Maintenance"),
                            ("policy_change", "Policy Change"),
                            ("promotion", "Promotion"),
                            ("security_alert", "Security Alert"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                (
                    "banner_image_url",
                    models.URLField(blank=True, max_length=2000, null=True),
                ),
                ("cta_label", models.CharField(blank=True, max_length=100, null=True)),
                ("cta_url", models.URLField(blank=True, max_length=2000, null=True)),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("all_users", "All Users"),
                            ("creators_only", "Creators Only"),
                            ("fans_only", "Fans Only"),
                            ("premium_creators", "Premium Creators"),
                            ("promax_creators", "Promax Creators"),
                            ("verified_creators", "Verified Creators"),
                            ("specific_users", "Specific Users"),
                        ],
                        default="all_users",
                        max_length=30,
                    ),
                ),
                ("target_user_ids", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_pinned", models.BooleanField(default=False)),
                ("show_as_banner", models.BooleanField(default=False)),
                ("show_in_feed", models.BooleanField(default=True)),
                ("show_as_notification", models.BooleanField(default=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("read_count", models.IntegerField(default=0)),
                ("dismissed_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by_admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_announcements",
                        to="lipaidox_admin_panel.adminaccount",
                    ),
                ),
            ],
            options={
                "db_table": "announcements",
            },
        ),
        migrations.CreateModel(
            name="PlatformAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("official", "Official"),
                            ("updates", "Updates"),
                            ("support", "Support"),
                            ("moderation", "Moderation"),
                            ("promotions", "Promotions"),
                        ],
                        default="official",
                        max_length=20,
                    ),
                ),
                ("handle", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("bio", models.TextField(blank=True, null=True)),
                ("avatar_url", models.URLField(blank=True, max_length=2000, null=True)),
                ("cover_url", models.URLField(blank=True, max_length=2000, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=True)),
                ("follower_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "managed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_platform_accounts",
                        to="lipaidox_admin_panel.adminaccount",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "platform_accounts",
            },
        ),
        migrations.CreateModel(
            name="AnnouncementRead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_dismissed", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(auto_now_add=True)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reads",
                        to="lipaidox_admin_panel.announcement",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement_reads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "announcement_reads",
            },
        ),
        migrations.AddField(
            model_name="announcement",
            name="platform_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="announcements",
                to="lipaidox_admin_panel.platformaccount",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_instances",
                to="lipaidox.tenant",
            ),
        ),
        migrations.CreateModel(
            name="AdminAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("acted_on_entity_id", models.UUIDField(blank=True, null=True)),
                (
                    "acted_on_entity_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("user_management", "User Management"),
                            ("content_moderation", "Content Moderation"),
                            ("kyc_review", "KYC Review"),
                            ("financial", "Financial"),
                            ("platform_settings", "Platform Settings"),
                            ("announcement", "Announcement"),
                            ("credit_management", "Credit Management"),
                            ("account_flag", "Account Flag"),
                            ("report_resolution", "Report Resolution"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("user_suspended", "User Suspended"),
                            ("user_banned", "User Banned"),
                            ("user_activated", "User Activated"),
                            ("user_deactivated", "User Deactivated"),
                            ("user_role_changed", "User Role Changed"),
                            ("user_password_reset", "User Password Reset"),
                            ("kyc_approved", "KYC Approved"),
                            ("kyc_rejected", "KYC Rejected"),
                            (
                                "kyc_resubmission_requested",
                                "KYC Resubmission Requested",
                            ),
                            ("kyc_permanently_rejected", "KYC Permanently Rejected"),
                            ("content_removed", "Content Removed"),
                            ("content_flagged", "Content Flagged"),
                            ("content_approved", "Content Approved"),
                            ("content_restored", "Content Restored"),
                            ("payout_approved", "Payout Approved"),
                            ("payout_rejected", "Payout Rejected"),
                            ("payout_reversed", "Payout Reversed"),
                            ("credit_gifted", "Credit Gifted"),
                            ("fee_overridden", "Fee Overridden"),
                            ("account_flagged", "Account Flagged"),
                            ("account_flag_resolved", "Account Flag Resolved"),
                            ("account_flag_dismissed", "Account Flag Dismissed"),
                            ("report_resolved", "Report Resolved"),
                            ("report_dismissed", "Report Dismissed"),
                            ("report_escalated", "Report Escalated"),
                            ("announcement_created", "Announcement Created"),
                            ("announcement_updated", "Announcement Updated"),
                            ("announcement_deleted", "Announcement Deleted"),
                            ("platform_post_created", "Platform Post Created"),
                            ("platform_post_removed", "Platform Post Removed"),
                            ("platform_settings_updated", "Platform Settings Updated"),
                        ],
                        max_length=30,
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("state_before", models.JSONField(blank=True, default=dict)),
                ("state_after", models.JSONField(blank=True, default=dict)),
                ("is_reversible", models.BooleanField(default=False)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("reversal_reason", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acted_on_content",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_actions_taken_on",
                        to="lipaidox_content.content",
                    ),
                ),
                (
                    "acted_on_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_actions_taken_on",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="lipaidox_admin_panel.adminaccount",
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversed_actions",
                        to="lipaidox_admin_panel.adminaccount",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "admin_actions",
            },
        ),
        migrations.CreateModel(
            name="AccountFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("suspected_fraud", "Suspected Fraud"),
                            ("identity_mismatch", "Identity Mismatch"),
                            ("duplicate_account", "Duplicate Account"),
                            ("policy_violation", "Policy Violation"),
                            ("payment_fraud", "Payment Fraud"),
                            ("content_violation", "Content Violation"),
                            ("spam_behaviour", "Spam Behaviour"),
                            ("aml_concern", "AML Concern"),
                            ("chargeback_abuse", "Chargeback Abuse"),
                            ("suspicious_login", "Suspicious Login"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("flagged_by_system", models.BooleanField(default=False)),
                (
                    "system_trigger",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("under_investigation", "Under Investigation"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                            ("escalated", "Escalated"),
                        ],
                        default="open",
                        max_length=30,
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("investigation_notes", models.TextField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no_action", "No Action"),
                            ("warning_issued", "Warning Issued"),
                            ("account_restricted", "Account Restricted"),
                            ("account_suspended", "Account Suspended"),
                            ("account_banned", "Account Banned"),
                            ("referred_to_legal", "Referred to Legal"),
                            ("false_positive", "False Positive"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("resolution_note", models.TextField(blank=True, null=True)),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
                ("escalation_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flags_assigned",
                        to="lipaidox_admin_panel.adminaccount",
                    ),
                ),
                (
                    "escalated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flags_escalated",
                        to="lipaidox_admin_panel.adminaccount",
                    ),
                ),
                (
                    "flagged_by_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flags_created",
                        to="lipaidox_admin_panel.adminaccount",
                    ),
                ),
                (
                    "flagged_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flags_resolved",
                        to="lipaidox_admin_panel.adminaccount",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "account_flags",
            },
        ),
        migrations.CreateModel(
            name="PlatformPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("announcement", "Announcement"),
                            ("tutorial", "Tutorial"),
                            ("feature_guide", "Feature Guide"),
                            ("promotional", "Promotional"),
                            ("maintenance_notice", "Maintenance Notice"),
                            ("policy_update", "Policy Update"),
                        ],
                        default="announcement",
                        max_length=30,
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("all_users", "All Users"),
                            ("creators_only", "Creators Only"),
                            ("fans_only", "Fans Only"),
                            ("premium_creators", "Premium Creators"),
                            ("promax_creators", "Promax Creators"),
                            ("verified_creators", "Verified Creators"),
                            ("specific_users", "Specific Users"),
                        ],
                        default="all_users",
                        max_length=30,
                    ),
                ),
                ("target_user_ids", models.JSONField(blank=True, default=list)),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_system_post", models.BooleanField(default=True)),
                ("allow_comments", models.BooleanField(default=False)),
                ("allow_likes", models.BooleanField(default=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_posts",
                        to="lipaidox_admin_panel.announcement",
                    ),
                ),
                (
                    "content",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_post",
                        to="lipaidox_content.content",
                    ),
                ),
                (
                    "created_by_admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_platform_posts",
                        to="lipaidox_admin_panel.adminaccount",
                    ),
                ),
                (
                    "platform_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="lipaidox_admin_panel.platformaccount",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "platform_posts",
                "indexes": [
                    models.Index(
                        fields=["platform_account"],
                        name="platform_po_platfor_ca6fd7_idx",
                    ),
                    models.Index(
                        fields=["post_type"], name="platform_po_post_ty_825182_idx"
                    ),
                    models.Index(
                        fields=["target_audience"],
                        name="platform_po_target__590d7d_idx",
                    ),
                    models.Index(
                        fields=["is_pinned"], name="platform_po_is_pinn_f8df8b_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="platform_po_created_090b15_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="platformaccount",
            index=models.Index(fields=["handle"], name="platform_ac_handle_ee3a93_idx"),
        ),
        migrations.AddIndex(
            model_name="platformaccount",
            index=models.Index(
                fields=["account_type"], name="platform_ac_account_650112_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="platformaccount",
            index=models.Index(
                fields=["is_active"], name="platform_ac_is_acti_29f202_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="platformaccount",
            constraint=models.CheckConstraint(
                check=models.Q(("follower_count__gte", 0)), name="follower_count_check"
            ),
        ),
        migrations.AddIndex(
            model_name="announcementread",
            index=models.Index(
                fields=["announcement"], name="announcemen_announc_1b88ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="announcementread",
            index=models.Index(fields=["user"], name="announcemen_user_id_e00460_idx"),
        ),
        migrations.AddIndex(
            model_name="announcementread",
            index=models.Index(
                fields=["is_dismissed"], name="announcemen_is_dism_c5f029_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="announcementread",
            unique_together={("announcement", "user")},
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["platform_account"], name="announcemen_platfor_b5dc62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["announcement_type"], name="announcemen_announc_b7733d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(fields=["status"], name="announcemen_status_a07d93_idx"),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["target_audience"], name="announcemen_target__e32955_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["published_at"], name="announcemen_publish_6b0e06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["is_pinned"], name="announcemen_is_pinn_52ad7c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="announcement",
            constraint=models.CheckConstraint(
                check=models.Q(("read_count__gte", 0)), name="read_count_check"
            ),
        ),
        migrations.AddConstraint(
            model_name="announcement",
            constraint=models.CheckConstraint(
                check=models.Q(("dismissed_count__gte", 0)),
                name="dismissed_count_check",
            ),
        ),
        migrations.AddIndex(
            model_name="adminaction",
            index=models.Index(fields=["admin"], name="admin_actio_admin_i_1c477a_idx"),
        ),
        migrations.AddIndex(
            model_name="adminaction",
            index=models.Index(
                fields=["acted_on_user"], name="admin_actio_acted_o_76c648_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminaction",
            index=models.Index(
                fields=["acted_on_content"], name="admin_actio_acted_o_e4fd1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminaction",
            index=models.Index(
                fields=["action_type"], name="admin_actio_action__d7b108_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminaction",
            index=models.Index(
                fields=["category"], name="admin_actio_categor_0353d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminaction",
            index=models.Index(
                fields=["created_at"], name="admin_actio_created_6f8524_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="adminaction",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("reversed_at__isnull", True),
                    ("is_reversible", True),
                    _connector="OR",
                ),
                name="reversal_check",
            ),
        ),
        migrations.AddIndex(
            model_name="adminaccount",
            index=models.Index(fields=["user"], name="admin_accou_user_id_62c481_idx"),
        ),
        migrations.AddIndex(
            model_name="adminaccount",
            index=models.Index(
                fields=["admin_role"], name="admin_accou_admin_r_f15673_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminaccount",
            index=models.Index(
                fields=["is_active"], name="admin_accou_is_acti_371461_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountflag",
            index=models.Index(
                fields=["flagged_user"], name="account_fla_flagged_16868a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountflag",
            index=models.Index(fields=["reason"], name="account_fla_reason_b80478_idx"),
        ),
        migrations.AddIndex(
            model_name="accountflag",
            index=models.Index(
                fields=["severity"], name="account_fla_severit_91304f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountflag",
            index=models.Index(fields=["status"], name="account_fla_status_1502f0_idx"),
        ),
        migrations.AddIndex(
            model_name="accountflag",
            index=models.Index(
                fields=["assigned_to"], name="account_fla_assigne_9d1a73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountflag",
            index=models.Index(
                fields=["created_at"], name="account_fla_created_a973f7_idx"
            ),
        ),
    ]
