# Generated by Django 4.2.7 on 2026-03-31 12:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "lms_identity",
            "0006_institutionuser_coursereview_courseassignmentteam_and_more",
        ),
        ("lms_content", "0006_labsubmission"),
        ("lipaidox", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillAssessmentQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("rating", "Rating Scale"),
                            ("text", "Text Input"),
                            ("checkbox", "Checkbox"),
                        ],
                        default="multiple_choice",
                        max_length=20,
                    ),
                ),
                ("options", models.JSONField(blank=True, default=list)),
                ("skill_category", models.CharField(max_length=100)),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "lms_skill_assessment_questions",
                "ordering": ["order", "skill_category", "difficulty_level"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("reason", models.TextField()),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("skill_match", "Skill Match"),
                            ("career_goal", "Career Goal"),
                            ("interest", "Interest Based"),
                            ("popular", "Popular"),
                        ],
                        default="skill_match",
                        max_length=20,
                    ),
                ),
                ("is_viewed", models.BooleanField(default=False)),
                ("is_enrolled", models.BooleanField(default=False)),
                ("enrolled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_recommendations",
                        to="lms_content.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_recommendations",
                        to="lms_identity.studentprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "lms_onboarding_recommendations",
            },
        ),
        migrations.CreateModel(
            name="OnboardingProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_step",
                    models.IntegerField(
                        choices=[
                            ("1", "Personal Information"),
                            ("2", "Employment Status"),
                            ("3", "Career Goals"),
                            ("4", "Preferences & Interests"),
                            ("5", "Skill Assessment"),
                            ("6", "Completed"),
                        ],
                        default="1",
                    ),
                ),
                ("completed_steps", models.JSONField(blank=True, default=list)),
                (
                    "personal_info_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "employment_status_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "career_goals_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "preferences_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "skill_assessment_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("session_count", models.IntegerField(default=0)),
                ("last_session_at", models.DateTimeField(blank=True, null=True)),
                ("total_time_spent_minutes", models.IntegerField(default=0)),
                ("skipped_steps", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_progress",
                        to="lms_identity.studentprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "lms_onboarding_progress",
            },
        ),
        migrations.CreateModel(
            name="SkillAssessmentResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("response_text", models.TextField(blank=True, null=True)),
                ("response_rating", models.IntegerField(blank=True, null=True)),
                ("response_options", models.JSONField(blank=True, default=list)),
                ("time_spent_seconds", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="lms_onboarding.skillassessmentquestion",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_assessment_responses",
                        to="lms_identity.studentprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "lms_skill_assessment_responses",
                "indexes": [
                    models.Index(fields=["student"], name="idx_response_student"),
                    models.Index(fields=["question"], name="idx_response_question"),
                ],
                "unique_together": {("student", "question")},
            },
        ),
        migrations.AddIndex(
            model_name="skillassessmentquestion",
            index=models.Index(fields=["skill_category"], name="idx_question_category"),
        ),
        migrations.AddIndex(
            model_name="skillassessmentquestion",
            index=models.Index(
                fields=["difficulty_level"], name="idx_question_difficulty"
            ),
        ),
        migrations.AddIndex(
            model_name="skillassessmentquestion",
            index=models.Index(fields=["is_active"], name="idx_question_active"),
        ),
        migrations.AddIndex(
            model_name="onboardingrecommendation",
            index=models.Index(fields=["student"], name="idx_rec_student"),
        ),
        migrations.AddIndex(
            model_name="onboardingrecommendation",
            index=models.Index(fields=["course"], name="idx_rec_course"),
        ),
        migrations.AddIndex(
            model_name="onboardingrecommendation",
            index=models.Index(fields=["-score"], name="idx_rec_score"),
        ),
        migrations.AddIndex(
            model_name="onboardingrecommendation",
            index=models.Index(fields=["recommendation_type"], name="idx_rec_type"),
        ),
        migrations.AddIndex(
            model_name="onboardingprogress",
            index=models.Index(fields=["student"], name="idx_onboard_student"),
        ),
        migrations.AddIndex(
            model_name="onboardingprogress",
            index=models.Index(fields=["current_step"], name="idx_onboard_step"),
        ),
        migrations.AddIndex(
            model_name="onboardingprogress",
            index=models.Index(fields=["is_completed"], name="idx_onboard_completed"),
        ),
        migrations.AddIndex(
            model_name="onboardingprogress",
            index=models.Index(fields=["-created_at"], name="idx_onboard_created"),
        ),
    ]
