# Generated by Django 4.2.7 on 2026-03-27 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lipaidox", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lipaidox_payment", "0001_initial"),
        (
            "lipaidox_content",
            "0004_remove_contentreport_unique_pending_report_per_user_content_and_more",
        ),
        ("lipaidox_creator_profile", "0004_usernamehistory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tip_type",
                    models.CharField(
                        choices=[("money", "Money")], default="money", max_length=20
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("message", models.TextField(blank=True, null=True)),
                ("is_anonymous", models.BooleanField(default=False)),
                (
                    "platform_fee_percent",
                    models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
                ),
                ("platform_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "gateway_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "live_stream_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                ("refund_reason", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tips",
                        to="lipaidox_content.content",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tips_received",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "fan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tips_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lipaidox_payment.paymentmethod",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tips",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(fields=["fan"], name="idx_tips_fan"),
                    models.Index(fields=["creator"], name="idx_tips_creator"),
                    models.Index(fields=["content"], name="idx_tips_content"),
                    models.Index(fields=["status"], name="idx_tips_status"),
                    models.Index(fields=["sent_at"], name="idx_tips_sent"),
                    models.Index(fields=["live_stream_id"], name="idx_tips_stream"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="tip",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gt", 0)), name="tips_amount_check"
            ),
        ),
        migrations.AddConstraint(
            model_name="tip",
            constraint=models.CheckConstraint(
                check=models.Q(("platform_fee__gte", 0)), name="tips_platform_fee_check"
            ),
        ),
        migrations.AddConstraint(
            model_name="tip",
            constraint=models.CheckConstraint(
                check=models.Q(("net_amount__gte", 0)), name="tips_net_amount_check"
            ),
        ),
        migrations.AddConstraint(
            model_name="tip",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "net_amount",
                        django.db.models.expressions.CombinedExpression(
                            models.F("amount"), "-", models.F("platform_fee")
                        ),
                    )
                ),
                name="tips_net_amount_calc",
            ),
        ),
    ]
