# Generated by Django 4.2.7 on 2026-03-30 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lms_identity", "0002_instructorprofile"),
        ("lipaidox", "0001_initial"),
        ("lms_content", "0003_resource_lab"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailableCertification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("provider", models.CharField(max_length=255)),
                (
                    "cert_type",
                    models.CharField(
                        choices=[
                            ("professional", "Professional Certificate"),
                            ("completion", "Certificate of Completion"),
                            ("skill_mastery", "Skill Mastery"),
                        ],
                        default="professional",
                        max_length=20,
                    ),
                ),
                ("difficulty", models.CharField(default="intermediate", max_length=20)),
                ("estimated_hours", models.IntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("requirements", models.JSONField(default=list)),
                ("skills", models.JSONField(default=list)),
                ("enrolled_count", models.IntegerField(default=0)),
                (
                    "pass_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "lms_available_certifications",
            },
        ),
        migrations.CreateModel(
            name="SkillBadge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("skill_name", models.CharField(max_length=255)),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("platinum", "Platinum"),
                            ("gold", "Gold"),
                            ("silver", "Silver"),
                            ("bronze", "Bronze"),
                        ],
                        default="bronze",
                        max_length=20,
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("assessments_count", models.IntegerField(default=0)),
                ("endorsements_count", models.IntegerField(default=0)),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                ("verification_code", models.CharField(max_length=100, unique=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to="lms_identity.studentprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "lms_skill_badges",
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("professional", "Professional Certificate"),
                            ("completion", "Certificate of Completion"),
                            ("skill_mastery", "Skill Mastery"),
                        ],
                        default="completion",
                        max_length=20,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("distinction", "Distinction"),
                            ("merit", "Merit"),
                            ("honors", "Honors"),
                            ("pass", "Pass"),
                        ],
                        default="pass",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("issue_date", models.DateTimeField(auto_now_add=True)),
                ("verification_code", models.CharField(max_length=100, unique=True)),
                ("public_url", models.URLField(blank=True, max_length=500, null=True)),
                ("qr_code_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "blockchain_hash",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "blockchain_network",
                    models.CharField(default="Polygon", max_length=100),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("view_count", models.IntegerField(default=0)),
                ("download_count", models.IntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lms_content.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="lms_identity.studentprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "lms_certificates",
            },
        ),
        migrations.CreateModel(
            name="CertificationEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("progress_percent", models.IntegerField(default=0)),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "certification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrolled_students",
                        to="lms_certification.availablecertification",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cert_enrollments",
                        to="lms_identity.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "lms_certification_enrollments",
                "unique_together": {("student", "certification")},
            },
        ),
        migrations.CreateModel(
            name="BadgeEndorsement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endorsed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endorsements",
                        to="lms_certification.skillbadge",
                    ),
                ),
                (
                    "endorsed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lms_badge_endorsements",
                "unique_together": {("badge", "endorsed_by")},
            },
        ),
    ]
