# Generated by Django 4.2.7 on 2026-03-23 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lipaidox", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreatorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("bio", models.TextField(blank=True, max_length=1000, null=True)),
                (
                    "profile_photo_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "cover_photo_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("website_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "country_of_residence",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "preferred_language",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("timezone", models.CharField(blank=True, max_length=100, null=True)),
                ("gender", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "area_of_interest",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "social_instagram",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                (
                    "social_twitter",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                (
                    "social_tiktok",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                (
                    "social_youtube",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                (
                    "social_facebook",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                (
                    "social_linkedin",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                ("social_other", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("incomplete", "Incomplete"),
                            ("complete", "Complete"),
                            ("suspended", "Suspended"),
                            ("deactivated", "Deactivated"),
                        ],
                        default="incomplete",
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "creator_tier",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("platinum", "Platinum"),
                        ],
                        default="bronze",
                        max_length=20,
                    ),
                ),
                (
                    "fan_club_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("welcome_message", models.TextField(blank=True, null=True)),
                ("follower_count", models.IntegerField(default=0)),
                ("subscriber_count", models.IntegerField(default=0)),
                (
                    "total_earnings",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=14),
                ),
                ("profile_completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "creator_profiles",
                "indexes": [
                    models.Index(
                        fields=["username"], name="creator_pro_usernam_963fa7_idx"
                    ),
                    models.Index(
                        fields=["status"], name="creator_pro_status_b0dd2f_idx"
                    ),
                    models.Index(
                        fields=["is_verified"], name="creator_pro_is_veri_567458_idx"
                    ),
                ],
            },
        ),
    ]
