# Generated by Django 4.2.7 on 2026-03-23 11:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lipaidox_creator_profile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creatorprofile",
            name="display_name",
        ),
    ]
