# Generated by Django 4.2.7 on 2026-03-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lipaidox_creator_profile", "0002_remove_creatorprofile_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatorprofile",
            name="live_credits",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="creatorprofile",
            name="plan_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="creatorprofile",
            name="plan_tier",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("premium", "Premium"),
                    ("promax", "Promax+"),
                ],
                default="free",
                max_length=20,
            ),
        ),
    ]
