# Generated by Django 4.2.7 on 2026-03-26 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lipaidox", "0001_initial"),
        ("lipaidox_creator_profile", "0003_creatorprofile_live_credits_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsernameHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(db_index=True, max_length=50)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="username_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "username_history",
                "indexes": [
                    models.Index(
                        fields=["username", "is_available"],
                        name="username_hi_usernam_3cd135_idx",
                    ),
                    models.Index(
                        fields=["user", "changed_at"],
                        name="username_hi_user_id_01848a_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="usernamehistory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_available", False)),
                fields=("username", "tenant"),
                name="unique_active_username",
            ),
        ),
    ]
