# Generated by Django 4.2.7 on 2026-03-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lipaidox_creator_profile", "0004_usernamehistory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatorprofile",
            name="content_blocks_count",
            field=models.IntegerField(default=0),
        ),
    ]
