# Generated by Django 4.2.7 on 2026-07-10 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lipaidox_creator_profile', '0008_membership_review'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='membershipsubscription',
            new_name='membership__subscri_8d52ec_idx',
            old_name='member_sub_subscr_idx',
        ),
        migrations.RenameIndex(
            model_name='membershipsubscription',
            new_name='membership__target__320df4_idx',
            old_name='member_sub_target_idx',
        ),
        migrations.RenameIndex(
            model_name='membershipsubscription',
            new_name='membership__status_2c56db_idx',
            old_name='member_sub_status_idx',
        ),
        migrations.RenameIndex(
            model_name='membershipsubscription',
            new_name='membership__subscri_6cb223_idx',
            old_name='member_sub_subscr_cr_idx',
        ),
        migrations.RenameIndex(
            model_name='membershipsubscription',
            new_name='membership__target__179a2f_idx',
            old_name='member_sub_target_cr_idx',
        ),
        migrations.RenameIndex(
            model_name='membershipsubscription',
            new_name='membership__subscri_417f53_idx',
            old_name='member_sub_pair_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='creator_rev_target__10a897_idx',
            old_name='review_target_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='creator_rev_author__0c3b06_idx',
            old_name='review_author_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='creator_rev_status_b243e8_idx',
            old_name='review_status_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='creator_rev_rating_f518dd_idx',
            old_name='review_rating_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='creator_rev_created_197861_idx',
            old_name='review_created_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='creator_rev_target__78873b_idx',
            old_name='review_target_status_cr_idx',
        ),
        migrations.RenameIndex(
            model_name='reviewhelpful',
            new_name='review_help_review__453137_idx',
            old_name='review_help_review_idx',
        ),
        migrations.RenameIndex(
            model_name='reviewhelpful',
            new_name='review_help_user_id_28e37c_idx',
            old_name='review_help_user_idx',
        ),
        migrations.RenameIndex(
            model_name='reviewreport',
            new_name='review_repo_review__018a02_idx',
            old_name='review_report_review_idx',
        ),
    ]
