# Generated by Django 4.2.7 on 2026-07-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipaidox_creator_profile', '0009_rename_member_sub_subscr_idx_membership__subscri_8d52ec_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='owner_replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='owner_reply',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='review',
            name='owner_reply_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
