# Generated by Django 4.2.7 on 2026-08-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipaidox_creator_profile', '0010_review_owner_replied_at_review_owner_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='content_categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
