# Generated by Django 4.2.7 on 2026-09-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipaidox_creator_profile', '0011_creatorprofile_content_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofile',
            name='plan_tier',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('go_plus', 'Go Plus'), ('premium', 'Premium'), ('promax', 'Promax+')], default='free', max_length=20),
        ),
    ]
