# Generated by Django 4.2.7 on 2026-09-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipaidox_creator_profile', '0012_alter_creatorprofile_plan_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='account_kind',
            field=models.CharField(choices=[('creator', 'Creator'), ('business', 'Business')], default='creator', max_length=10),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='business_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='business_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='business_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='business_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='business_website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='contact_show_directions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='contact_show_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='contact_show_phone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='contact_show_whatsapp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='show_category_on_profile',
            field=models.BooleanField(default=True),
        ),
    ]
