# Generated by Django 4.2.7 on 2026-09-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipaidox_creator_profile', '0013_creatorprofile_account_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='username_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
