# Generated by Django 4.2.7 on 2026-09-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipaidox_creator_profile', '0014_creatorprofile_username_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='show_gender_on_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='show_birthday_on_profile',
            field=models.BooleanField(default=False),
        ),
    ]
