# Generated by Django 4.2.7 on 2026-03-24 17:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lipaidox_creator_profile", "0003_creatorprofile_live_credits_and_more"),
        ("lipaidox_payment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreatorPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("premium", "Premium"),
                            ("promax", "Promax+"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "price_per_month",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("can_monetize", models.BooleanField(default=False)),
                ("can_live_stream", models.BooleanField(default=False)),
                ("can_sell_ppv", models.BooleanField(default=False)),
                ("can_receive_tips", models.BooleanField(default=False)),
                ("can_sell_subscriptions", models.BooleanField(default=False)),
                ("can_sell_custom_content", models.BooleanField(default=False)),
                ("monthly_free_credits", models.IntegerField(default=0)),
                ("unlimited_live_sessions", models.IntegerField(default=0)),
                (
                    "credit_top_up_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "credit_top_up_duration_mins",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "max_content_uploads_per_month",
                    models.IntegerField(blank=True, null=True),
                ),
                ("max_file_size_mb", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "creator_plans",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="CreatorPlanPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plan_tier",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("premium", "Premium"),
                            ("promax", "Promax+"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial"),
                            ("renewal", "Renewal"),
                            ("retry", "Retry"),
                            ("upgrade", "Upgrade"),
                            ("credit_top_up", "Credit Top Up"),
                        ],
                        default="renewal",
                        max_length=20,
                    ),
                ),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateTimeField(blank=True, null=True)),
                ("period_end", models.DateTimeField(blank=True, null=True)),
                ("credits_purchased", models.IntegerField(blank=True, null=True)),
                ("credits_duration_mins", models.IntegerField(blank=True, null=True)),
                (
                    "gateway_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("gateway_response", models.JSONField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True, null=True)),
                ("retry_attempt", models.IntegerField(default=0)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                ("refund_reason", models.TextField(blank=True, null=True)),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_payments",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lipaidox_payment.paymentmethod",
                    ),
                ),
            ],
            options={
                "db_table": "creator_plan_payments",
            },
        ),
        migrations.CreateModel(
            name="CreatorPurchasedCredits",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("credits_purchased", models.IntegerField()),
                ("credits_remaining", models.IntegerField()),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchased_credits",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lipaidox_creator_plans.creatorplanpayment",
                    ),
                ),
            ],
            options={
                "db_table": "creator_purchased_credits",
            },
        ),
        migrations.CreateModel(
            name="CreatorPlanSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plan_tier",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("premium", "Premium"),
                            ("promax", "Promax+"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "price_at_signup",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("past_due", "Past Due"),
                            ("pending", "Pending"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("next_billing_date", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True, null=True)),
                ("cancel_at_period_end", models.BooleanField(default=True)),
                (
                    "downgrade_to_tier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("free", "Free"),
                            ("premium", "Premium"),
                            ("promax", "Promax+"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("available_credits", models.IntegerField(default=0)),
                ("credits_reset_at", models.DateTimeField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("last_retry_at", models.DateTimeField(blank=True, null=True)),
                ("max_retries", models.IntegerField(default=3)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_subscription",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lipaidox_payment.paymentmethod",
                    ),
                ),
            ],
            options={
                "db_table": "creator_plan_subscriptions",
            },
        ),
        migrations.AddField(
            model_name="creatorplanpayment",
            name="plan_subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="lipaidox_creator_plans.creatorplansubscription",
            ),
        ),
        migrations.CreateModel(
            name="CreatorLiveCreditUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("live_stream_id", models.UUIDField(blank=True, null=True)),
                ("credits_used", models.IntegerField(default=1)),
                ("duration_mins", models.IntegerField(default=15)),
                ("is_free_credit", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_usage",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "creator_live_credit_usage",
            },
        ),
        migrations.AddIndex(
            model_name="creatorplansubscription",
            index=models.Index(fields=["status"], name="creator_pla_status_692136_idx"),
        ),
        migrations.AddIndex(
            model_name="creatorplansubscription",
            index=models.Index(
                fields=["next_billing_date"], name="creator_pla_next_bi_fc2ca7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creatorplanpayment",
            index=models.Index(fields=["status"], name="creator_pla_status_dd2f08_idx"),
        ),
        migrations.AddIndex(
            model_name="creatorplanpayment",
            index=models.Index(
                fields=["attempted_at"], name="creator_pla_attempt_fd6728_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creatorlivecreditusage",
            index=models.Index(
                fields=["used_at"], name="creator_liv_used_at_abbc24_idx"
            ),
        ),
    ]
