# Generated by Django 4.2.7 on 2026-09-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lipaidox_creator_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorplan',
            name='annual_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='creatorplan',
            name='max_live_countries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creatorplan',
            name='max_premium_content_per_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creatorplan',
            name='max_subscription_tiers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creatorplan',
            name='platform_fee_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='creatorplan',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('go_plus', 'Go Plus'), ('premium', 'Premium'), ('promax', 'Promax+')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='creatorplanpayment',
            name='plan_tier',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('go_plus', 'Go Plus'), ('premium', 'Premium'), ('promax', 'Promax+')], max_length=20),
        ),
        migrations.AlterField(
            model_name='creatorplansubscription',
            name='downgrade_to_tier',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('basic', 'Basic'), ('go_plus', 'Go Plus'), ('premium', 'Premium'), ('promax', 'Promax+')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='creatorplansubscription',
            name='plan_tier',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('go_plus', 'Go Plus'), ('premium', 'Premium'), ('promax', 'Promax+')], default='free', max_length=20),
        ),
    ]
