# Generated by Django 4.2.7 on 2026-03-27 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lipaidox_creator_profile", "0004_usernamehistory_and_more"),
        (
            "lipaidox_content",
            "0004_remove_contentreport_unique_pending_report_per_user_content_and_more",
        ),
        ("lipaidox", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_date", models.DateField()),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("total_users", models.IntegerField(default=0)),
                ("new_users", models.IntegerField(default=0)),
                ("active_users", models.IntegerField(default=0)),
                ("total_creators", models.IntegerField(default=0)),
                ("new_creators", models.IntegerField(default=0)),
                ("active_creators", models.IntegerField(default=0)),
                ("total_fans", models.IntegerField(default=0)),
                ("new_fans", models.IntegerField(default=0)),
                ("total_content_published", models.IntegerField(default=0)),
                ("total_content_views", models.IntegerField(default=0)),
                ("total_live_streams", models.IntegerField(default=0)),
                (
                    "gross_revenue",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "platform_fees_collected",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "total_payouts",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "total_refunds",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("new_subscriptions", models.IntegerField(default=0)),
                ("cancelled_subscriptions", models.IntegerField(default=0)),
                ("active_subscriptions", models.IntegerField(default=0)),
                ("creator_credits_sold", models.IntegerField(default=0)),
                ("fan_credits_sold", models.IntegerField(default=0)),
                ("fan_credits_gifted", models.IntegerField(default=0)),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "platform_analytics",
            },
        ),
        migrations.CreateModel(
            name="FeedRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relevance_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "interest_match_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "social_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "diversity_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "freshness_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "recommendation_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                ("feed_position", models.IntegerField(default=0)),
                ("recommendation_reason", models.TextField(blank=True, null=True)),
                ("weight_factors", models.JSONField(blank=True, default=dict)),
                ("shown_at", models.DateTimeField(blank=True, null=True)),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                ("liked_at", models.DateTimeField(blank=True, null=True)),
                ("shared_at", models.DateTimeField(blank=True, null=True)),
                ("purchased_at", models.DateTimeField(blank=True, null=True)),
                ("skipped_at", models.DateTimeField(blank=True, null=True)),
                ("user_feedback", models.IntegerField(default=0)),
                ("engagement_time_seconds", models.IntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_recommendations",
                        to="lipaidox_content.content",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_recommendations",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "feed_recommendations",
            },
        ),
        migrations.CreateModel(
            name="CreatorAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_date", models.DateField()),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("follower_count", models.IntegerField(default=0)),
                ("follower_gained", models.IntegerField(default=0)),
                ("follower_lost", models.IntegerField(default=0)),
                ("subscriber_count", models.IntegerField(default=0)),
                ("subscriber_gained", models.IntegerField(default=0)),
                ("subscriber_lost", models.IntegerField(default=0)),
                ("content_published", models.IntegerField(default=0)),
                ("total_content_views", models.IntegerField(default=0)),
                ("total_content_likes", models.IntegerField(default=0)),
                ("total_content_comments", models.IntegerField(default=0)),
                (
                    "revenue_from_subscriptions",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "revenue_from_ppv",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "revenue_from_tips",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "revenue_from_credits",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "revenue_from_live_streams",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "platform_fees_paid",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "net_revenue",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("live_streams_count", models.IntegerField(default=0)),
                ("live_stream_total_viewers", models.IntegerField(default=0)),
                ("live_stream_peak_viewers", models.IntegerField(default=0)),
                ("live_stream_duration_mins", models.IntegerField(default=0)),
                (
                    "engagement_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "ppv_purchase_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "subscription_conversion_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "creator_analytics",
            },
        ),
        migrations.CreateModel(
            name="ContentWatermark",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "watermark_type",
                    models.CharField(
                        choices=[
                            ("visible", "Visible"),
                            ("invisible", "Invisible"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=20,
                    ),
                ),
                ("visible_enabled", models.BooleanField(default=True)),
                (
                    "visible_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("visible_logo_url", models.TextField(blank=True, null=True)),
                (
                    "visible_position",
                    models.CharField(
                        choices=[
                            ("top_left", "Top Left"),
                            ("top_right", "Top Right"),
                            ("bottom_left", "Bottom Left"),
                            ("bottom_right", "Bottom Right"),
                            ("center", "Center"),
                            ("tiled", "Tiled"),
                        ],
                        default="bottom_right",
                        max_length=20,
                    ),
                ),
                (
                    "visible_opacity",
                    models.DecimalField(decimal_places=2, default=0.7, max_digits=3),
                ),
                ("visible_font_size", models.IntegerField(default=14)),
                ("visible_color", models.CharField(default="#FFFFFF", max_length=20)),
                ("watermarked_file_url", models.TextField(blank=True, null=True)),
                ("invisible_enabled", models.BooleanField(default=True)),
                ("invisible_payload", models.JSONField(blank=True, default=dict)),
                (
                    "invisible_method",
                    models.CharField(default="steganography", max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("applied", "Applied"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watermarks",
                        to="lipaidox_content.content",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watermarks",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watermarks",
                        to="lipaidox_content.contentmedia",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "content_watermarks",
            },
        ),
        migrations.CreateModel(
            name="ContentScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recency_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "engagement_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "purchase_rate_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "creator_tier_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "velocity_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "overall_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                ("score_rank", models.IntegerField(default=0)),
                (
                    "trending_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                ("is_trending", models.BooleanField(default=False)),
                ("trend_position", models.IntegerField(default=0)),
                (
                    "category_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                ("category_rank", models.IntegerField(default=0)),
                (
                    "quality_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "ai_authenticity_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                ("last_calculated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="lipaidox_content.content",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_scores",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "content_scores",
            },
        ),
        migrations.CreateModel(
            name="ContentAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_date", models.DateField()),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("view_count", models.IntegerField(default=0)),
                ("unique_view_count", models.IntegerField(default=0)),
                ("average_watch_duration_s", models.IntegerField(default=0)),
                (
                    "completion_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                ("like_count", models.IntegerField(default=0)),
                ("comment_count", models.IntegerField(default=0)),
                ("share_count", models.IntegerField(default=0)),
                ("save_count", models.IntegerField(default=0)),
                (
                    "engagement_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                ("ppv_purchases", models.IntegerField(default=0)),
                (
                    "ppv_revenue",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("tip_count", models.IntegerField(default=0)),
                (
                    "tip_revenue",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("subscriber_views", models.IntegerField(default=0)),
                ("non_subscriber_views", models.IntegerField(default=0)),
                ("new_subscribers_from_content", models.IntegerField(default=0)),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="lipaidox_content.content",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_analytics",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "content_analytics",
            },
        ),
        migrations.CreateModel(
            name="AIScanQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("fingerprint", "Fingerprint"),
                            ("duplicate_check", "Duplicate Check"),
                            ("watermark", "Watermark"),
                            ("reverse_search", "Reverse Search"),
                            ("price_benchmark", "Price Benchmark"),
                            ("full_pipeline", "Full Pipeline"),
                        ],
                        default="full_pipeline",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                            ("dead", "Dead"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("priority", models.IntegerField(default=5)),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=3)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_queue_jobs",
                        to="lipaidox_content.content",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_queue_jobs",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_queue_jobs",
                        to="lipaidox_content.contentmedia",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "ai_scan_queue",
                "ordering": ["-priority", "queued_at"],
            },
        ),
        migrations.CreateModel(
            name="AIMediaIntelligence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fingerprint_method",
                    models.CharField(
                        choices=[
                            ("sha256", "SHA-256"),
                            ("phash", "pHash"),
                            ("dhash", "dHash"),
                            ("combined", "Combined"),
                        ],
                        default="combined",
                        max_length=20,
                    ),
                ),
                ("sha256_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("phash_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("dhash_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("combined_fingerprint", models.TextField(blank=True, null=True)),
                (
                    "fingerprint_generated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("is_duplicate", models.BooleanField(default=False)),
                (
                    "duplicate_similarity_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "duplicate_action",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("flagged", "Flagged"),
                            ("blocked", "Blocked"),
                            ("warning_issued", "Warning Issued"),
                            ("admin_review", "Admin Review"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("duplicate_detected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reverse_scan_status",
                    models.CharField(
                        choices=[
                            ("not_scanned", "Not Scanned"),
                            ("scanning", "Scanning"),
                            ("clean", "Clean"),
                            ("matches_found", "Matches Found"),
                            ("failed", "Failed"),
                        ],
                        default="not_scanned",
                        max_length=20,
                    ),
                ),
                ("reverse_scan_matches_count", models.IntegerField(default=0)),
                ("reverse_scan_results", models.JSONField(blank=True, default=dict)),
                ("reverse_scanned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "authenticity_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("authenticity_note", models.TextField(blank=True, null=True)),
                (
                    "price_benchmark_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price_benchmark_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price_benchmark_avg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price_benchmark_currency",
                    models.CharField(default="USD", max_length=10),
                ),
                ("price_benchmarked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("scan_started_at", models.DateTimeField(blank=True, null=True)),
                ("scan_completed_at", models.DateTimeField(blank=True, null=True)),
                ("scan_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_intelligence",
                        to="lipaidox_content.content",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_intelligence",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "duplicate_of_content",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="lipaidox_content.content",
                    ),
                ),
                (
                    "duplicate_of_media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="lipaidox_content.contentmedia",
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_intelligence",
                        to="lipaidox_content.contentmedia",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "ai_media_intelligence",
            },
        ),
        migrations.CreateModel(
            name="SuggestedCreator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category_match_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "popularity_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "compatibility_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "growth_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "suggestion_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                ("suggestion_rank", models.IntegerField(default=0)),
                ("suggestion_reasons", models.JSONField(blank=True, default=list)),
                ("matching_categories", models.JSONField(blank=True, default=list)),
                ("shown_at", models.DateTimeField(blank=True, null=True)),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                ("followed_at", models.DateTimeField(blank=True, null=True)),
                ("subscribed_at", models.DateTimeField(blank=True, null=True)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("user_feedback", models.IntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "suggested_creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_to_users",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_creators",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "suggested_creators",
                "indexes": [
                    models.Index(fields=["user"], name="idx_suggested_creators_user"),
                    models.Index(
                        fields=["suggested_creator"],
                        name="idx_suggested_creators_creator",
                    ),
                    models.Index(
                        fields=["-suggestion_score"],
                        name="idx_suggested_creators_score",
                    ),
                    models.Index(
                        fields=["suggestion_rank"], name="idx_suggested_creators_rank"
                    ),
                    models.Index(
                        fields=["generated_at"], name="idx_suggested_creators_gen"
                    ),
                    models.Index(
                        fields=["expires_at"], name="idx_suggested_creators_expires"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="suggestedcreator",
            constraint=models.UniqueConstraint(
                fields=("user", "suggested_creator"), name="suggested_creators_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="suggestedcreator",
            constraint=models.CheckConstraint(
                check=models.Q(("suggestion_score__range", (0, 1))),
                name="suggestion_score_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="suggestedcreator",
            constraint=models.CheckConstraint(
                check=models.Q(("user_feedback__range", (-1, 1))),
                name="creator_feedback_check",
            ),
        ),
        migrations.AddIndex(
            model_name="platformanalytics",
            index=models.Index(
                fields=["period_date"], name="idx_platform_analytics_date"
            ),
        ),
        migrations.AddIndex(
            model_name="platformanalytics",
            index=models.Index(
                fields=["period_type"], name="idx_platform_analytics_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="platformanalytics",
            constraint=models.UniqueConstraint(
                fields=("period_date", "period_type"), name="platform_analytics_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="feedrecommendation",
            index=models.Index(fields=["user"], name="idx_feed_recommendations_user"),
        ),
        migrations.AddIndex(
            model_name="feedrecommendation",
            index=models.Index(fields=["content"], name="idx_feed_rec_content"),
        ),
        migrations.AddIndex(
            model_name="feedrecommendation",
            index=models.Index(
                fields=["-recommendation_score"], name="idx_feed_rec_score"
            ),
        ),
        migrations.AddIndex(
            model_name="feedrecommendation",
            index=models.Index(fields=["feed_position"], name="idx_feed_rec_position"),
        ),
        migrations.AddIndex(
            model_name="feedrecommendation",
            index=models.Index(fields=["generated_at"], name="idx_feed_rec_generated"),
        ),
        migrations.AddIndex(
            model_name="feedrecommendation",
            index=models.Index(fields=["expires_at"], name="idx_feed_rec_expires"),
        ),
        migrations.AddConstraint(
            model_name="feedrecommendation",
            constraint=models.UniqueConstraint(
                fields=("user", "content"), name="feed_recommendations_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="feedrecommendation",
            constraint=models.CheckConstraint(
                check=models.Q(("recommendation_score__range", (0, 1))),
                name="recommendation_score_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedrecommendation",
            constraint=models.CheckConstraint(
                check=models.Q(("user_feedback__range", (-1, 1))),
                name="user_feedback_check",
            ),
        ),
        migrations.AddIndex(
            model_name="creatoranalytics",
            index=models.Index(
                fields=["creator"], name="idx_creator_analytics_creator"
            ),
        ),
        migrations.AddIndex(
            model_name="creatoranalytics",
            index=models.Index(
                fields=["period_date"], name="idx_creator_analytics_date"
            ),
        ),
        migrations.AddIndex(
            model_name="creatoranalytics",
            index=models.Index(
                fields=["period_type"], name="idx_creator_analytics_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="creatoranalytics",
            constraint=models.UniqueConstraint(
                fields=("creator", "period_date", "period_type"),
                name="creator_analytics_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="creatoranalytics",
            constraint=models.CheckConstraint(
                check=models.Q(("follower_count__gte", 0)),
                name="creator_follower_count_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="creatoranalytics",
            constraint=models.CheckConstraint(
                check=models.Q(("subscriber_count__gte", 0)),
                name="subscriber_count_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="creatoranalytics",
            constraint=models.CheckConstraint(
                check=models.Q(("total_revenue__gte", 0)), name="revenue_check"
            ),
        ),
        migrations.AddConstraint(
            model_name="creatoranalytics",
            constraint=models.CheckConstraint(
                check=models.Q(("net_revenue__gte", 0)), name="net_revenue_check"
            ),
        ),
        migrations.AddIndex(
            model_name="contentwatermark",
            index=models.Index(fields=["content"], name="idx_watermarks_content"),
        ),
        migrations.AddIndex(
            model_name="contentwatermark",
            index=models.Index(fields=["creator"], name="idx_watermarks_creator"),
        ),
        migrations.AddIndex(
            model_name="contentwatermark",
            index=models.Index(fields=["status"], name="idx_watermarks_status"),
        ),
        migrations.AddConstraint(
            model_name="contentwatermark",
            constraint=models.UniqueConstraint(
                fields=("media",), name="content_watermarks_media_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentwatermark",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("visible_opacity__isnull", True),
                    models.Q(("visible_opacity__gte", 0), ("visible_opacity__lte", 1)),
                    _connector="OR",
                ),
                name="opacity_check",
            ),
        ),
        migrations.AddIndex(
            model_name="contentscore",
            index=models.Index(fields=["content"], name="idx_content_scores_content"),
        ),
        migrations.AddIndex(
            model_name="contentscore",
            index=models.Index(fields=["creator"], name="idx_content_scores_creator"),
        ),
        migrations.AddIndex(
            model_name="contentscore",
            index=models.Index(
                fields=["-overall_score"], name="idx_content_scores_overall"
            ),
        ),
        migrations.AddIndex(
            model_name="contentscore",
            index=models.Index(
                fields=["-trending_score"], name="idx_content_scores_trending"
            ),
        ),
        migrations.AddIndex(
            model_name="contentscore",
            index=models.Index(
                fields=["is_trending"], name="idx_content_scores_is_trending"
            ),
        ),
        migrations.AddIndex(
            model_name="contentscore",
            index=models.Index(
                fields=["last_calculated_at"], name="idx_content_scores_calculated"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentscore",
            constraint=models.UniqueConstraint(
                fields=("content",), name="content_scores_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentscore",
            constraint=models.CheckConstraint(
                check=models.Q(("overall_score__range", (0, 1))),
                name="overall_score_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentscore",
            constraint=models.CheckConstraint(
                check=models.Q(("trending_score__range", (0, 1))),
                name="trending_score_check",
            ),
        ),
        migrations.AddIndex(
            model_name="contentanalytics",
            index=models.Index(
                fields=["content"], name="idx_content_analytics_content"
            ),
        ),
        migrations.AddIndex(
            model_name="contentanalytics",
            index=models.Index(
                fields=["creator"], name="idx_content_analytics_creator"
            ),
        ),
        migrations.AddIndex(
            model_name="contentanalytics",
            index=models.Index(
                fields=["period_date"], name="idx_content_analytics_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentanalytics",
            constraint=models.UniqueConstraint(
                fields=("content", "period_date", "period_type"),
                name="content_analytics_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentanalytics",
            constraint=models.CheckConstraint(
                check=models.Q(("view_count__gte", 0)), name="view_count_check"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentanalytics",
            constraint=models.CheckConstraint(
                check=models.Q(("engagement_rate__range", (0, 1))),
                name="engagement_rate_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentanalytics",
            constraint=models.CheckConstraint(
                check=models.Q(("completion_rate__range", (0, 1))),
                name="completion_rate_check",
            ),
        ),
        migrations.AddIndex(
            model_name="aiscanqueue",
            index=models.Index(fields=["status"], name="idx_ai_scan_queue_status"),
        ),
        migrations.AddIndex(
            model_name="aiscanqueue",
            index=models.Index(fields=["job_type"], name="idx_ai_scan_queue_job_type"),
        ),
        migrations.AddIndex(
            model_name="aiscanqueue",
            index=models.Index(fields=["-priority"], name="idx_ai_scan_queue_priority"),
        ),
        migrations.AddIndex(
            model_name="aiscanqueue",
            index=models.Index(
                fields=["queued_at"], name="idx_ai_scan_queue_queued_at"
            ),
        ),
        migrations.AddIndex(
            model_name="aiscanqueue",
            index=models.Index(
                fields=["next_retry_at"], name="idx_ai_scan_queue_next_retry"
            ),
        ),
        migrations.AddConstraint(
            model_name="aiscanqueue",
            constraint=models.CheckConstraint(
                check=models.Q(("priority__range", (1, 10))), name="priority_check"
            ),
        ),
        migrations.AddConstraint(
            model_name="aiscanqueue",
            constraint=models.CheckConstraint(
                check=models.Q(("attempts__gte", 0)), name="attempts_check"
            ),
        ),
        migrations.AddIndex(
            model_name="aimediaintelligence",
            index=models.Index(fields=["content"], name="idx_ai_intelligence_content"),
        ),
        migrations.AddIndex(
            model_name="aimediaintelligence",
            index=models.Index(fields=["creator"], name="idx_ai_intelligence_creator"),
        ),
        migrations.AddIndex(
            model_name="aimediaintelligence",
            index=models.Index(
                fields=["sha256_hash"], name="idx_ai_intelligence_sha256"
            ),
        ),
        migrations.AddIndex(
            model_name="aimediaintelligence",
            index=models.Index(fields=["phash_hash"], name="idx_ai_intelligence_phash"),
        ),
        migrations.AddIndex(
            model_name="aimediaintelligence",
            index=models.Index(fields=["dhash_hash"], name="idx_ai_intelligence_dhash"),
        ),
        migrations.AddIndex(
            model_name="aimediaintelligence",
            index=models.Index(fields=["is_duplicate"], name="idx_ai_intel_duplicate"),
        ),
        migrations.AddIndex(
            model_name="aimediaintelligence",
            index=models.Index(fields=["scan_status"], name="idx_ai_intel_scan_status"),
        ),
        migrations.AddIndex(
            model_name="aimediaintelligence",
            index=models.Index(
                fields=["duplicate_action"], name="idx_ai_intel_dup_action"
            ),
        ),
        migrations.AddConstraint(
            model_name="aimediaintelligence",
            constraint=models.UniqueConstraint(
                fields=("media",), name="ai_media_intelligence_media_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="aimediaintelligence",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("duplicate_similarity_score__isnull", True),
                    models.Q(
                        ("duplicate_similarity_score__gte", 0),
                        ("duplicate_similarity_score__lte", 1),
                    ),
                    _connector="OR",
                ),
                name="similarity_score_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="aimediaintelligence",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("authenticity_score__isnull", True),
                    models.Q(
                        ("authenticity_score__gte", 0), ("authenticity_score__lte", 1)
                    ),
                    _connector="OR",
                ),
                name="authenticity_score_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="aimediaintelligence",
            constraint=models.CheckConstraint(
                check=models.Q(("reverse_scan_matches_count__gte", 0)),
                name="reverse_scan_matches_check",
            ),
        ),
    ]
