# Generated by Django 4.2.7 on 2026-03-30 08:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("lipaidox", "0001_initial"),
        ("lipaidox_creator_profile", "0004_usernamehistory_and_more"),
        ("lipaidox_ai_intelligence", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIFingerprintRegistry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sha256_hash", models.CharField(max_length=64, unique=True)),
                ("phash_hash", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "original_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "original_creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_fingerprints",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "ai_fingerprint_registry",
                "indexes": [
                    models.Index(
                        fields=["sha256_hash"], name="ai_fingerpr_sha256__fae1a5_idx"
                    ),
                    models.Index(
                        fields=["phash_hash"], name="ai_fingerpr_phash_h_2add5a_idx"
                    ),
                ],
            },
        ),
    ]
