# Generated by Django 4.2.7 on 2026-03-27 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lipaidox_creator_profile", "0004_usernamehistory_and_more"),
        (
            "lipaidox_content",
            "0004_remove_contentreport_unique_pending_report_per_user_content_and_more",
        ),
        ("lipaidox", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("like", "Like"),
                            ("unlike", "Unlike"),
                            ("comment", "Comment"),
                            ("share", "Share"),
                            ("save", "Save"),
                            ("purchase", "Purchase"),
                            ("subscribe", "Subscribe"),
                            ("unsubscribe", "Unsubscribe"),
                            ("follow", "Follow"),
                            ("unfollow", "Unfollow"),
                            ("tip", "Tip"),
                            ("skip", "Skip"),
                            ("report", "Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("watch_duration_s", models.IntegerField(blank=True, null=True)),
                (
                    "completion_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("feed", "Feed"),
                            ("explore", "Explore"),
                            ("search", "Search"),
                            ("recommendation", "Recommendation"),
                            ("profile", "Profile"),
                            ("trending", "Trending"),
                            ("direct_link", "Direct Link"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("device_type", models.CharField(blank=True, max_length=50, null=True)),
                ("session_id", models.CharField(blank=True, max_length=255, null=True)),
                ("interacted_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="lipaidox_content.content",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_interactions",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_rec_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_interactions",
            },
        ),
        migrations.CreateModel(
            name="TrendingContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trending_score",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
                ),
                ("rank_position", models.IntegerField()),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "audience_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("adult", "Adult"),
                            ("teen", "Teen"),
                            ("mature", "Mature"),
                            ("family", "Family"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("trend_window_hours", models.IntegerField(default=24)),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trending_entries",
                        to="lipaidox_content.content",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trending_content",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_rec_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "trending_content",
            },
        ),
        migrations.CreateModel(
            name="SuggestedCreator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "suggestion_score",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
                ),
                ("rank_position", models.IntegerField()),
                (
                    "suggestion_reason",
                    models.CharField(
                        choices=[
                            ("matching_category", "Matching Category"),
                            ("similar_to_followed", "Similar to Followed"),
                            ("trending_creator", "Trending Creator"),
                            ("new_verified_creator", "New Verified Creator"),
                            ("platform_featured", "Platform Featured"),
                            ("purchased_content_before", "Purchased Content Before"),
                        ],
                        max_length=100,
                    ),
                ),
                ("is_seen", models.BooleanField(default=False)),
                ("is_followed", models.BooleanField(default=False)),
                ("valid_until", models.DateTimeField()),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_suggested_to_users",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_rec_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_suggested_creators",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recommendation_suggested_creators",
            },
        ),
        migrations.CreateModel(
            name="FeedRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recommendation_score",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
                ),
                (
                    "recommendation_reason",
                    models.CharField(
                        choices=[
                            ("followed_creator", "Followed Creator"),
                            ("subscribed_creator", "Subscribed Creator"),
                            ("matching_category", "Matching Category"),
                            ("trending", "Trending"),
                            ("similar_content", "Similar Content"),
                            ("new_creator_discovery", "New Creator Discovery"),
                            ("purchased_before", "Purchased Before"),
                            ("platform_featured", "Platform Featured"),
                        ],
                        max_length=100,
                    ),
                ),
                ("position", models.IntegerField()),
                ("is_seen", models.BooleanField(default=False)),
                ("is_interacted", models.BooleanField(default=False)),
                ("seen_at", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField()),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_user_feed_recommendations",
                        to="lipaidox_content.content",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_user_feed_recommendations",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_rec_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_feed_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recommendation_feed_recommendations",
            },
        ),
        migrations.CreateModel(
            name="ContentScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recency_score",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
                ),
                (
                    "engagement_score",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
                ),
                (
                    "purchase_score",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
                ),
                (
                    "creator_tier_score",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
                ),
                (
                    "velocity_score",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
                ),
                (
                    "total_score",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
                ),
                ("view_count", models.IntegerField(default=0)),
                ("like_count", models.IntegerField(default=0)),
                ("comment_count", models.IntegerField(default=0)),
                ("share_count", models.IntegerField(default=0)),
                ("purchase_count", models.IntegerField(default=0)),
                (
                    "engagement_rate",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
                ),
                (
                    "primary_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "audience_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("adult", "Adult"),
                            ("teen", "Teen"),
                            ("mature", "Mature"),
                            ("family", "Family"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("last_computed_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_scores",
                        to="lipaidox_content.content",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_content_scores",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_rec_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "recommendation_content_scores",
            },
        ),
        migrations.CreateModel(
            name="UserInterestProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("category_weights", models.JSONField(default=dict)),
                ("preferred_content_formats", models.TextField(default="[]")),
                ("preferred_access_types", models.TextField(default="[]")),
                (
                    "avg_watch_completion_rate",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
                ),
                (
                    "purchase_propensity_score",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
                ),
                (
                    "tip_propensity_score",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
                ),
                ("total_interactions", models.IntegerField(default=0)),
                ("last_active_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile_confidence_score",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
                ),
                ("last_computed_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_rec_instances",
                        to="lipaidox.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interest_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_interest_profiles",
                "indexes": [
                    models.Index(
                        fields=["user"], name="idx_user_interest_profiles_usr"
                    ),
                    models.Index(
                        fields=["last_active_at"], name="idx_user_interest_profiles_lst"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="userinterestprofile",
            constraint=models.UniqueConstraint(
                fields=("user",), name="user_interest_profiles_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="userinterestprofile",
            constraint=models.CheckConstraint(
                check=models.Q(("purchase_propensity_score__range", (0, 1))),
                name="purchase_propensity_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="userinterestprofile",
            constraint=models.CheckConstraint(
                check=models.Q(("profile_confidence_score__range", (0, 1))),
                name="confidence_score_check",
            ),
        ),
        migrations.AddIndex(
            model_name="userinteraction",
            index=models.Index(fields=["user"], name="idx_user_interactions_user"),
        ),
        migrations.AddIndex(
            model_name="userinteraction",
            index=models.Index(
                fields=["content"], name="idx_user_interactions_content"
            ),
        ),
        migrations.AddIndex(
            model_name="userinteraction",
            index=models.Index(
                fields=["creator"], name="idx_user_interactions_creator"
            ),
        ),
        migrations.AddIndex(
            model_name="userinteraction",
            index=models.Index(
                fields=["interaction_type"], name="idx_user_interactions_type"
            ),
        ),
        migrations.AddIndex(
            model_name="userinteraction",
            index=models.Index(
                fields=["interacted_at"], name="idx_user_interactions_interact"
            ),
        ),
        migrations.AddIndex(
            model_name="userinteraction",
            index=models.Index(fields=["source"], name="idx_user_interactions_source"),
        ),
        migrations.AddConstraint(
            model_name="userinteraction",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("watch_duration_s__isnull", True),
                    ("watch_duration_s__gte", 0),
                    _connector="OR",
                ),
                name="watch_duration_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="userinteraction",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("completion_rate__isnull", True),
                    models.Q(("completion_rate__gte", 0), ("completion_rate__lte", 1)),
                    _connector="OR",
                ),
                name="recommendation_completion_rate_check",
            ),
        ),
        migrations.AddIndex(
            model_name="trendingcontent",
            index=models.Index(
                fields=["rank_position"], name="idx_trending_content_rank"
            ),
        ),
        migrations.AddIndex(
            model_name="trendingcontent",
            index=models.Index(
                fields=["category"], name="idx_trending_content_category"
            ),
        ),
        migrations.AddIndex(
            model_name="trendingcontent",
            index=models.Index(
                fields=["audience_type"], name="idx_trending_content_audience"
            ),
        ),
        migrations.AddIndex(
            model_name="trendingcontent",
            index=models.Index(
                fields=["expires_at"], name="idx_trending_content_expires"
            ),
        ),
        migrations.AddConstraint(
            model_name="trendingcontent",
            constraint=models.UniqueConstraint(
                fields=("content", "trend_window_hours"), name="trending_content_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="trendingcontent",
            constraint=models.CheckConstraint(
                check=models.Q(("rank_position__gte", 1)), name="rank_position_check"
            ),
        ),
        migrations.AddConstraint(
            model_name="trendingcontent",
            constraint=models.CheckConstraint(
                check=models.Q(("trending_score__gte", 0)),
                name="recommendation_trending_score_check",
            ),
        ),
        migrations.AddIndex(
            model_name="suggestedcreator",
            index=models.Index(fields=["user"], name="idx_rec_suggested_creators_usr"),
        ),
        migrations.AddIndex(
            model_name="suggestedcreator",
            index=models.Index(
                fields=["creator"], name="idx_rec_suggested_creators_cre"
            ),
        ),
        migrations.AddIndex(
            model_name="suggestedcreator",
            index=models.Index(
                fields=["user", "rank_position"], name="idx_rec_suggested_creators_rnk"
            ),
        ),
        migrations.AddIndex(
            model_name="suggestedcreator",
            index=models.Index(
                fields=["valid_until"], name="idx_suggested_creators_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="suggestedcreator",
            constraint=models.UniqueConstraint(
                fields=("user", "creator"),
                name="recommendation_suggested_creators_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="suggestedcreator",
            constraint=models.CheckConstraint(
                check=models.Q(("rank_position__gte", 1)), name="rank_check"
            ),
        ),
        migrations.AddConstraint(
            model_name="suggestedcreator",
            constraint=models.CheckConstraint(
                check=models.Q(("suggestion_score__gte", 0)),
                name="recommendation_suggestion_score_check",
            ),
        ),
        migrations.AddIndex(
            model_name="feedrecommendation",
            index=models.Index(fields=["user"], name="idx_feed_recs_user"),
        ),
        migrations.AddIndex(
            model_name="feedrecommendation",
            index=models.Index(fields=["content"], name="idx_feed_recs_content"),
        ),
        migrations.AddIndex(
            model_name="feedrecommendation",
            index=models.Index(
                fields=["-recommendation_score"], name="idx_feed_recs_score"
            ),
        ),
        migrations.AddIndex(
            model_name="feedrecommendation",
            index=models.Index(
                fields=["user", "position"], name="idx_feed_recs_position"
            ),
        ),
        migrations.AddIndex(
            model_name="feedrecommendation",
            index=models.Index(
                fields=["valid_until"], name="idx_feed_recs_valid_until"
            ),
        ),
        migrations.AddIndex(
            model_name="feedrecommendation",
            index=models.Index(fields=["is_seen"], name="idx_feed_recs_is_seen"),
        ),
        migrations.AddConstraint(
            model_name="feedrecommendation",
            constraint=models.UniqueConstraint(
                fields=("user", "content"),
                name="recommendation_feed_recommendations_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedrecommendation",
            constraint=models.CheckConstraint(
                check=models.Q(("position__gte", 1)), name="position_check"
            ),
        ),
        migrations.AddConstraint(
            model_name="feedrecommendation",
            constraint=models.CheckConstraint(
                check=models.Q(("recommendation_score__gte", 0)),
                name="recommendation_feed_score_check",
            ),
        ),
        migrations.AddIndex(
            model_name="contentscore",
            index=models.Index(
                fields=["content"], name="idx_rec_content_scores_content"
            ),
        ),
        migrations.AddIndex(
            model_name="contentscore",
            index=models.Index(
                fields=["creator"], name="idx_rec_content_scores_creator"
            ),
        ),
        migrations.AddIndex(
            model_name="contentscore",
            index=models.Index(
                fields=["-total_score"], name="idx_content_scores_total_score"
            ),
        ),
        migrations.AddIndex(
            model_name="contentscore",
            index=models.Index(
                fields=["primary_category"], name="idx_content_scores_category"
            ),
        ),
        migrations.AddIndex(
            model_name="contentscore",
            index=models.Index(
                fields=["audience_type"], name="idx_content_scores_audience"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentscore",
            constraint=models.UniqueConstraint(
                fields=("content",), name="recommendation_content_scores_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentscore",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("recency_score__gte", 0),
                    ("engagement_score__gte", 0),
                    ("total_score__gte", 0),
                ),
                name="scores_check",
            ),
        ),
    ]
