# Generated by Django 4.2.7 on 2026-03-30 09:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("lipaidox_content", "0006_contentappeal"),
        ("lipaidox_creator_profile", "0005_creatorprofile_content_blocks_count"),
        ("lipaidox", "0001_initial"),
        ("lipaidox_recommendation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedrecommendation",
            name="is_ad",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="PromotedContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2, help_text="Total budget paid", max_digits=12
                    ),
                ),
                (
                    "spent",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "target_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("impressions", models.IntegerField(default=0)),
                ("clicks", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="lipaidox_content.content",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promoted_campaigns",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_rec_instances",
                        to="lipaidox.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "recommendation_promoted_content",
            },
        ),
        migrations.AddField(
            model_name="feedrecommendation",
            name="ad_campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feed_impressions",
                to="lipaidox_recommendation.promotedcontent",
            ),
        ),
        migrations.AddIndex(
            model_name="promotedcontent",
            index=models.Index(fields=["status"], name="recommendat_status_2d08f8_idx"),
        ),
        migrations.AddIndex(
            model_name="promotedcontent",
            index=models.Index(
                fields=["end_date"], name="recommendat_end_dat_386df7_idx"
            ),
        ),
    ]
