# Generated by Django 4.2.7 on 2026-03-23 11:40

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lipaidox_creator_profile", "0002_remove_creatorprofile_display_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "platform_categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ContentClassification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("primary_category", models.CharField(max_length=100)),
                (
                    "secondary_categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "audience_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("adult", "Adult"),
                            ("educational", "Educational"),
                            ("fitness", "Fitness"),
                            ("gaming", "Gaming"),
                            ("music", "Music"),
                            ("travel", "Travel"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("content_language", models.CharField(default="en", max_length=50)),
                ("has_images", models.BooleanField(default=False)),
                ("has_videos", models.BooleanField(default=False)),
                ("has_audio", models.BooleanField(default=False)),
                ("has_live_streams", models.BooleanField(default=False)),
                ("has_blog", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classification",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "content_classifications",
            },
        ),
    ]
