# Generated by Django 4.2.7 on 2026-03-26 22:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lipaidox_cc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentclassification",
            name="target_age_gap",
            field=models.CharField(
                choices=[
                    ("teens", "13-17"),
                    ("young_adults", "18-24"),
                    ("adults", "25-34"),
                    ("middle_aged", "35-49"),
                    ("mature", "50-64"),
                    ("seniors", "65+"),
                    ("all_ages", "All Ages"),
                ],
                default="all_ages",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contentclassification",
            name="target_country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="contentclassification",
            name="target_gender",
            field=models.CharField(
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("non_binary", "Non-Binary"),
                    ("prefer_not_to_say", "Prefer not to say"),
                    ("all", "All Genders"),
                ],
                default="all",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contentclassification",
            name="target_interests",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("technology", "Technology"),
                        ("sports", "Sports"),
                        ("arts", "Arts & Culture"),
                        ("fashion", "Fashion"),
                        ("food", "Food & Cooking"),
                        ("photography", "Photography"),
                        ("reading", "Reading"),
                        ("movies", "Movies & TV"),
                        ("outdoors", "Outdoors"),
                        ("pets", "Pets & Animals"),
                        ("business", "Business"),
                        ("science", "Science"),
                        ("politics", "Politics"),
                        ("diy", "DIY & Crafts"),
                        ("collecting", "Collecting"),
                        ("gaming", "Gaming"),
                        ("social", "Social Media"),
                        ("music", "Music"),
                        ("health", "Health & Wellness"),
                        ("travel", "Travel"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="contentclassification",
            name="target_professionalism",
            field=models.CharField(
                choices=[
                    ("casual", "Casual"),
                    ("semi_professional", "Semi-Professional"),
                    ("professional", "Professional"),
                    ("expert", "Expert/Industry Leader"),
                    ("all_levels", "All Levels"),
                ],
                default="all_levels",
                max_length=25,
            ),
        ),
    ]
