# Generated by Django 4.2.7 on 2026-03-27 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lipaidox_payment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lipaidox_creator_profile", "0004_usernamehistory_and_more"),
        ("lipaidox_admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreatorCreditLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("admin_gift", "Admin Gift"),
                            ("monthly_allocation", "Monthly Allocation"),
                            ("spent", "Spent"),
                            ("expired", "Expired"),
                            ("refunded", "Refunded"),
                            ("converted", "Converted"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=30,
                    ),
                ),
                ("credits_delta", models.IntegerField()),
                ("credits_before", models.IntegerField()),
                ("credits_after", models.IntegerField()),
                ("live_stream_id", models.UUIDField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_expired", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "creator_credit_ledger",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CreatorCreditWallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("purchased_credits", models.IntegerField(default=0)),
                ("free_monthly_credits", models.IntegerField(default=0)),
                ("gifted_credits", models.IntegerField(default=0)),
                ("total_credits_used", models.IntegerField(default=0)),
                ("total_credits_purchased", models.IntegerField(default=0)),
                ("total_credits_gifted", models.IntegerField(default=0)),
                ("monthly_credits_allocated", models.IntegerField(default=0)),
                ("monthly_reset_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "creator_credit_wallets",
            },
        ),
        migrations.CreateModel(
            name="CreditConversionRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "credit_type",
                    models.CharField(
                        choices=[
                            ("creator_credit", "Creator Credit"),
                            ("fan_credit", "Fan Credit"),
                        ],
                        default="fan_credit",
                        max_length=20,
                    ),
                ),
                ("credits_per_unit", models.IntegerField()),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "monetary_value",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "platform_fee_percent",
                    models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("effective_from", models.DateTimeField(auto_now_add=True)),
                ("effective_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "credit_conversion_rates",
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="CreditGift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "credit_type",
                    models.CharField(
                        choices=[
                            ("creator_credit", "Creator Credit"),
                            ("fan_credit", "Fan Credit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("credits_amount", models.IntegerField()),
                ("reason", models.TextField()),
                ("internal_note", models.TextField(blank=True, null=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("gifted_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "credit_gifts",
                "ordering": ["-gifted_at"],
            },
        ),
        migrations.CreateModel(
            name="CreditPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "credit_type",
                    models.CharField(
                        choices=[
                            ("creator_credit", "Creator Credit"),
                            ("fan_credit", "Fan Credit"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("creator", "Creator"),
                            ("fan", "Fan"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=10,
                    ),
                ),
                ("credit_amount", models.IntegerField()),
                ("price_usd", models.DecimalField(decimal_places=2, max_digits=10)),
                ("bonus_credits", models.IntegerField(default=0)),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("badge_label", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "credit_packages",
                "ordering": ["credit_type", "sort_order", "price_usd"],
            },
        ),
        migrations.CreateModel(
            name="CreditPurchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "credit_type",
                    models.CharField(
                        choices=[
                            ("creator_credit", "Creator Credit"),
                            ("fan_credit", "Fan Credit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("credits_purchased", models.IntegerField()),
                ("bonus_credits", models.IntegerField(default=0)),
                ("total_credits", models.IntegerField()),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("reversed", "Reversed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gateway_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="lipaidox_credits.creditpackage",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lipaidox_payment.paymentmethod",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "credit_purchases",
                "ordering": ["-purchased_at"],
            },
        ),
        migrations.CreateModel(
            name="FanCreditGiftSent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("live_stream_id", models.UUIDField()),
                ("credits_sent", models.IntegerField()),
                (
                    "animation_type",
                    models.CharField(
                        choices=[
                            ("heart", "Heart"),
                            ("star", "Star"),
                            ("fire", "Fire"),
                            ("crown", "Crown"),
                            ("diamond", "Diamond"),
                            ("rocket", "Rocket"),
                            ("confetti", "Confetti"),
                        ],
                        default="heart",
                        max_length=20,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=255, null=True)),
                ("is_anonymous", models.BooleanField(default=False)),
                (
                    "monetary_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "platform_fee",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "creator_earnings",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("reversed", "Reversed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("creator_wallet_credited", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversion_rate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lipaidox_credits.creditconversionrate",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gifts_received",
                        to="lipaidox_creator_profile.creatorprofile",
                    ),
                ),
                (
                    "creator_wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gifts_received",
                        to="lipaidox_credits.creatorcreditwallet",
                    ),
                ),
                (
                    "fan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gifts_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "fan_credit_gifts_sent",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="FanCreditWallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("purchased_credits", models.IntegerField(default=0)),
                ("gifted_credits", models.IntegerField(default=0)),
                ("total_credits_purchased", models.IntegerField(default=0)),
                ("total_credits_gifted_by_admin", models.IntegerField(default=0)),
                ("total_credits_sent", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fan_credit_wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "fan_credit_wallets",
            },
        ),
        migrations.CreateModel(
            name="FanCreditLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("admin_gift", "Admin Gift"),
                            ("monthly_allocation", "Monthly Allocation"),
                            ("spent", "Spent"),
                            ("expired", "Expired"),
                            ("refunded", "Refunded"),
                            ("converted", "Converted"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=30,
                    ),
                ),
                ("credits_delta", models.IntegerField()),
                ("credits_before", models.IntegerField()),
                ("credits_after", models.IntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fan_credit_ledger_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lipaidox_credits.creditgift",
                    ),
                ),
                (
                    "gift_sent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lipaidox_credits.fancreditgiftsent",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lipaidox_credits.creditpurchase",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="lipaidox_credits.fancreditwallet",
                    ),
                ),
            ],
            options={
                "db_table": "fan_credit_ledger",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="fancreditgiftsent",
            name="fan_wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gifts_sent",
                to="lipaidox_credits.fancreditwallet",
            ),
        ),
        migrations.AddIndex(
            model_name="creditpackage",
            index=models.Index(fields=["credit_type"], name="idx_pkg_type"),
        ),
        migrations.AddIndex(
            model_name="creditpackage",
            index=models.Index(fields=["target"], name="idx_pkg_target"),
        ),
        migrations.AddIndex(
            model_name="creditpackage",
            index=models.Index(fields=["is_active"], name="idx_pkg_is_active"),
        ),
        migrations.AddConstraint(
            model_name="creditpackage",
            constraint=models.CheckConstraint(
                check=models.Q(("credit_amount__gt", 0)), name="credit_amount_check"
            ),
        ),
        migrations.AddConstraint(
            model_name="creditpackage",
            constraint=models.CheckConstraint(
                check=models.Q(("price_usd__gt", 0)), name="price_check"
            ),
        ),
        migrations.AddConstraint(
            model_name="creditpackage",
            constraint=models.CheckConstraint(
                check=models.Q(("bonus_credits__gte", 0)), name="bonus_credits_check"
            ),
        ),
        migrations.AddConstraint(
            model_name="creditpackage",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("duration_minutes__isnull", True),
                    ("duration_minutes__gt", 0),
                    _connector="OR",
                ),
                name="duration_check",
            ),
        ),
        migrations.AddField(
            model_name="creditgift",
            name="gifted_by_admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credits_gifted",
                to="lipaidox_admin_panel.adminaccount",
            ),
        ),
        migrations.AddField(
            model_name="creditgift",
            name="gifted_to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_gifts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="creditconversionrate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lipaidox_admin_panel.adminaccount",
            ),
        ),
        migrations.AddField(
            model_name="creatorcreditwallet",
            name="creator",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_wallet",
                to="lipaidox_creator_profile.creatorprofile",
            ),
        ),
        migrations.AddField(
            model_name="creatorcreditledger",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_ledger_entries",
                to="lipaidox_creator_profile.creatorprofile",
            ),
        ),
        migrations.AddField(
            model_name="creatorcreditledger",
            name="gift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lipaidox_credits.creditgift",
            ),
        ),
        migrations.AddField(
            model_name="creatorcreditledger",
            name="purchase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lipaidox_credits.creditpurchase",
            ),
        ),
        migrations.AddField(
            model_name="creatorcreditledger",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_entries",
                to="lipaidox_credits.creatorcreditwallet",
            ),
        ),
        migrations.AddIndex(
            model_name="fancreditwallet",
            index=models.Index(fields=["fan"], name="idx_fan_wallet_fan"),
        ),
        migrations.AddConstraint(
            model_name="fancreditwallet",
            constraint=models.CheckConstraint(
                check=models.Q(("purchased_credits__gte", 0)),
                name="fan_purchased_credits_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="fancreditwallet",
            constraint=models.CheckConstraint(
                check=models.Q(("gifted_credits__gte", 0)),
                name="fan_gifted_credits_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="fancreditwallet",
            constraint=models.CheckConstraint(
                check=models.Q(("total_credits_sent__gte", 0)),
                name="fan_total_sent_check",
            ),
        ),
        migrations.AddIndex(
            model_name="fancreditledger",
            index=models.Index(fields=["fan"], name="idx_fan_ledger_fan"),
        ),
        migrations.AddIndex(
            model_name="fancreditledger",
            index=models.Index(fields=["wallet"], name="idx_fan_ledger_wallet"),
        ),
        migrations.AddIndex(
            model_name="fancreditledger",
            index=models.Index(fields=["transaction_type"], name="idx_fan_ledger_type"),
        ),
        migrations.AddIndex(
            model_name="fancreditledger",
            index=models.Index(fields=["created_at"], name="idx_fan_ledger_created"),
        ),
        migrations.AddConstraint(
            model_name="fancreditledger",
            constraint=models.CheckConstraint(
                check=models.Q(("credits_after__gte", 0)),
                name="fan_credits_after_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="fancreditledger",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "credits_after",
                        django.db.models.expressions.CombinedExpression(
                            models.F("credits_before"), "+", models.F("credits_delta")
                        ),
                    )
                ),
                name="fan_delta_consistency",
            ),
        ),
        migrations.AddIndex(
            model_name="fancreditgiftsent",
            index=models.Index(fields=["fan"], name="idx_fangifts_fan"),
        ),
        migrations.AddIndex(
            model_name="fancreditgiftsent",
            index=models.Index(fields=["creator"], name="idx_fangifts_creator"),
        ),
        migrations.AddIndex(
            model_name="fancreditgiftsent",
            index=models.Index(fields=["live_stream_id"], name="idx_fangifts_stream"),
        ),
        migrations.AddIndex(
            model_name="fancreditgiftsent",
            index=models.Index(fields=["status"], name="idx_fangifts_status"),
        ),
        migrations.AddIndex(
            model_name="fancreditgiftsent",
            index=models.Index(fields=["sent_at"], name="idx_fangifts_sent"),
        ),
        migrations.AddConstraint(
            model_name="fancreditgiftsent",
            constraint=models.CheckConstraint(
                check=models.Q(("credits_sent__gt", 0)), name="gift_sent_credits_check"
            ),
        ),
        migrations.AddConstraint(
            model_name="fancreditgiftsent",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("monetary_value__isnull", True),
                    ("monetary_value__gte", 0),
                    _connector="OR",
                ),
                name="gift_sent_monetary_value_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="fancreditgiftsent",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("creator_earnings__isnull", True),
                    ("creator_earnings__gte", 0),
                    _connector="OR",
                ),
                name="gift_sent_creator_earnings_check",
            ),
        ),
        migrations.AddIndex(
            model_name="creditpurchase",
            index=models.Index(fields=["user"], name="idx_purchases_user"),
        ),
        migrations.AddIndex(
            model_name="creditpurchase",
            index=models.Index(fields=["credit_type"], name="idx_purchases_type"),
        ),
        migrations.AddIndex(
            model_name="creditpurchase",
            index=models.Index(fields=["status"], name="idx_purchases_status"),
        ),
        migrations.AddIndex(
            model_name="creditpurchase",
            index=models.Index(fields=["purchased_at"], name="idx_purchases_at"),
        ),
        migrations.AddConstraint(
            model_name="creditpurchase",
            constraint=models.CheckConstraint(
                check=models.Q(("credits_purchased__gt", 0)),
                name="credits_purchased_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditpurchase",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "total_credits",
                        django.db.models.expressions.CombinedExpression(
                            models.F("credits_purchased"),
                            "+",
                            models.F("bonus_credits"),
                        ),
                    )
                ),
                name="total_credits_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditpurchase",
            constraint=models.CheckConstraint(
                check=models.Q(("amount_paid__gt", 0)), name="amount_paid_check"
            ),
        ),
        migrations.AddIndex(
            model_name="creditgift",
            index=models.Index(fields=["gifted_to_user"], name="idx_gifts_user"),
        ),
        migrations.AddIndex(
            model_name="creditgift",
            index=models.Index(fields=["gifted_by_admin"], name="idx_gifts_admin"),
        ),
        migrations.AddIndex(
            model_name="creditgift",
            index=models.Index(fields=["credit_type"], name="idx_gifts_type"),
        ),
        migrations.AddIndex(
            model_name="creditgift",
            index=models.Index(fields=["status"], name="idx_gifts_status"),
        ),
        migrations.AddConstraint(
            model_name="creditgift",
            constraint=models.CheckConstraint(
                check=models.Q(("credits_amount__gt", 0)), name="credits_amount_check"
            ),
        ),
        migrations.AddIndex(
            model_name="creditconversionrate",
            index=models.Index(fields=["credit_type"], name="idx_rate_type"),
        ),
        migrations.AddIndex(
            model_name="creditconversionrate",
            index=models.Index(fields=["is_active"], name="idx_rate_is_active"),
        ),
        migrations.AddConstraint(
            model_name="creditconversionrate",
            constraint=models.CheckConstraint(
                check=models.Q(("credits_per_unit__gt", 0)),
                name="rate_credits_per_unit_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditconversionrate",
            constraint=models.CheckConstraint(
                check=models.Q(("monetary_value__gt", 0)),
                name="rate_monetary_value_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditconversionrate",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("platform_fee_percent__gte", 0), ("platform_fee_percent__lte", 100)
                ),
                name="rate_platform_fee_check",
            ),
        ),
        migrations.AddIndex(
            model_name="creatorcreditwallet",
            index=models.Index(fields=["creator"], name="idx_creator_wallet_creator"),
        ),
        migrations.AddConstraint(
            model_name="creatorcreditwallet",
            constraint=models.CheckConstraint(
                check=models.Q(("purchased_credits__gte", 0)),
                name="purchased_credits_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="creatorcreditwallet",
            constraint=models.CheckConstraint(
                check=models.Q(("free_monthly_credits__gte", 0)),
                name="free_monthly_credits_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="creatorcreditwallet",
            constraint=models.CheckConstraint(
                check=models.Q(("gifted_credits__gte", 0)), name="gifted_credits_check"
            ),
        ),
        migrations.AddConstraint(
            model_name="creatorcreditwallet",
            constraint=models.CheckConstraint(
                check=models.Q(("total_credits_used__gte", 0)), name="total_used_check"
            ),
        ),
        migrations.AddIndex(
            model_name="creatorcreditledger",
            index=models.Index(fields=["creator"], name="idx_creator_ledger_creator"),
        ),
        migrations.AddIndex(
            model_name="creatorcreditledger",
            index=models.Index(fields=["wallet"], name="idx_creator_ledger_wallet"),
        ),
        migrations.AddIndex(
            model_name="creatorcreditledger",
            index=models.Index(
                fields=["transaction_type"], name="idx_creator_ledger_type"
            ),
        ),
        migrations.AddIndex(
            model_name="creatorcreditledger",
            index=models.Index(
                fields=["created_at"], name="idx_creator_ledger_created"
            ),
        ),
        migrations.AddIndex(
            model_name="creatorcreditledger",
            index=models.Index(
                fields=["expires_at"], name="idx_creator_ledger_expires"
            ),
        ),
        migrations.AddConstraint(
            model_name="creatorcreditledger",
            constraint=models.CheckConstraint(
                check=models.Q(("credits_after__gte", 0)), name="credits_after_check"
            ),
        ),
        migrations.AddConstraint(
            model_name="creatorcreditledger",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "credits_after",
                        django.db.models.expressions.CombinedExpression(
                            models.F("credits_before"), "+", models.F("credits_delta")
                        ),
                    )
                ),
                name="delta_consistency",
            ),
        ),
    ]
