# Generated by Django 4.2.7 on 2026-09-19 14:45

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lipaidox_creator_profile', '0012_alter_creatorprofile_plan_tier'),
        ('lipaidox_live_streaming', '0006_livestream_end_reason_alter_livestream_credits_used'),
        ('lipaidox_credits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveBillingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_sequence', models.IntegerField()),
                ('elapsed_seconds', models.IntegerField()),
                ('credits_consumed', models.DecimalField(decimal_places=6, max_digits=20)),
                ('credits_delta', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'live_billing_events',
                'ordering': ['event_sequence'],
            },
        ),
        migrations.CreateModel(
            name='LiveCreditReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credits_reserved', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('credits_consumed', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('credits_released', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('settled', 'Settled')], default='active', max_length=20)),
                ('end_reason', models.CharField(blank=True, choices=[('creator_ended', 'Creator ended'), ('credit_exhausted', 'Credits exhausted'), ('forced_ended', 'Ended by an administrator'), ('connection_lost', 'Connection lost')], default='', max_length=30)),
                ('started_at', models.DateTimeField()),
                ('last_heartbeat_at', models.DateTimeField()),
                ('last_sequence', models.IntegerField(default=0)),
                ('billed_seconds', models.IntegerField(default=0)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'live_credit_reservations',
            },
        ),
        migrations.AddField(
            model_name='creatorcreditwallet',
            name='reserved_credits',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='creatorcreditledger',
            name='credits_after',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='creatorcreditledger',
            name='credits_before',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='creatorcreditledger',
            name='credits_delta',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='creatorcreditledger',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('admin_gift', 'Admin Gift'), ('monthly_allocation', 'Monthly Allocation'), ('spent', 'Spent'), ('live_usage', 'Live Usage'), ('expired', 'Expired'), ('refunded', 'Refunded'), ('converted', 'Converted'), ('adjustment', 'Adjustment')], max_length=30),
        ),
        migrations.AlterField(
            model_name='creatorcreditwallet',
            name='free_monthly_credits',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='creatorcreditwallet',
            name='gifted_credits',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='creatorcreditwallet',
            name='monthly_credits_allocated',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='creatorcreditwallet',
            name='purchased_credits',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='creatorcreditwallet',
            name='total_credits_gifted',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='creatorcreditwallet',
            name='total_credits_purchased',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='creatorcreditwallet',
            name='total_credits_used',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='fancreditledger',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('admin_gift', 'Admin Gift'), ('monthly_allocation', 'Monthly Allocation'), ('spent', 'Spent'), ('live_usage', 'Live Usage'), ('expired', 'Expired'), ('refunded', 'Refunded'), ('converted', 'Converted'), ('adjustment', 'Adjustment')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='creatorcreditwallet',
            constraint=models.CheckConstraint(check=models.Q(('reserved_credits__gte', 0)), name='reserved_credits_check'),
        ),
        migrations.AddConstraint(
            model_name='creatorcreditwallet',
            constraint=models.CheckConstraint(check=models.Q(('reserved_credits__lte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('purchased_credits'), '+', models.F('free_monthly_credits')), '+', models.F('gifted_credits')))), name='reserved_within_balance_check'),
        ),
        migrations.AddField(
            model_name='livecreditreservation',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_credit_reservations', to='lipaidox_creator_profile.creatorprofile'),
        ),
        migrations.AddField(
            model_name='livecreditreservation',
            name='live_stream',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_reservation', to='lipaidox_live_streaming.livestream'),
        ),
        migrations.AddField(
            model_name='livecreditreservation',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='lipaidox_credits.creatorcreditwallet'),
        ),
        migrations.AddField(
            model_name='livebillingevent',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lipaidox_creator_profile.creatorprofile'),
        ),
        migrations.AddField(
            model_name='livebillingevent',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_events', to='lipaidox_credits.livecreditreservation'),
        ),
        migrations.AddIndex(
            model_name='livecreditreservation',
            index=models.Index(fields=['status'], name='idx_live_resv_status'),
        ),
        migrations.AddIndex(
            model_name='livecreditreservation',
            index=models.Index(fields=['creator', 'status'], name='idx_live_resv_creator_status'),
        ),
        migrations.AddConstraint(
            model_name='livecreditreservation',
            constraint=models.CheckConstraint(check=models.Q(('credits_reserved__gte', 0)), name='live_resv_reserved_check'),
        ),
        migrations.AddConstraint(
            model_name='livecreditreservation',
            constraint=models.CheckConstraint(check=models.Q(('credits_consumed__gte', 0)), name='live_resv_consumed_check'),
        ),
        migrations.AddConstraint(
            model_name='livecreditreservation',
            constraint=models.CheckConstraint(check=models.Q(('credits_consumed__lte', models.F('credits_reserved'))), name='live_resv_consumed_within_reserved_check'),
        ),
        migrations.AddConstraint(
            model_name='livecreditreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('creator',), name='live_resv_one_active_per_creator'),
        ),
        migrations.AddConstraint(
            model_name='livebillingevent',
            constraint=models.UniqueConstraint(fields=('reservation', 'event_sequence'), name='live_billing_event_unique_seq'),
        ),
    ]
