# Generated by Django 4.2.7 on 2026-09-19 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lipaidox_credits', '0003_convert_balances_to_prd_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=60)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('old_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'financial_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='creditpurchase',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='creditpurchase',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('user', 'idempotency_key'), name='credit_purchase_idempotency_unique'),
        ),
        migrations.AddField(
            model_name='financialauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_audit_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='financialauditlog',
            index=models.Index(fields=['action'], name='idx_fin_audit_action'),
        ),
        migrations.AddIndex(
            model_name='financialauditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='idx_fin_audit_entity'),
        ),
        migrations.AddIndex(
            model_name='financialauditlog',
            index=models.Index(fields=['-created_at'], name='idx_fin_audit_created'),
        ),
    ]
